import assert from "node:assert/strict";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { selectNextStoryScene } from "../src/story-manager.mjs";
import { NPC_ASSETS } from "../src/assets/asset-manifest.mjs";
import { STORY_OUTFIT_ASSETS } from "../src/story-outfit-assets.mjs";
import { DAY16_PRESENTATION_SCENES } from "../src/day16-presentation-data.mjs";
import { DAY16_CONTACT_CHOICES,DAY16_MEETING_CHOICES,DAY16_SHARING_CHOICES,applyLockedDay16ChoiceState,getLockedDay16ResumePresentation,getLockedDay16Segment,validateLockedDay16Runtime } from "../src/day16-campaign-runtime.mjs";
function roundTrip(state){const values=new Map(),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};SaveManager.save(state,storage);return SaveManager.load(storage,GAME_MODES.MARRIAGE_30);}
function makeState(){const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=16;state.storyHistory=[{sceneId:"m30-day15-current-leisure-date",choiceId:"leisure15_privacy_private_note",day:15,response:"완료"}];state.storyFlags={day16CurrentSocialCirclePending:true,day15ActivityStrategy:"leisure15_activity_each_pick",day15ChangeStrategy:"leisure15_change_shorten",day15PrivacyStrategy:"leisure15_privacy_private_note",day4ContactStrategy:"contact_direct_call",day4IdentityFocus:"identity_evidence_first",day4AccidentQuestion:"accident_direct_knowledge_only",day4SharingStrategy:"sharing_organize_first",day11ScheduleNoteMismatch:"unverified",day14PastPreferenceRecommendation:"unverified",day15LeisureReservationVisitLabel:"unverified",seojinAffection:12,seojinStatusInterest:19};state.scenario.featureUnlocks={finance:true,shop:true};return state;}
assert.equal(selectNextStoryScene(makeState())?.id,"m30-day16-current-social-circle");assert.equal(validateLockedDay16Runtime(),true);
const visualState=makeState();visualState.storyFlags.day16ContactStrategy="social16_contact_one_to_one";visualState.storyFlags.day16MeetingStrategy="social16_meeting_public_45";visualState.storyFlags.day16SharingStrategy="social16_sharing_current_notes";const all=[...getLockedDay16Segment(visualState,0),...getLockedDay16Segment(visualState,1),...getLockedDay16Segment(visualState,2),...getLockedDay16Segment(visualState,3)];
assert.equal(all.filter(x=>x.type==="transition").length,9);assert.equal(all.filter(x=>x.type==="choice").length,3);assert.equal(all.filter(x=>x.type==="sfx").length,18);assert.ok(all.filter(x=>x.type==="dialogue"||x.type==="narration").length>=60);for(const step of all.filter(x=>x.type==="transition").slice(0,8)){assert.ok(step.camera);assert.ok(step.characterAssetUrl);assert.equal(step.characterAssetUrl,step.characterId==="girlfriend"?STORY_OUTFIT_ASSETS.day8:NPC_ASSETS["best-friend"]);}assert.equal(Object.keys(DAY16_PRESENTATION_SCENES).length,8);for(const word of ["가짜 하은","진짜 하은","사고는 고의","범인","하은의 거짓말"])assert.equal(all.map(x=>x.text??x.label??"").join(" ").includes(word),false);
for(const contact of DAY16_CONTACT_CHOICES)for(const meeting of DAY16_MEETING_CHOICES)for(const sharing of DAY16_SHARING_CHOICES){let state=makeState();const before=structuredClone(state.scenario.featureUnlocks);assert.deepEqual(applyLockedDay16ChoiceState(state,contact.id),{stage:1});state=roundTrip(state);assert.equal(getLockedDay16ResumePresentation(state).characterAssetUrl,NPC_ASSETS["best-friend"]);assert.deepEqual(applyLockedDay16ChoiceState(state,contact.id),{stage:1});assert.equal(state.scenario.unlockedActions.filter(x=>x==="current-social-circle").length,1);assert.deepEqual(applyLockedDay16ChoiceState(state,meeting.id),{stage:2});state=roundTrip(state);assert.equal(state.storyFlags.day16ContactStrategy,contact.id);assert.equal(state.storyFlags.day16MeetingStrategy,meeting.id);assert.deepEqual(applyLockedDay16ChoiceState(state,sharing.id),{stage:3});state=roundTrip(state);assert.equal(state.storyFlags.day16SharingStrategy,sharing.id);assert.equal(state.storyFlags.day16CurrentSocialCircleCompleted,true);assert.equal(state.storyFlags.day17CurrentHealthRoutinePending,true);assert.equal(state.storyFlags.seojinAffection,12);assert.equal(state.storyFlags.seojinStatusInterest,19);assert.equal(state.storyFlags.day11ScheduleNoteMismatch,"unverified");assert.equal(state.storyFlags.day14PastPreferenceRecommendation,"unverified");assert.equal(state.storyFlags.day15LeisureReservationVisitLabel,"unverified");assert.deepEqual(state.scenario.featureUnlocks,before);for(const [key,value] of [["clues","current-social-circle-record"],["profileUnlocks","jihun-current"],["introducedNpcIds","best-friend"],["followUpHooks","day17-current-health-routine"]])assert.ok(state.scenario[key].includes(value));assert.equal(getLockedDay16Segment(state).at(-1).type,"sceneEnd");}
for(const option of DAY16_CONTACT_CHOICES){const s=makeState();applyLockedDay16ChoiceState(s,option.id);assert.equal(s.storyFlags.friendGroupAccess,false);if(option.id==="social16_contact_written_intro")assert.equal(s.storyFlags.jihunWrittenIntroStored,true);else assert.equal(s.storyFlags.jihunCurrentContact,true);}
for(const option of DAY16_MEETING_CHOICES){const s=makeState();applyLockedDay16ChoiceState(s,DAY16_CONTACT_CHOICES[0].id);applyLockedDay16ChoiceState(s,option.id);if(option.id==="social16_meeting_public_45"){assert.equal(s.storyFlags.nextMeetingPublic,true);assert.equal(s.storyFlags.nextMeetingMinutes,45)}if(option.id==="social16_meeting_topics_current"){assert.equal(s.storyFlags.currentTopicsOnly,true);assert.equal(s.storyFlags.oldMediaAutoOpen,false)}if(option.id==="social16_meeting_exit_anytime"){assert.equal(s.storyFlags.unconditionalExit,true);assert.equal(s.storyFlags.followupAutoPromise,false)}}
for(const option of DAY16_SHARING_CHOICES){const s=makeState();applyLockedDay16ChoiceState(s,DAY16_CONTACT_CHOICES[0].id);applyLockedDay16ChoiceState(s,DAY16_MEETING_CHOICES[0].id);applyLockedDay16ChoiceState(s,option.id);if(option.id==="social16_sharing_current_notes"){assert.equal(s.storyFlags.currentSocialCircleRecord,true);assert.equal(s.storyFlags.recordScope,"currentOnly")}if(option.id==="social16_sharing_old_media_closed"){assert.equal(s.storyFlags.oldMediaConsentRequired,true);assert.equal(s.storyFlags.oldMediaAutoOpen,false)}if(option.id==="social16_sharing_ask_each_person"){assert.equal(s.storyFlags.thirdPartyShareConsent,"perPerson");assert.equal(s.storyFlags.statusBroadcast,false)}}
{const s=makeState(),snapshot=structuredClone(s);assert.equal(applyLockedDay16ChoiceState(s,"invalid"),null);assert.deepEqual(s,snapshot);assert.equal(applyLockedDay16ChoiceState(s,DAY16_MEETING_CHOICES[0].id),null);assert.equal(s.storyFlags.day16RuntimeStage,undefined);applyLockedDay16ChoiceState(s,DAY16_CONTACT_CHOICES[0].id);const stage1=structuredClone(s);assert.equal(applyLockedDay16ChoiceState(s,DAY16_CONTACT_CHOICES[1].id),null);assert.deepEqual(s,stage1)}
{const legacy=makeState();delete legacy.storyFlags.day16RuntimeStage;const restored=roundTrip(legacy);assert.equal(getLockedDay16ResumePresentation(restored).backgroundId,"home-morning");assert.equal(restored.storyFlags.day16RuntimeStage,undefined)}
{const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_DATING});free.day=16;assert.equal(selectNextStoryScene(free)?.id==="m30-day16-current-social-circle",false)}
console.log("✓ DAY 16 27개 선택 경로·연출·저장 복원·축 독립성 PASS");
