import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {getDay19V4PlayableMiddle} from '../src/day19-v4-playable-middle.mjs';
import {validateDay19V4SourceStep} from '../src/day19-v4-source-selection.mjs';

const choose18=(s,key)=>applyDay18V4Choice(s,`day18_v4_${key}`);
function atBudget(shared){const appointment=shared?'HAEUN':'SOLO',s={money:42000,breakup:null,ended:false,storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:appointment,day17V4Choice9:shared?'day17_v4_life_haeun':'day17_v4_life_solo',day17V4DinnerAgreement:{day:18,partner:appointment,status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,shared?{}:{haeunContactAllowed:false});for(const key of shared?['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near']:['morning_solo','menu_familiar','solo_food','return_home','alone_stop','travel_life'])choose18(s,key);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);for(let n=1;n<=4;n++)applyDay19V4Choice(s,getDay19V4Options(s.storyFlags.day19V4)[0].id);return s;}
function assertOwned(steps){for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay19V4SourceStep(step),true,step.text??step.actionLabel);assert.equal(steps.some(step=>['narration','sourceNote'].includes(step.type)),false);assert.doesNotMatch(steps.map(step=>step.text??'').join('\n'),/\[함께|\[혼자|경로|실제 연락|SCENARIO|INTERNAL/);}

test('SCENE 06~08 choose exactly one shared or solo source route',()=>{for(const isShared of [true,false]){const s=atBudget(isShared),before=JSON.stringify(s.storyFlags.day19V4),steps=getDay19V4PlayableMiddle(s.storyFlags.day19V4);assertOwned(steps);assert.deepEqual(steps.filter(step=>step.type==='sceneDirection').map(step=>step.number),[6,7,8]);assert.equal(steps.at(-1).choiceNumber,5);assert.equal(steps.some(step=>['dialogue','message'].includes(step.type)&&step.speaker==='하은'),isShared);assert.deepEqual(steps.at(-1).options.map(option=>option.label),isShared?['각자 편하게 쓸 수 있는 만큼 같이 보자.','내가 더 내고 싶은 부분은 말해도 되지?','네가 돈 신경 안 썼으면 좋겠어.']:['생활비를 먼저 남긴다.','내가 꼭 쓰고 싶은 한 가지를 정한다.','일단 큰 금액부터 맞춰 본다.']);assert.equal(JSON.stringify(s.storyFlags.day19V4),before);}}
);

test('all C5 reactions preserve money ownership and reach choice 6',()=>{for(const isShared of [true,false]){const base=atBudget(isShared);for(const option of getDay19V4Options(base.storyFlags.day19V4)){const s=structuredClone(base),money=s.money;applyDay19V4Choice(s,option.id);const steps=getDay19V4PlayableMiddle(s.storyFlags.day19V4);assertOwned(steps);assert.equal(steps.find(step=>step.type==='sceneDirection').number,9);assert.equal(steps.at(-1).choiceNumber,6);assert.equal(s.money,money);assert.equal(s.storyFlags.day19V4.facts.transferredPartnerMoney,false);if(!isShared)assert.equal(steps.some(step=>step.speaker==='하은'),false);}}});

test('all C6 reactions select shared dialogue or solo reflection and reach SCENE 10~11 choice 7',()=>{for(const isShared of [true,false]){const base=atBudget(isShared);applyDay19V4Choice(base,getDay19V4Options(base.storyFlags.day19V4)[0].id);for(const option of getDay19V4Options(base.storyFlags.day19V4)){const s=structuredClone(base);applyDay19V4Choice(s,option.id);const steps=getDay19V4PlayableMiddle(s.storyFlags.day19V4);assertOwned(steps);assert.deepEqual(steps.filter(step=>step.type==='sceneDirection').map(step=>step.number),[10,11]);assert.equal(steps.at(-1).choiceNumber,7);if(!isShared)assert.equal(steps.some(step=>step.speaker==='하은'),false);}}});

test('C7 never fabricates Haeun approval on solo routes and closes at SCENE 12',()=>{for(const isShared of [true,false]){const base=atBudget(isShared);for(let n=5;n<=6;n++)applyDay19V4Choice(base,getDay19V4Options(base.storyFlags.day19V4)[0].id);for(const option of getDay19V4Options(base.storyFlags.day19V4)){const s=structuredClone(base);applyDay19V4Choice(s,option.id);const chapter=structuredClone(s.storyFlags.day19V4),steps=getDay19V4PlayableMiddle(s.storyFlags.day19V4);assertOwned(steps);assert.equal(steps.find(step=>step.type==='sceneDirection').number,12);assert.deepEqual(steps.at(-1),{type:'middleBoundary',nextScene:13});if(!isShared)assert.equal(steps.some(step=>step.speaker==='하은'),false);assert.deepEqual(getDay19V4PlayableMiddle(structuredClone(chapter)),steps);}}});
