import assert from "node:assert/strict";
import {DAY12_V3_PLAYABLE_SCRIPT_13_24,getDay12V3PlayableScene13To24,validateDay12V3PlayableScript13To24} from "../src/day12-v3-playable-script-13-24.mjs";
assert.equal(validateDay12V3PlayableScript13To24(),true);
assert.deepEqual(DAY12_V3_PLAYABLE_SCRIPT_13_24.map(x=>x.number),Array.from({length:12},(_,i)=>i+13));
const honest={storyFlags:{day12V3PriorSeojinPersonalInterest:true,day12V3Choice7:"day12_name_fun_and_fatigue",day12V3Choice8:"day12_ask_seojin_day_off",day12V3Choice9:"day12_invite_outside_work",day12V3Choice10:"day12_report_team_roles",day12V3Choice11:"day12_tell_seojin_lunch",day12V3Choice12:"day12_disclose_remaining_conversation",day12V3Choice13:"day12_intent_colleague",day12V3Choice14:"day12_plan_seoul_forest_photo"}};
assert.deepEqual(getDay12V3PlayableScene13To24(honest,17).selectedBranches,["mutualCuriosity","day12_invite_outside_work","inviteAccepted"]);
assert.deepEqual(getDay12V3PlayableScene13To24(honest,21).selectedBranches,["day12_disclose_remaining_conversation","discloseInvitation","day12_intent_colleague","disclosureNightEnd"]);
assert.ok(getDay12V3PlayableScene13To24(honest,18).steps.some(x=>x.type==="dialogue"&&x.speaker==="서진"&&x.text==="그럼 오늘은 셋이 본 걸로 하죠."));
assert.ok(getDay12V3PlayableScene13To24(honest,23).steps.some(x=>x.type==="dialogue"&&x.speaker==="하은"&&x.text.includes("혼자 보고 와도 돼")));
assert.ok(getDay12V3PlayableScene13To24(honest,20).steps.some(x=>x.type==="message"&&x.sender==="하은"&&x.text==="수고했어. 어땠어?"));
assert.equal(getDay12V3PlayableScene13To24(honest,20).steps[0].text,"회사 건물 밖 / 낮");
const contradiction={storyFlags:{day12V3Choice8:"day12_name_haeun_and_friends",day12V3Choice9:"day12_invite_outside_work",day12V3Choice11:"day12_tell_seojin_lunch",day12V3Choice12:"day12_claim_only_work",day12V3Choice14:"day12_plan_decide_after_rest"}};
assert.deepEqual(getDay12V3PlayableScene13To24(contradiction,17).selectedBranches,["comfortableColleague","day12_invite_outside_work","inviteDeferred"]);
assert.ok(getDay12V3PlayableScene13To24(contradiction,21).selectedBranches.includes("explicitContradiction"));
assert.deepEqual(getDay12V3PlayableScene13To24(contradiction,22).selectedBranches,["heartRemaining"]);
assert.deepEqual(getDay12V3PlayableScene13To24(contradiction,24).selectedBranches,["unresolvedEnding"]);
const deferred={storyFlags:{day12V3Choice8:"day12_keep_personal_distance",day12V3Choice9:"day12_end_for_rest",day12V3Choice11:"day12_ask_to_debrief_after_rest",day12V3Choice12:"day12_name_uncertainty_and_pause"}};
assert.deepEqual(getDay12V3PlayableScene13To24(deferred,17).selectedBranches,["keptDistance","day12_end_for_rest"]);
assert.deepEqual(getDay12V3PlayableScene13To24(deferred,22).selectedBranches,["callDeferred"]);
const serialized=JSON.stringify(DAY12_V3_PLAYABLE_SCRIPT_13_24);
for(const marker of ["저도 주문할 수 있어요","첫 번째 끝난 걸 잊어서요","제가 기대한 방식이 아니었을 뿐이지","질문만 가져와서 종이가 생겼네요","그녀가 믿는 것과 자신이 사실대로 말한 것은 같은 일이 아니었다","어느 길로 갈지도, 누구를 만날지도 정해지지 않았다"])assert.ok(serialized.includes(marker),marker);
for(const forbidden of ["가짜 하은","사고 범인","정식 복귀 확정","서진과 과거 연애 확정","아라와 반드시"])assert.equal(serialized.includes(forbidden),false,forbidden);
assert.throws(()=>getDay12V3PlayableScene13To24({},12),/UNKNOWN/);
console.log("day12-v3-playable-script-13-24.test: all assertions passed");
