import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import {DAY11_V3_PRESENTATION_SCENES,DAY11_V3_READY_REUSE_ASSETS,DAY11_V3_REQUIRED_NEW_ASSETS,getDay11V3Presentation,validateDay11V3PresentationAudit} from "../src/day11-v3-presentation-data.mjs";

assert.equal(validateDay11V3PresentationAudit(),true);
assert.equal(Object.keys(DAY11_V3_PRESENTATION_SCENES).length,24);
assert.equal(Object.keys(DAY11_V3_REQUIRED_NEW_ASSETS).length,7);
assert.ok(Object.values(DAY11_V3_READY_REUSE_ASSETS).every(asset=>existsSync(new URL(`../${asset}`,import.meta.url))));
const readyAssets=Object.values(DAY11_V3_REQUIRED_NEW_ASSETS).filter(asset=>asset.status==="ready-new");
const pendingAssets=Object.values(DAY11_V3_REQUIRED_NEW_ASSETS).filter(asset=>asset.status==="production-required");
assert.equal(readyAssets.length,7);
assert.equal(pendingAssets.length,0);
assert.ok(readyAssets.every(asset=>existsSync(new URL(`../${asset.path}`,import.meta.url))));
assert.ok(pendingAssets.every(asset=>!existsSync(new URL(`../${asset.path}`,import.meta.url))));
const soraAsset=DAY11_V3_REQUIRED_NEW_ASSETS.soraSprite;
const soraPng=readFileSync(new URL(`../${soraAsset.path}`,import.meta.url));
assert.equal(soraPng.readUInt32BE(16),1024);
assert.equal(soraPng.readUInt32BE(20),1536);
assert.equal(soraPng[25],6,"Sora sprite must use PNG RGBA color type");

const attending={storyFlags:{day11V3AttendedSoraMeeting:true,day11V3ShoulderLeanOccurred:true,day11V3RelationshipBand:"HIGH"}};
assert.equal(getDay11V3Presentation(5,attending).requiredAsset,"cafeThreeShot");
assert.match(getDay11V3Presentation(4,attending).eventCgUrl,/cg-day11-v3-bakery-choice-pov-v1\.png$/);
assert.match(getDay11V3Presentation(5,attending).eventCgUrl,/cg-day11-v3-haeun-sora-cafe-three-shot-v1\.png$/);
assert.match(getDay11V3Presentation(11,attending).eventCgUrl,/cg-day11-v3-cake-trip-boundary-v1\.png$/);
assert.match(getDay11V3Presentation(19,attending).eventCgUrl,/cg-day11-v3-siwoo-exhibition-message-pov-v1\.png$/);
assert.equal(getDay11V3Presentation(16,attending).secondaryCharacterId,"sora-day11");
assert.match(getDay11V3Presentation(16,attending).secondaryCharacterAssetUrl,/sora-day11-cafe-casual-2d-v4\.png$/);
assert.equal(getDay11V3Presentation(22,attending).requiredAsset,"shoulderLean");
assert.match(getDay11V3Presentation(22,attending).eventCgUrl,/cg-day11-v3-shoulder-lean-bench-v1\.png$/);
const phone={storyFlags:{day11V3AttendedSoraMeeting:false,day11V3RelationshipBand:"MID"}};
assert.match(getDay11V3Presentation(5,phone).backgroundUrl,/004_small-cafe\.png$/);
assert.equal(getDay11V3Presentation(4,phone).eventCgUrl,null);
assert.equal(getDay11V3Presentation(5,phone).characterId,null);
assert.equal(getDay11V3Presentation(16,phone).secondaryCharacterId,null);
assert.equal(getDay11V3Presentation(19,phone).requiredAsset,null);
assert.equal(getDay11V3Presentation(22,phone).requiredAsset,null);
assert.equal(getDay11V3Presentation(22,{storyFlags:{day11V3AttendedSoraMeeting:false,day11V3ShoulderLeanOccurred:true}}).requiredAsset,null);
assert.equal(getDay11V3Presentation(24,{storyFlags:{day11V3RelationshipBand:"LOW"}}).requiredAsset,null);
assert.match(getDay11V3Presentation(24,{storyFlags:{day11V3RelationshipBand:"HIGH",day11V3UnresolvedConflict:false}}).eventCgUrl,/cg-day11-v3-cake-photo-message-pov-v1\.png$/);
assert.equal(getDay11V3Presentation(24,{storyFlags:{day11V3RelationshipBand:"HIGH",day11V3UnresolvedConflict:true}}).requiredAsset,null);
console.log("day11-v3-presentation-audit.test: all assertions passed");
