import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {getDay19V4PlayableCandidates} from '../src/day19-v4-playable-candidates.mjs';
import {validateDay19V4SourceStep} from '../src/day19-v4-source-selection.mjs';

const c18=(s,k)=>applyDay18V4Choice(s,`day18_v4_${k}`);
function start(shared){const p=shared?'HAEUN':'SOLO',s={money:42000,breakup:null,ended:false,storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:p,day17V4Choice9:shared?'day17_v4_life_haeun':'day17_v4_life_solo',day17V4DinnerAgreement:{day:18,partner:p,status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,shared?{}:{haeunContactAllowed:false});for(const k of shared?['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near']:['morning_solo','menu_familiar','solo_food','return_home','alone_stop','travel_life'])c18(s,k);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);for(let n=1;n<=7;n++)applyDay19V4Choice(s,getDay19V4Options(s.storyFlags.day19V4)[0].id);return s;}
function owned(steps){for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay19V4SourceStep(step),true,step.text??step.actionLabel);assert.equal(steps.some(step=>['narration','sourceNote'].includes(step.type)),false);assert.doesNotMatch(steps.map(step=>step.text??'').join('\n'),/\[함께|\[혼자|경로|SCENARIO|INTERNAL/);}
function branchAt(base,target){const s=structuredClone(base);while(s.storyFlags.day19V4.phase!==target)applyDay19V4Choice(s,getDay19V4Options(s.storyFlags.day19V4)[0].id);return s;}

test('SCENE 13 exposes C8 without turning interest into acceptance',()=>{for(const shared of [true,false]){const s=start(shared),steps=getDay19V4PlayableCandidates(s.storyFlags.day19V4);owned(steps);assert.equal(steps[0].number,13);assert.equal(steps.at(-1).choiceNumber,8);assert.equal(s.storyFlags.day19V4.facts.reservationStatus,'NOT_RESERVED');if(!shared)assert.equal(steps.some(x=>x.speaker==='하은'),false);}});

test('C8 through C11 all preserve candidate-only semantics',()=>{for(const shared of [true,false]){const root=start(shared);for(const [phase,nextChoice,sceneNumber] of [['companion_wait',9,14],['comfort_spend',10,15],['candidate',11,16],['reservation',12,17]]){const base=branchAt(root,phase);for(const option of getDay19V4Options(base.storyFlags.day19V4)){const s=structuredClone(base),money=s.money;applyDay19V4Choice(s,option.id);const steps=getDay19V4PlayableCandidates(s.storyFlags.day19V4);owned(steps);assert.equal(steps.find(x=>x.type==='sceneDirection').number,sceneNumber);assert.equal(steps.at(-1).choiceNumber,nextChoice);assert.equal(s.storyFlags.day19V4.facts.travelPaymentMade,false);assert.equal(s.storyFlags.day19V4.facts.reservationStatus,phase==='reservation'?'CANDIDATE_ONLY':'NOT_RESERVED');assert.equal(s.money,money);if(!shared)assert.equal(steps.some(x=>x.speaker==='하은'),false);}}}});

test('C12 reactions never count unknown lottery winnings and close at SCENE 18 boundary',()=>{for(const shared of [true,false]){const root=start(shared),base=branchAt(root,'expectation');applyDay19V4Choice(base,getDay19V4Options(base.storyFlags.day19V4)[0].id);assert.equal(base.storyFlags.day19V4.phase,'dinner');const before=structuredClone(base.storyFlags.day19V4),steps=getDay19V4PlayableCandidates(base.storyFlags.day19V4);owned(steps);assert.deepEqual(steps.at(-1),{type:'candidateBoundary',nextScene:18});assert.equal(base.storyFlags.day19V4.facts.lotteryWinningsCounted,false);assert.equal(base.storyFlags.day19V4.facts.travelPaymentMade,false);assert.deepEqual(getDay19V4PlayableCandidates(structuredClone(before)),steps);}});

test('reservation-first wording ends with hand withdrawal, not a booking',()=>{const s=branchAt(start(true),'reservation'),option=getDay19V4Options(s.storyFlags.day19V4).find(x=>x.id.endsWith('_reserve_first'));applyDay19V4Choice(s,option.id);const steps=getDay19V4PlayableCandidates(s.storyFlags.day19V4),text=steps.map(x=>x.text??'').join('\n');owned(steps);assert.match(text,/나는 못 간다고 말하기 어려워질 것 같아/);assert.equal(steps.some(x=>x.status==='payment-hand-away'),true);assert.doesNotMatch(text,/예약했|결제했|예약 완료/);assert.equal(s.storyFlags.day19V4.facts.reservationStatus,'CANDIDATE_ONLY');});
