import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {
  applyDay19V4GameChoice, completeDay19V4GameChapter, getDay19V4GameCompatibility,
  getDay19V4GameResumePresentation, getDay19V4GameSegment, prepareDay19V4GameEntry
} from '../src/day19-v4-game-bridge.mjs';

function state(shared=true){const p=shared?'HAEUN':'SOLO',s={day:19,money:42000,breakup:null,ended:false,economyLedger:[],storyHistory:[],pendingStoryId:'m30-day19-current-shared-chore',storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:p,day17V4Choice9:shared?'day17_v4_life_haeun':'day17_v4_life_solo',day17V4DinnerAgreement:{day:18,partner:p,status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,shared?{}:{haeunContactAllowed:false});for(const k of shared?['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near']:['morning_solo','menu_familiar','solo_food','return_home','alone_stop','travel_life'])applyDay18V4Choice(s,`day18_v4_${k}`);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});return s;}
const choose=(s,index=0)=>applyDay19V4GameChoice(s,getDay19V4Options(s.storyFlags.day19V4)[index].id);
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}};

test('bridge starts V4 without mutating legacy DAY19 saves',()=>{const s=state();assert.equal(getDay19V4GameCompatibility(s).mode,'V4_NEW');assert.equal(prepareDay19V4GameEntry(s).mode,'V4');assert.equal(getDay19V4GameSegment(s).at(-1).choiceNumber,1);const legacy=state();legacy.storyFlags.day19RuntimeStage=1;assert.equal(prepareDay19V4GameEntry(legacy).mode,'LEGACY');assert.equal(legacy.storyFlags.day19V4,undefined);});

test('bridge stitches all four playable sections and strips boundary markers',()=>{for(const shared of[true,false]){const s=state(shared);prepareDay19V4GameEntry(s);let guard=0;while(s.storyFlags.day19V4.phase!=='ending'){const before=s.storyFlags.day19V4.phase,{steps}=choose(s);assert.ok(guard++<18);assert.equal(steps.some(x=>/Boundary$/.test(x.type)),false);assert.ok(steps.some(x=>x.type==='choice')||s.storyFlags.day19V4.phase==='ending',before);}const steps=getDay19V4GameSegment(s);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.ok(steps.filter(x=>x.type==='transition').some(x=>x.sceneNumber===24));assert.doesNotThrow(()=>getDay19V4GameResumePresentation(s));}});

test('lottery cost is atomic, single, and never reveals or credits a result',()=>{const s=state(false);s.storyFlags.day19EntertainmentBudgetReserved=true;prepareDay19V4GameEntry(s);choose(s);choose(s);const option=getDay19V4Options(s.storyFlags.day19V4).find(x=>x.id.endsWith('_lottery')),before=s.money;const {purchase}=applyDay19V4GameChoice(s,option.id);assert.equal(purchase.entry.amount,-5000);assert.equal(s.money,before-5000);assert.equal(s.storyFlags.day19V4LotteryPurchase.resultStatus,'UNOPENED');assert.equal(s.storyFlags.day19V4LotteryPurchase.prizeCounted,false);assert.equal(s.economyLedger.filter(x=>x.label==='DAY 19 결과 미확인 복권 구매').length,1);assert.equal(s.storyFlags.day19V4.facts.lotteryWinningsCounted,false);});

test('failed lottery application rolls money and ledger back',()=>{const s=state(false);s.storyFlags.day19EntertainmentBudgetReserved=true;prepareDay19V4GameEntry(s);choose(s);choose(s);s.money=4999;const option=getDay19V4Options(s.storyFlags.day19V4).find(x=>x.id.endsWith('_lottery')),before=structuredClone(s);assert.throws(()=>applyDay19V4GameChoice(s,option.id),/BUDGET_CHANGED/);assert.equal(s.money,before.money);assert.deepEqual(s.economyLedger,before.economyLedger);assert.equal(s.storyFlags.day19V4LotteryPurchase,undefined);assert.deepEqual(s.storyFlags.day19V4,before.storyFlags.day19V4);});

test('completion records exact V4 history and DAY20 hook without legacy choice effects',()=>{const s=state();prepareDay19V4GameEntry(s);while(s.storyFlags.day19V4.phase!=='ending')choose(s);const end=completeDay19V4GameChapter(s,{type:'chapterCompletionCue',day:19,finalSceneReached:true});assert.deepEqual(end,{type:'sceneEnd',day:19,complete:true});assert.equal(s.storyFlags.day19V4.complete,true);assert.equal(s.storyFlags.day19V4Day20HookPending,true);assert.equal(s.storyFlags.day19RuntimeComplete,true);assert.equal(s.storyHistory.filter(x=>x.sceneId==='m30-day19-current-shared-chore').length,1);assert.equal(s.storyHistory[0].scenarioId,'day19-notion-v4');assert.equal(s.storyFlags.day19CurrentSharedChoreCompleted,undefined);});

test('real save manager round-trips a mid-DAY19 checkpoint without changing the next segment',()=>{const s=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});const seed=state(true);s.day=19;s.breakup=null;s.ended=false;s.storyFlags=seed.storyFlags;s.storyHistory=[];s.pendingStoryId='m30-day19-current-shared-chore';prepareDay19V4GameEntry(s);for(let i=0;i<9;i++)choose(s,i%3);const before=getDay19V4GameSegment(s),store=storage();SaveManager.save(s,store);const loaded=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.ok(loaded);assert.deepEqual(loaded.storyFlags.day19V4,s.storyFlags.day19V4);assert.deepEqual(getDay19V4GameSegment(loaded),before);});

test('main runtime selects V4 bridge and keeps legacy expansion/history recorder out of new saves',()=>{const source=readFileSync(new URL('../game.js',import.meta.url),'utf8');assert.match(source,/day19-v4-game-bridge\.mjs\?v=1/);assert.match(source,/lockedDay19\?getDay19Segment\(state\)/);assert.match(source,/if\(lockedDay19\)\{if\(day19V4\)/);assert.match(source,/step\.day===19\?completeDay19V4GameChapter/);assert.match(source,/completionCue\.day===19\)completeDay19V4GameChapter/);assert.match(source,/lockedDay19&&!day19V4\?19/);assert.match(source,/LOCKED_DAY19_SCENE_ID&&!state\.storyFlags\?\.day19V4/);});
