import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,completeDay19V4,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {applyDay20V4Choice,beginDay20V4,getDay20V4Options} from '../src/day20-v4-state-contract.mjs';
import {getDay20V4PlayableOpening} from '../src/day20-v4-playable-opening.mjs';
import {validateDay20V4SourceStep} from '../src/day20-v4-source-selection.mjs';

function state(shared=true){const partner=shared?'HAEUN':'SOLO',s={breakup:null,ended:false,money:42000,storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:partner,day17V4Choice9:shared?'day17_v4_life_haeun':'day17_v4_life_solo',day17V4DinnerAgreement:{day:18,partner,status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,shared?{}:{haeunContactAllowed:false});for(const key of shared?['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near']:['morning_solo','menu_familiar','solo_food','return_home','alone_stop','travel_life'])applyDay18V4Choice(s,`day18_v4_${key}`);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);while(s.storyFlags.day19V4.phase!=='ending'){const opts=getDay19V4Options(s.storyFlags.day19V4),i=shared&&s.storyFlags.day19V4.phase==='dinner'?2:shared&&s.storyFlags.day19V4.phase==='tomorrow_table'?0:0;applyDay19V4Choice(s,opts[i].id);}completeDay19V4(s,{type:'chapterCompletionCue',day:19,finalSceneReached:true});beginDay20V4(s);return s;}
const choose=(state,index=0)=>applyDay20V4Choice(state,getDay20V4Options(state.storyFlags.day20V4)[index].id);
const assertSourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay20V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);};

test('opening exposes exact source choices and reactions through SCENE 04',()=>{const s=state(true);let steps=getDay20V4PlayableOpening(s.storyFlags.day20V4);assert.equal(steps[0].number,1);assert.equal(steps.at(-1).choiceNumber,1);assertSourced(steps);choose(s,1);steps=getDay20V4PlayableOpening(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.text==='오늘은 같이 조금씩 해 먹을까?'));assert.equal(steps.at(-1).choiceNumber,2);assertSourced(steps);choose(s,0);steps=getDay20V4PlayableOpening(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===3));assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===4));assert.ok(steps.some(step=>step.text==='네가 자랑한 분야 좀 볼까.'));assert.equal(steps.at(-1).choiceNumber,3);assertSourced(steps);choose(s,0);steps=getDay20V4PlayableOpening(s.storyFlags.day20V4);assert.equal(steps.at(-1).type,'openingBoundary');assert.equal(steps.at(-1).nextScene,5);assertSourced(steps);});

test('solo opening never creates Haeun arrival, dialogue, or a second cup',()=>{const s=state(false),steps=getDay20V4PlayableOpening(s.storyFlags.day20V4);assert.equal(steps.some(step=>step.type==='sceneDirection'&&step.number===3),false);assert.equal(steps.some(step=>step.speaker==='하은'||step.sender==='하은'),false);assert.ok(steps.some(step=>step.text?.includes('아무도 고르지 않은 컵을 하은의 컵이라고 부르지 않았다')));assert.equal(steps.at(-1).choiceNumber,5);assertSourced(steps);choose(s);assert.equal(getDay20V4PlayableOpening(s.storyFlags.day20V4).at(-1).nextScene,23);});

test('short-tea opening closes toward the agreed short ending, not intimacy',()=>{const s=state(true);choose(s,2);choose(s);choose(s);const steps=getDay20V4PlayableOpening(s.storyFlags.day20V4);assert.equal(s.storyFlags.day20V4.phase,'night_end');assert.equal(steps.at(-1).nextScene,20);assert.equal(s.storyFlags.day20V4.facts.closenessChoice,null);assert.equal(s.storyFlags.day20V4.facts.stayedOver,false);assertSourced(steps);});
