import assert from 'node:assert/strict';
import test from 'node:test';
import {day25ContinuedFixture,day25EndedFixture,day25NewMeetingFixture} from './day25-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location,resolveDay25V4NewMeeting} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,completeDay26V4,getDay26V4Entry,getDay26V4Options,resolveDay26V4Attendance,resolveDay26V4Jihoon,resolveDay26V4NewMeaning,resolveDay26V4NewNext,validateDay26V4} from '../src/day26-v4-state-contract.mjs';

const choose25=(state,suffix)=>{const options=getDay25V4Options(state.storyFlags.day25V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`DAY25:${state.storyFlags.day25V4.phase}:${suffix}`);applyDay25V4Choice(state,selected.id);};
function complete25(state,{friend='meet',meeting='ACCEPTED'}={}){beginDay25V4(state);let guard=0;while(state.storyFlags.day25V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){const proposal=state.storyFlags.day25V4.facts.proposal;resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:proposal==='PREPARE_MARRIAGE'?'PREPARE_MARRIAGE':'REDISCUSS'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='new_meeting_resolution'){resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:state.storyFlags.day25V4.input.newMeeting.recipient,outcome:meeting});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}choose25(state,phase==='friend_meal'?friend:undefined);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});return state;}
const choose26=(state,suffix)=>{const options=getDay26V4Options(state.storyFlags.day26V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`DAY26:${state.storyFlags.day26V4.phase}:${suffix}`);return applyDay26V4Choice(state,selected.id);};
function finish26(state){let guard=0;while(state.storyFlags.day26V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day26V4.phase;if(phase==='attendance_resolution'){resolveDay26V4Attendance(state,{type:'attendanceChangeResponse',accepted:true});continue;}if(phase==='jihoon_resolution'||phase==='solo_friend_resolution'){resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:false});continue;}if(phase==='new_meaning_resolution'){resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:state.storyFlags.day26V4.input.newMeeting.recipient,outcome:'NEED_TIME'});continue;}if(phase==='new_next_resolution'){resolveDay26V4NewNext(state,{type:'newMeetingNextResponse',recipient:state.storyFlags.day26V4.input.newMeeting.recipient,outcome:'DEFERRED'});continue;}choose26(state);}return state;}

test('DAY26 entry freezes verified DAY23-25 outcomes and preserves legacy saves',()=>{const state=complete25(day25ContinuedFixture());const entry=getDay26V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.groupMealScheduled,true);assert.equal(entry.input.relationshipContinues,true);assert.equal(entry.input.haeunFutureOutcome,'PREPARE_MARRIAGE');assert.equal(entry.input.haeunNightEligible,true);assert.equal(entry.input.newMeeting,null);const legacy=structuredClone(state);legacy.storyFlags.day26RuntimeStage=1;assert.equal(getDay26V4Entry(legacy).mode,'LEGACY');const broken=structuredClone(state);broken.storyFlags.day25V4.facts.friendMealScheduled=false;assert.equal(getDay26V4Entry(broken).mode,'BLOCKED_PREREQUISITE');});

test('group meal keeps overstatement, acknowledgement, promise and actual correction distinct',()=>{const state=complete25(day25ContinuedFixture());beginDay26V4(state);choose26(state);choose26(state);choose26(state,'shared_story');choose26(state,'fast');assert.equal(state.storyFlags.day26V4.facts.publicOverstatement,true);choose26(state,'explain');assert.equal(state.storyFlags.day26V4.facts.haeunSpeechInterrupted,true);while(state.storyFlags.day26V4.phase!=='group_private')choose26(state);choose26(state,'admit');assert.equal(state.storyFlags.day26V4.facts.overstatementAcknowledged,true);assert.equal(state.storyFlags.day26V4.facts.overstatementCorrected,false);choose26(state,'name_override');assert.equal(state.storyFlags.day26V4.facts.overstatementCorrectionPromised,true);assert.equal(state.storyFlags.day26V4.facts.overstatementCorrected,false);choose26(state,'correct');assert.equal(state.storyFlags.day26V4.facts.overstatementCorrected,true);finish26(state);assert.equal(state.storyFlags.day26V4.facts.route,'GROUP_MEAL');assert.equal(validateDay26V4(state.storyFlags.day26V4),true);});

test('rest request waits for current attendance response before cancelling a real group meal',()=>{const state=complete25(day25ContinuedFixture());beginDay26V4(state);choose26(state,'rest');assert.equal(state.storyFlags.day26V4.phase,'attendance_resolution');assert.equal(state.storyFlags.day26V4.facts.route,null);resolveDay26V4Attendance(state,{type:'attendanceChangeResponse',accepted:true});assert.equal(state.storyFlags.day26V4.facts.route,'SOLO_DAY');assert.equal(state.storyFlags.day26V4.phase,'solo_life');});

test('Jihoon being known does not create a separate meal without his current response',()=>{const state=complete25(day25ContinuedFixture(),{friend:'later'});beginDay26V4(state);choose26(state);assert.equal(state.storyFlags.day26V4.phase,'jihoon_resolution');assert.equal(state.storyFlags.day26V4.facts.jihoonMealAccepted,null);resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:false});assert.equal(state.storyFlags.day26V4.facts.route,'SOLO_DAY');});

test('accepted single new meeting keeps relationship intent and next appointment responses separate',()=>{const state=complete25(day25NewMeetingFixture(),{meeting:'ACCEPTED'});beginDay26V4(state);choose26(state);assert.equal(state.storyFlags.day26V4.facts.route,'NEW_MEETING');choose26(state);choose26(state,'romance');assert.equal(state.storyFlags.day26V4.phase,'new_meaning_resolution');resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'ARA',outcome:'NEED_TIME'});assert.equal(state.storyFlags.day26V4.facts.newMeaningResponse,'NEED_TIME');choose26(state,'meet_again');assert.equal(state.storyFlags.day26V4.phase,'new_next_resolution');resolveDay26V4NewNext(state,{type:'newMeetingNextResponse',recipient:'ARA',outcome:'DECLINED'});assert.equal(state.storyFlags.day26V4.facts.newNextResponse,'DECLINED');choose26(state);choose26(state);assert.equal(state.storyFlags.day26V4.phase,'ending');assert.equal(state.storyFlags.day26V4.facts.day27Route,'INDEPENDENT_LIFE');});

test('rescheduled new meeting stays a solo day and completion opens only DAY27 hook',()=>{const state=complete25(day25NewMeetingFixture(),{meeting:'RESCHEDULED'});beginDay26V4(state);choose26(state,'rest');finish26(state);assert.equal(state.storyFlags.day26V4.facts.route,'SOLO_DAY');assert.equal(validateDay26V4(state.storyFlags.day26V4),true);completeDay26V4(state,{type:'chapterCompletionCue',day:26,finalSceneReached:true});assert.equal(state.storyFlags.day26V4.complete,true);assert.equal(state.storyFlags.day26V4Day27HookPending,true);assert.equal(state.storyFlags.day25V4Day26HookPending,false);const forged=structuredClone(state.storyFlags.day26V4);forged.input.currentMoney+=1;assert.equal(validateDay26V4(forged),false);assert.equal(state.storyFlags.day26RuntimeComplete,undefined);});
