import assert from 'node:assert/strict';
import test from 'node:test';
import {day27FriendlyFixture,day27PublicCorrectionFixture} from './day27-v4-playable-fixture.mjs';
import {applyDay27V4Choice,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4Relationship} from '../src/day27-v4-state-contract.mjs';
import {getDay27V4PlayableMiddle} from '../src/day27-v4-playable-middle.mjs';
import {validateDay27V4SourceStep} from '../src/day27-v4-source-selection.mjs';

const choose=(state,suffix)=>{const option=getDay27V4Options(state.storyFlags.day27V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day27V4.phase}:${suffix}`);applyDay27V4Choice(state,option.id);};
const enterHonest=state=>{choose(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});choose(state);};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay27V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}

test('SCENE10-17 honest route emits exact-backed C8-C12 and waits for Haeun relationship response',()=>{const state=day27FriendlyFixture(),seen=[];enterHonest(state);let guard=0;while(state.storyFlags.day27V4.phase!=='relationship_resolution'){assert.ok(guard++<10);const steps=getDay27V4PlayableMiddle(state.storyFlags.day27V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered,state.storyFlags.day27V4.phase);seen.push(offered.choiceNumber);choose(state);}let steps=getDay27V4PlayableMiddle(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).type,'day27RelationshipCue');assert.deepEqual(seen,[8,9,10,12]);resolveDay27V4Relationship(state,{type:'day27RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});steps=getDay27V4PlayableMiddle(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).nextScene,18);assert.match(JSON.stringify(steps),/집에 가면 잠깐 조용히 있고 싶어/);});

test('SCENE15 exists only for an actual uncorrected DAY26 public overstatement',()=>{const clean=day27FriendlyFixture();enterHonest(clean);choose(clean);choose(clean);choose(clean);assert.equal(clean.storyFlags.day27V4.phase,'conversation_end');assert.doesNotMatch(JSON.stringify(getDay27V4PlayableMiddle(clean.storyFlags.day27V4)),/어제 네가 신난 게 싫었던 건 아니야/);const state=day27PublicCorrectionFixture();enterHonest(state);choose(state);choose(state);choose(state);assert.equal(state.storyFlags.day27V4.phase,'public_correction');let steps=getDay27V4PlayableMiddle(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.find(step=>step.type==='choice').choiceNumber,11);assert.match(JSON.stringify(steps),/그런데 네 대답까지 내가 했지/);choose(state,'correct_myself');assert.equal(state.storyFlags.day27V4.facts.publicCorrectionDone,true);steps=getDay27V4PlayableMiddle(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.find(step=>step.type==='choice').choiceNumber,12);});

test('explicit relationship ending renders a non-grabbing farewell and cannot keep contact',()=>{const state=day27FriendlyFixture();enterHonest(state);choose(state);choose(state);choose(state);choose(state,'end_relationship');assert.equal(state.storyFlags.day27V4.facts.relationshipContinues,false);assert.equal(state.storyFlags.day27V4.facts.contactAllowed,false);const steps=getDay27V4PlayableMiddle(state.storyFlags.day27V4);sourced(steps);assert.match(JSON.stringify(steps),/혼자 갈게/);assert.match(JSON.stringify(steps),/그 자리에서 작별했다/);assert.doesNotMatch(JSON.stringify(steps),/집에 가면 잠깐 조용히/);});
