import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {applyDay29V4Choice,beginDay29V4,getDay29V4Options,resolveDay29V4Evening} from '../src/day29-v4-state-contract.mjs';
import {getDay29V4PlayableOpening} from '../src/day29-v4-playable-opening.mjs';
import {getDay29V4RuntimeResolution} from '../src/day29-v4-runtime-resolution.mjs';
import {validateDay29V4SourceStep} from '../src/day29-v4-source-selection.mjs';

const choose28=state=>applyDay28V4Choice(state,getDay28V4Options(state.storyFlags.day28V4)[0].id);
function finish28(state,newRoute=false){while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});continue;}if(phase==='new_relationship_resolution'){resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});continue;}const options=getDay28V4Options(state.storyFlags.day28V4);const option=phase==='continuing_distance'?options.find(item=>item.id.endsWith('_talk_only')):phase==='new_meeting_wish'?options.find(item=>item.id.endsWith('_want_romance')):options[0];applyDay28V4Choice(state,option.id);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});beginDay29V4(state);return state;}
const friendly=()=>{const state=day28FriendlyFixture();state.storyFlags.day7V3Complete=true;return finish28(state);};
const solo=()=>finish28(day28SoloFixture());
const mixed=()=>finish28(day28NewMeetingFixture(),true);
const choose29=(state,suffix)=>{const options=getDay29V4Options(state.storyFlags.day29V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day29V4.phase}:${suffix}`);applyDay29V4Choice(state,option.id);};
function sourced(steps){for(const step of steps)if(['dialogue','monologue','playerNarration','storyActionCue'].includes(step.type))assert.equal(validateDay29V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);}

test('SCENE01-09 exposes all common choices in order with whole-line source evidence',()=>{const state=friendly(),seen=[];let guard=0;while(state.storyFlags.day29V4.phase!=='evening_resolution'){assert.ok(guard++<12);const steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered,state.storyFlags.day29V4.phase);seen.push(offered.choiceNumber);choose29(state);}assert.deepEqual(seen,[1,2,3,4,5,6,7,8,9]);const steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).type,'day29EveningCue');assert.equal(steps.at(-1).target,'HAEUN');});

test('missing possessions never create bought clothes, photos, cards or flowers',()=>{const state=solo();state.storyFlags.day29V4.input.ownedOutfit=false;state.storyFlags.day29V4.input.actualPhoto=false;state.storyFlags.day29V4.input.haeunCardReceived=false;state.storyFlags.day29V4.input.ownedFlower=false;assert.equal(getDay29V4PlayableOpening(state.storyFlags.day29V4).at(-1).choiceNumber,1);choose29(state);let steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);assert.doesNotMatch(JSON.stringify(steps),/예전에 쇼핑하며 직접 산 옷이 있다면/);choose29(state);steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);assert.deepEqual(steps.at(-1).options.map(option=>option.id.split('_').at(-1)),['close']);choose29(state);assert.equal(state.storyFlags.day29V4.phase,'flower');steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);sourced(steps);assert.doesNotMatch(JSON.stringify(steps),/봉투를 열었다|꽃을 샀던 날/);assert.match(JSON.stringify(steps),/받지 않은 카드를 만들지 않고|아무것도 사지 않았던 창가/);});

test('solo history reaches SCENE19 without Haeun or an invented response',()=>{const state=solo();while(state.storyFlags.day29V4.phase!=='solo_evening')choose29(state);const steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).nextScene,19);assert.doesNotMatch(JSON.stringify(steps),/하은|day29EveningCue/);assert.equal(state.storyFlags.day29V4.facts.eveningTarget,null);});

test('current runtime answer preserves sealed Haeun and Ara targets and locations',()=>{for(const [state,target] of [[friendly(),'HAEUN'],[mixed(),'ARA']]){while(state.storyFlags.day29V4.phase!=='evening_resolution')choose29(state);const cue=getDay29V4PlayableOpening(state.storyFlags.day29V4).at(-1),response=getDay29V4RuntimeResolution(state,cue);assert.equal(response.target,target);assert.equal(response.accepted,true);if(target==='ARA')assert.equal(response.location,'OUTSIDE');resolveDay29V4Evening(state,response);const steps=getDay29V4PlayableOpening(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).nextScene,target==='HAEUN'?10:18);assert.doesNotMatch(JSON.stringify(steps),target==='HAEUN'?/ARA|YURI|SEOJIN/:/하은/);}});
