import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {applyDay22V4GameChoice,applyDay22V4GameResolution,completeDay22V4GameChapter,getDay22V4GameCompatibility,getDay22V4GameResumePresentation,getDay22V4GameSegment,prepareDay22V4GameEntry} from '../src/day22-v4-game-bridge.mjs';
import {getDay22V4RuntimeResolution} from '../src/day22-v4-runtime-resolution.mjs';
import {getDay22V4Options} from '../src/day22-v4-state-contract.mjs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {completedDay21ForDay22} from './day22-v4-fixture.mjs';

function state(route='BUSAN_TRIP',options={}){const s=completedDay21ForDay22(route,options);return {day:22,money:120000,economyLedger:route==='BUSAN_TRIP'?[{day:21,category:'travel',label:'fixture',amount:-60000}]:[],storyHistory:[],pendingStoryId:'m30-day22-current-recovery-day',...s};}
const choose=(state,index=0)=>applyDay22V4GameChoice(state,getDay22V4Options(state.storyFlags.day22V4)[index].id);
const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};};
function finish(state){let guard=0;while(state.storyFlags.day22V4.phase!=='ending'){assert.ok(guard++<30);const segment=getDay22V4GameSegment(state),cue=segment.find(step=>['photoConsentCue','contactConsentCue'].includes(step.type));if(cue)applyDay22V4GameResolution(state,getDay22V4RuntimeResolution(state,cue));else choose(state);}return getDay22V4GameSegment(state);}

test('bridge preserves legacy entry and prepares only validated V4',()=>{const fresh=state();assert.equal(getDay22V4GameCompatibility(fresh).mode,'V4_NEW');assert.equal(prepareDay22V4GameEntry(fresh).mode,'V4');assert.equal(getDay22V4GameSegment(fresh).at(-1).choiceNumber,1);const legacy={storyFlags:{day21RuntimeComplete:true,day22RuntimeStage:1}};assert.equal(getDay22V4GameCompatibility(legacy).mode,'LEGACY');assert.equal(legacy.storyFlags.day22V4,undefined);});

test('Busan bridge stitches every module, resolves consent, and never charges travel twice',()=>{const s=state();prepareDay22V4GameEntry(s);const before={money:s.money,ledger:s.economyLedger.length};let guard=0;while(s.storyFlags.day22V4.phase!=='ending'){assert.ok(guard++<30);let packet;const steps=getDay22V4GameSegment(s),cue=steps.find(step=>['photoConsentCue','contactConsentCue'].includes(step.type));if(cue)packet=applyDay22V4GameResolution(s,getDay22V4RuntimeResolution(s,cue));else packet=choose(s);assert.equal(packet.steps.some(step=>/Boundary$/.test(step.type)),false);assert.ok(packet.steps.some(step=>step.type==='choice'||step.type==='photoConsentCue'||step.type==='contactConsentCue'||step.type==='chapterCompletionCue'));for(const transition of packet.steps.filter(step=>step.type==='transition')){assert.ok(transition.backgroundUrl);assert.ok(transition.storyClock);}}const final=getDay22V4GameSegment(s);assert.ok(final.some(step=>step.type==='transition'&&step.sceneNumber===24));assert.equal(final.at(-1).type,'chapterCompletionCue');assert.deepEqual({money:s.money,ledger:s.economyLedger.length},before);assert.doesNotThrow(()=>getDay22V4GameResumePresentation(s));});

test('Seoul and no-travel bridges keep lodging, Busan, contact, and character presentation out',()=>{for(const route of ['SEOUL_DAY','NO_TRAVEL']){const s=state(route);prepareDay22V4GameEntry(s);const all=[];let guard=0;while(s.storyFlags.day22V4.phase!=='ending'){assert.ok(guard++<30);const segment=getDay22V4GameSegment(s);all.push(...segment);const cue=segment.find(step=>step.type==='photoConsentCue');if(cue)applyDay22V4GameResolution(s,getDay22V4RuntimeResolution(s,cue));else choose(s);}all.push(...getDay22V4GameSegment(s));const rendered=all.map(step=>`${step.backgroundId??''} ${step.text??''}`).join('\n');if(route==='SEOUL_DAY'){assert.doesNotMatch(rendered,/day22-busan-lodging|부산의 밤이라면|실제 예약한 곳/);assert.match(rendered,/서울의 내 집에 돌아와 있었다/);}else{assert.equal(all.some(step=>step.type==='transition'&&step.characterId),false);assert.doesNotMatch(rendered,/day22-busan|부산의 밤이라면|서울의 밤이라면|함께 여행한 하은/);}assert.equal(s.economyLedger.length,0);assert.equal(s.storyFlags.day22V4.facts.todayContact,route==='SEOUL_DAY'?'NONE':null);}});

test('resolution failures roll the chapter back atomically',()=>{const s=state();prepareDay22V4GameEntry(s);while(s.storyFlags.day22V4.phase!=='contact_resolution'){if(s.storyFlags.day22V4.phase==='photo_resolution')applyDay22V4GameResolution(s,{type:'haeunPhotoResponse',keepAccepted:true});else{const options=getDay22V4Options(s.storyFlags.day22V4),index=s.storyFlags.day22V4.phase==='contact'?0:0;applyDay22V4GameChoice(s,options[index].id);}}const before=structuredClone(s.storyFlags.day22V4);assert.throws(()=>applyDay22V4GameResolution(s,{type:'haeunContactResponse',contact:'HAND',accepted:true}),/MISMATCH/);assert.deepEqual(s.storyFlags.day22V4,before);});

test('completion records immutable route history once and opens DAY23 once',()=>{const s=state('NO_TRAVEL');prepareDay22V4GameEntry(s);const final=finish(s),cue=final.at(-1);completeDay22V4GameChapter(s,cue);completeDay22V4GameChapter(s,cue);assert.equal(s.storyFlags.day22V4.complete,true);assert.equal(s.storyFlags.day21V4Day22HookPending,false);assert.equal(s.storyFlags.day22V4Day23HookPending,true);assert.equal(s.storyHistory.length,1);assert.equal(s.storyHistory[0].scenarioId,'day22-notion-v4');assert.equal(s.storyHistory[0].route,'NO_TRAVEL');assert.equal(s.storyFlags.day22RuntimeComplete,true);assert.equal(s.pendingStoryId,null);});

test('SaveManager round-trip preserves a mid-DAY22 checkpoint and resume presentation',()=>{const s=state('SEOUL_DAY');prepareDay22V4GameEntry(s);for(let index=0;index<6;index++)choose(s);const expected=getDay22V4GameSegment(s),store=storage(),shell=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});Object.assign(shell,s);SaveManager.save(shell,store);const loaded=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.deepEqual(loaded.storyFlags.day22V4,s.storyFlags.day22V4);assert.deepEqual(getDay22V4GameSegment(loaded),expected);assert.deepEqual(getDay22V4GameResumePresentation(loaded),getDay22V4GameResumePresentation(s));});

test('runtime consent responses are separate and route constrained',()=>{const shared=state();prepareDay22V4GameEntry(shared);shared.storyFlags.day22V4.input.relationshipTone='CALM';assert.deepEqual(getDay22V4RuntimeResolution(shared,{type:'photoConsentCue'}),{type:'haeunPhotoResponse',keepAccepted:true});assert.deepEqual(getDay22V4RuntimeResolution(shared,{type:'contactConsentCue',contact:'HUG'}),{type:'haeunContactResponse',contact:'HUG',accepted:true});const separate=state('BUSAN_TRIP',{shared:false});prepareDay22V4GameEntry(separate);assert.equal(getDay22V4RuntimeResolution(separate,{type:'contactConsentCue',contact:'HAND'}).accepted,false);});

test('main runtime connects DAY22 V4 entry, choice, consent, completion, clock, and legacy-only Free Action',()=>{const source=readFileSync(new URL('../game.js',import.meta.url),'utf8'),bridge=readFileSync(new URL('../src/day22-v4-game-bridge.mjs',import.meta.url),'utf8');assert.match(source,/day22-v4-game-bridge\.mjs\?v=6/);assert.match(source,/asset-manifest\.mjs\?v=24/);assert.match(bridge,/asset-manifest\.mjs\?v=24/);for(const module of ['opening','meal-photo','cafe','no-travel','ending'])assert.match(bridge,new RegExp(`day22-v4-playable-${module}\\.mjs\\?v=2`));assert.match(bridge,/day22-v4-playable-evening\.mjs\?v=3/);assert.match(source,/day22-v4-runtime-resolution\.mjs\?v=1/);assert.match(source,/if\(day22V4\)prepareDay22V4GameEntry/);assert.match(source,/applyDay22V4GameChoice\(currentState,id\)/);assert.match(source,/getDay22V4RuntimeResolution\(state,step\)/);assert.match(source,/applyDay22V4GameResolution\(state,response\)/);assert.match(source,/step\.day===22\?completeDay22V4GameChapter/);assert.match(source,/completionCue\.day===22\)completeDay22V4GameChapter/);assert.match(source,/photoConsentCue/);assert.match(source,/!state\.storyFlags\?\.day22V4&&state\.storyFlags\?\.day22RuntimeComplete/);assert.match(source,/state\.storyFlags\?\.day22V4\?LOCKED_DAY22_SCENE_ID/);assert.match(source,/lockedDay22&&!day22V4\?22/);});
