import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,completeDay19V4,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {getDay20V4Options} from '../src/day20-v4-state-contract.mjs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {applyDay20V4GameChoice,applyDay20V4GameResolution,completeDay20V4GameChapter,getDay20V4GameCompatibility,getDay20V4GameResumePresentation,getDay20V4GameSegment,prepareDay20V4GameEntry} from '../src/day20-v4-game-bridge.mjs';

function state(shared=true){const p=shared?'HAEUN':'SOLO',s={day:20,money:42000,breakup:null,ended:false,storyHistory:[],pendingStoryId:'m30-day20-current-shared-meal',storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:p,day17V4Choice9:shared?'day17_v4_life_haeun':'day17_v4_life_solo',day17V4DinnerAgreement:{day:18,partner:p,status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,shared?{}:{haeunContactAllowed:false});for(const k of shared?['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near']:['morning_solo','menu_familiar','solo_food','return_home','alone_stop','travel_life'])applyDay18V4Choice(s,`day18_v4_${k}`);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);while(s.storyFlags.day19V4.phase!=='ending'){const opts=getDay19V4Options(s.storyFlags.day19V4),i=shared&&s.storyFlags.day19V4.phase==='dinner'?2:shared&&s.storyFlags.day19V4.phase==='tomorrow_table'?0:0;applyDay19V4Choice(s,opts[i].id);}completeDay19V4(s,{type:'chapterCompletionCue',day:19,finalSceneReached:true});return s;}
const choose=(s,index=0)=>applyDay20V4GameChoice(s,getDay20V4Options(s.storyFlags.day20V4)[index].id);
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}};

test('bridge starts V4 and preserves legacy DAY20 saves',()=>{const s=state();assert.equal(getDay20V4GameCompatibility(s).mode,'V4_NEW');assert.equal(prepareDay20V4GameEntry(s).mode,'V4');assert.equal(getDay20V4GameSegment(s).at(-1).choiceNumber,1);const legacy=state();legacy.storyFlags.day20RuntimeStage=1;assert.equal(prepareDay20V4GameEntry(legacy).mode,'LEGACY');assert.equal(legacy.storyFlags.day20V4,undefined);});

test('bridge stitches every face-to-face section and strips boundaries',()=>{const s=state();prepareDay20V4GameEntry(s);let guard=0;while(s.storyFlags.day20V4.phase!=='ending'){assert.ok(guard++<20);const phase=s.storyFlags.day20V4.phase;let packet;if(phase==='contact_resolution')packet=applyDay20V4GameResolution(s,{type:'haeunContactResponse',contact:'HUG',accepted:true});else if(phase==='stay_resolution')packet=applyDay20V4GameResolution(s,{type:'haeunStayResponse',accepted:true,prepared:true,sleepingPlan:'SEPARATE_BEDDING'});else{const options=getDay20V4Options(s.storyFlags.day20V4),index=phase==='closeness'?0:phase==='night_end'?2:0;packet=choose(s,index);}assert.equal(packet.steps.some(step=>/Boundary$/.test(step.type)),false);assert.ok(packet.steps.some(step=>step.type==='choice'||step.type==='haeunContactResolution'||step.type==='haeunStayResolution'||step.type==='chapterCompletionCue'));}const final=getDay20V4GameSegment(s);assert.ok(final.some(step=>step.type==='transition'&&step.sceneNumber===24));assert.equal(final.at(-1).type,'chapterCompletionCue');assert.equal(s.storyFlags.day20V4.facts.firstHug,true);assert.equal(s.storyFlags.day20V4.facts.stayedOver,true);assert.doesNotThrow(()=>getDay20V4GameResumePresentation(s));});

test('solo bridge never exposes Haeun presentation or resolution steps',()=>{const s=state(false);prepareDay20V4GameEntry(s);let guard=0;while(s.storyFlags.day20V4.phase!=='ending'){assert.ok(guard++<6);const packet=choose(s);assert.equal(packet.steps.some(step=>step.type==='haeunContactResolution'||step.type==='haeunStayResolution'),false);for(const step of packet.steps.filter(step=>step.type==='transition'))assert.equal(step.characterId,null);}const final=getDay20V4GameSegment(s);assert.equal(final.some(step=>step.speaker==='하은'||step.sender==='하은'),false);assert.equal(final.at(-1).type,'chapterCompletionCue');});

test('failed resolution rolls chapter back atomically',()=>{const s=state();prepareDay20V4GameEntry(s);while(s.storyFlags.day20V4.phase!=='closeness')choose(s);choose(s,0);const before=structuredClone(s.storyFlags.day20V4);assert.throws(()=>applyDay20V4GameResolution(s,{type:'haeunContactResponse',contact:'HAND',accepted:true}),/MISMATCH/);assert.deepEqual(s.storyFlags.day20V4,before);});

test('completion records exact V4 history once and save manager round-trips',()=>{const s=state(false);prepareDay20V4GameEntry(s);choose(s);choose(s);const store=storage(),shell=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});Object.assign(shell,s);SaveManager.save(shell,store);const loaded=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.deepEqual(loaded.storyFlags.day20V4,s.storyFlags.day20V4);assert.deepEqual(getDay20V4GameSegment(loaded),getDay20V4GameSegment(s));while(s.storyFlags.day20V4.phase!=='ending')choose(s);completeDay20V4GameChapter(s,{type:'chapterCompletionCue',day:20,finalSceneReached:true});assert.equal(s.storyFlags.day20V4.complete,true);assert.equal(s.storyFlags.day19V4Day20HookPending,false);assert.equal(s.storyFlags.day20V4Day21HookPending,true);assert.equal(s.storyHistory.filter(record=>record.sceneId==='m30-day20-current-shared-meal').length,1);assert.equal(s.storyHistory.at(-1).scenarioId,'day20-notion-v4');assert.equal(s.storyFlags.day20RuntimeComplete,true);});
