import assert from 'node:assert/strict';
import test from 'node:test';
import {day25ContinuedFixture} from './day25-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,getDay26V4Options,resolveDay26V4Attendance} from '../src/day26-v4-state-contract.mjs';
import {getDay26V4PlayableGroup} from '../src/day26-v4-playable-group.mjs';
import {validateDay26V4SourceStep} from '../src/day26-v4-source-selection.mjs';

const choose25=(state,suffix)=>{const option=getDay25V4Options(state.storyFlags.day25V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option);applyDay25V4Choice(state,option.id);};
const choose26=(state,suffix)=>{const option=getDay26V4Options(state.storyFlags.day26V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day26V4.phase}:${suffix}`);applyDay26V4Choice(state,option.id);};
function groupState({energy=70,stress=20}={}){const state=day25ContinuedFixture();state.energy=energy;state.stress=stress;beginDay25V4(state);let guard=0;while(state.storyFlags.day25V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}choose25(state,phase==='friend_meal'?'meet':undefined);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});beginDay26V4(state);return state;}
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay26V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}

test('SCENE01-14 group meal emits only exact-backed narrative and every C1-C12 choice',()=>{const state=groupState(),seen=[];let guard=0;while(state.storyFlags.day26V4.phase!=='haeun_night'){assert.ok(guard++<30);const chapter=state.storyFlags.day26V4;const steps=getDay26V4PlayableGroup(chapter);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered,chapter.phase);seen.push(offered.choiceNumber);const suffix=chapter.phase==='group_opening'?'shared_story':chapter.phase==='group_celebration'?'starting':undefined;choose26(state,suffix);}const end=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(end);assert.deepEqual(seen,[1,2,3,4,5,6,7,8,9,10,11,12]);assert.equal(end.at(-1).nextScene,22);});

test('fast public claim and interruption stay visible until an actual friend correction',()=>{const state=groupState();choose26(state);choose26(state);choose26(state,'shared_story');choose26(state,'fast');let steps=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(steps);assert.match(JSON.stringify(steps),/빨리 한다는 이야기는 아직 안 했는데/);choose26(state,'explain');steps=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(steps);assert.match(JSON.stringify(steps),/내가 조금 더 말할게/);while(state.storyFlags.day26V4.phase!=='group_private')choose26(state);choose26(state,'admit');assert.equal(state.storyFlags.day26V4.facts.overstatementAcknowledged,true);assert.equal(state.storyFlags.day26V4.facts.overstatementCorrected,false);steps=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(steps);assert.match(JSON.stringify(steps),/내가 구경하는 사람 같았어/);choose26(state,'name_override');assert.equal(state.storyFlags.day26V4.facts.overstatementCorrectionPromised,true);assert.equal(state.storyFlags.day26V4.facts.overstatementCorrected,false);choose26(state,'correct');assert.equal(state.storyFlags.day26V4.facts.overstatementCorrected,true);});

test('rest request waits for attendance response and never renders the absent group table',()=>{const state=groupState();choose26(state,'rest');let steps=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).type,'attendanceChangeCue');assert.doesNotMatch(JSON.stringify(steps),/우리 어떤 이야기까지 할까/);resolveDay26V4Attendance(state,{type:'attendanceChangeResponse',accepted:true});steps=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).nextScene,21);});

test('low-energy stay records hidden fatigue while lean does not',()=>{for(const [suffix,hidden] of [['stay',true],['lean',false]]){const state=groupState({energy:20});while(state.storyFlags.day26V4.phase!=='group_body')choose26(state,state.storyFlags.day26V4.phase==='group_opening'?'no_announcement':undefined);choose26(state,suffix);assert.equal(state.storyFlags.day26V4.facts.fatigueHidden,hidden);const steps=getDay26V4PlayableGroup(state.storyFlags.day26V4);sourced(steps);assert.match(JSON.stringify(steps),suffix==='stay'?/피로가 쌓였다/:/자세를 바꾸어/);}});
