import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {applyDay29V4Choice,beginDay29V4,completeDay29V4,getDay29V4Entry,getDay29V4Options,resolveDay29V4Contact,resolveDay29V4Evening,resolveDay29V4Future,resolveDay29V4New,resolveDay29V4Stay,validateDay29V4} from '../src/day29-v4-state-contract.mjs';

const choose28=(state,suffix)=>{const options=getDay28V4Options(state.storyFlags.day28V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`DAY28 ${state.storyFlags.day28V4.phase}:${suffix}`);applyDay28V4Choice(state,option.id);};
function finish28(state,kind){while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});continue;}if(phase==='new_relationship_resolution'){resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});continue;}const suffix=phase==='continuing_distance'?'talk_only':phase==='new_meeting_wish'?'want_romance':null;choose28(state,suffix);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});return state;}
const friendly=()=>finish28(day28FriendlyFixture(),'friendly');
const solo=()=>finish28(day28SoloFixture(),'solo');
const mixed=()=>finish28(day28NewMeetingFixture(),'mixed');
const choose29=(state,suffix)=>{const options=getDay29V4Options(state.storyFlags.day29V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`DAY29 ${state.storyFlags.day29V4.phase}:${suffix}`);applyDay29V4Choice(state,option.id);};

test('DAY29 entry seals only completed DAY26-28 V4 history and preserves legacy saves',()=>{const state=friendly(),entry=getDay29V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.eveningCandidate,'HAEUN');assert.equal(entry.input.relationshipState,'CONTINUE');assert.equal(entry.input.source.day28Schema,'day28-notion-v4/1');assert.equal(entry.input.currentContact,null);const legacy=structuredClone(state);legacy.storyFlags.day29RuntimeStage=1;assert.equal(getDay29V4Entry(legacy).mode,'LEGACY');const broken=structuredClone(state);broken.storyFlags.day28V4.facts.day29Handoff.contactAllowed=false;assert.equal(getDay29V4Entry(broken).mode,'BLOCKED_PREREQUISITE');});

test('friendly route keeps meeting, future, contact and lodging as independent current responses',()=>{const state=friendly();beginDay29V4(state);while(state.storyFlags.day29V4.phase!=='evening_resolution')choose29(state);resolveDay29V4Evening(state,{type:'day29EveningResponse',target:'HAEUN',accepted:true,location:'HAEUN_HOME'});while(state.storyFlags.day29V4.phase!=='future_resolution')choose29(state);resolveDay29V4Future(state,{type:'day29FutureResponse',outcome:'CONTINUE',contactAllowed:true});while(state.storyFlags.day29V4.phase!=='contact_resolution')choose29(state);assert.equal(state.storyFlags.day29V4.facts.currentContact,null);resolveDay29V4Contact(state,{type:'day29ContactResponse',contact:'KISS',accepted:true});choose29(state,'stay');assert.equal(state.storyFlags.day29V4.phase,'stay_resolution');resolveDay29V4Stay(state,{type:'day29StayResponse',accepted:false});while(state.storyFlags.day29V4.phase!=='ending')choose29(state);assert.equal(state.storyFlags.day29V4.facts.day30Handoff.currentContact,'KISS');assert.equal(state.storyFlags.day29V4.facts.day30Handoff.stayed,false);assert.equal(validateDay29V4(state.storyFlags.day29V4),true);completeDay29V4(state,{type:'chapterCompletionCue',day:29,finalSceneReached:true});assert.equal(state.storyFlags.day29V4Day30HookPending,true);});

test('solo route cannot invent a person response and filters unowned photo and outfit claims',()=>{const state=solo();state.storyFlags.day7V3PhotoReceived=false;state.storyFlags.day13V3PortraitExists=false;state.storyFlags.day14V4FlowerPhotoTaken=false;state.storyFlags.day14V4RoomPhotoTaken=false;state.storyFlags.day26V4.input.ownedPinkOutfit=false;const entry=getDay29V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.eveningCandidate,null);beginDay29V4(state);choose29(state);assert.equal(getDay29V4Options(state.storyFlags.day29V4).some(option=>option.id.endsWith('_liked')),false);choose29(state);assert.deepEqual(getDay29V4Options(state.storyFlags.day29V4).map(option=>option.id.split('_').at(-1)),['close']);while(state.storyFlags.day29V4.phase!=='ending')choose29(state);assert.equal(state.storyFlags.day29V4.facts.eveningTarget,null);assert.equal(state.storyFlags.day29V4.facts.day30Handoff.eveningTarget,null);});

test('actual new relationship uses only its sealed person and still waits for a current answer',()=>{const state=mixed(),entry=getDay29V4Entry(state);assert.equal(entry.input.eveningCandidate,'ARA');beginDay29V4(state);while(state.storyFlags.day29V4.phase!=='evening_resolution')choose29(state);assert.throws(()=>resolveDay29V4Evening(state,{type:'day29EveningResponse',target:'YURI',accepted:true,location:'OUTSIDE'}),/INVALID_EVENING/);resolveDay29V4Evening(state,{type:'day29EveningResponse',target:'ARA',accepted:true,location:'OUTSIDE'});choose29(state,'meet_again');assert.equal(state.storyFlags.day29V4.facts.newResponse,null);resolveDay29V4New(state,{type:'day29NewResponse',target:'ARA',outcome:'NEED_TIME'});while(state.storyFlags.day29V4.phase!=='ending')choose29(state);assert.equal(state.storyFlags.day29V4.facts.day30Handoff.newResponse,'NEED_TIME');const forged=structuredClone(state.storyFlags.day29V4);forged.input.currentMoney+=1;assert.equal(validateDay29V4(forged),false);});
