import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,completeDay19V4,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {applyDay20V4Choice,beginDay20V4,getDay20V4Options} from '../src/day20-v4-state-contract.mjs';
import {getDay20V4PlayableDomestic} from '../src/day20-v4-playable-domestic.mjs';
import {validateDay20V4SourceStep} from '../src/day20-v4-source-selection.mjs';

function state(){const s={breakup:null,ended:false,money:42000,storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:'HAEUN',day17V4Choice9:'day17_v4_life_haeun',day17V4DinnerAgreement:{day:18,partner:'HAEUN',status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,{});for(const key of['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near'])applyDay18V4Choice(s,`day18_v4_${key}`);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);while(s.storyFlags.day19V4.phase!=='ending'){const opts=getDay19V4Options(s.storyFlags.day19V4),i=s.storyFlags.day19V4.phase==='dinner'?2:s.storyFlags.day19V4.phase==='tomorrow_table'?0:0;applyDay19V4Choice(s,opts[i].id);}completeDay19V4(s,{type:'chapterCompletionCue',day:19,finalSceneReached:true});beginDay20V4(s);for(let i=0;i<3;i++)applyDay20V4Choice(s,getDay20V4Options(s.storyFlags.day20V4)[0].id);return s;}
const choose=(s,index=0)=>applyDay20V4Choice(s,getDay20V4Options(s.storyFlags.day20V4)[index].id);
const assertSourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay20V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);};

test('domestic playable carries SCENE 05 through 11 with exact source steps',()=>{const s=state();let steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.equal(steps[0].number,5);assert.equal(steps.at(-1).choiceNumber,4);assertSourced(steps);choose(s,0);steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===6));assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===7));assert.ok(steps.some(step=>step.text==='너무 좋은 숙소 후기 같은데.'));assert.equal(steps.at(-1).choiceNumber,5);assertSourced(steps);choose(s,0);steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===8));assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===9));assert.equal(steps.at(-1).choiceNumber,6);assertSourced(steps);choose(s,0);steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.equal(steps.at(-1).choiceNumber,7);assertSourced(steps);choose(s,1);steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.equal(steps.at(-1).choiceNumber,8);assertSourced(steps);choose(s,2);steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.equal(steps.at(-1).type,'domesticBoundary');assert.equal(steps.at(-1).nextScene,12);assertSourced(steps);});

test('disclosure reaction goes to SCENE 19 and never appends domestic intimacy',()=>{const s=state();s.storyFlags.day20V4.input.day18DiscussionPending=true;choose(s);const options=getDay20V4Options(s.storyFlags.day20V4);assert.equal(options.length,3);applyDay20V4Choice(s,options[2].id);const steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.equal(s.storyFlags.day20V4.phase,'conflict');assert.equal(steps.at(-1).nextScene,19);assert.equal(steps.some(step=>step.type==='sceneDirection'&&step.number>=8&&step.number<=18),false);assert.ok(steps.some(step=>step.text==='그래도 숨기고 편해지고 싶지는 않아.'));assertSourced(steps);});

test('packaging joke is replaced when the actual DAY19 travel conversation is absent',()=>{const s=state();s.storyFlags.day20V4.input.sharedTravelConversationExperienced=false;choose(s);const steps=getDay20V4PlayableDomestic(s.storyFlags.day20V4);assert.equal(steps.some(step=>step.text==='너무 좋은 숙소 후기 같은데.'),false);assert.ok(steps.some(step=>step.text==='먹기 전에 감상 끝내자.'));assertSourced(steps);});
