import assert from 'node:assert/strict';
import test from 'node:test';
import {day27EndedFixture,day27FriendlyFixture} from './day27-v4-playable-fixture.mjs';
import {applyDay27V4Choice,completeDay27V4,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4Jihoon,resolveDay27V4NextTalk,resolveDay27V4Relationship} from '../src/day27-v4-state-contract.mjs';
import {beginDay28V4,getDay28V4Entry,validateDay28V4} from '../src/day28-v4-state-contract.mjs';

const choose=(state,suffix)=>{const options=getDay27V4Options(state.storyFlags.day27V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day27V4.phase}:${suffix}`);applyDay27V4Choice(state,option.id);};
function finishFriendly(){const state=day27FriendlyFixture();choose(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});choose(state);while(state.storyFlags.day27V4.phase!=='conversation_end')choose(state);choose(state,'want_again');resolveDay27V4Relationship(state,{type:'day27RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});resolveDay27V4Jihoon(state,{type:'day27JihoonResponse',available:false});choose(state);choose(state);choose(state,'short_meeting');resolveDay27V4NextTalk(state,{type:'day27NextTalkResponse',outcome:'ACCEPTED'});completeDay27V4(state,{type:'chapterCompletionCue',day:27,finalSceneReached:true});return state;}
function finishSolo(){const state=day27EndedFixture();choose(state);for(let index=0;index<6;index++)choose(state);completeDay27V4(state,{type:'chapterCompletionCue',day:27,finalSceneReached:true});return state;}

test('DAY28 entry seals only verified DAY25-27 facts and preserves legacy saves',()=>{const state=finishFriendly(),entry=getDay28V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.relationshipContinues,true);assert.equal(entry.input.haeunMeetingEligible,true);assert.equal(entry.input.actualConversation.target,'HAEUN');assert.equal(entry.input.nextTalk.response,'ACCEPTED');assert.equal(entry.input.source.day27Schema,'day27-notion-v4/1');assert.deepEqual(entry.input.entrustedBelongings,[]);assert.equal(entry.input.priorHomeInvitation,false);const legacy=structuredClone(state);legacy.storyFlags.day28RuntimeStage=1;assert.equal(getDay28V4Entry(legacy).mode,'LEGACY');const broken=structuredClone(state);broken.storyFlags.day27V4.facts.day28Handoff.contactAllowed=false;assert.equal(getDay28V4Entry(broken).mode,'BLOCKED_PREREQUISITE');});

test('a prior kiss and reunion language never replace current DAY28 consent',()=>{const state=finishFriendly();beginDay28V4(state);const chapter=state.storyFlags.day28V4;assert.equal(chapter.input.priorKissOccurred,true);assert.equal(chapter.input.priorContact,'KISS');assert.equal(chapter.facts.currentContact,null);assert.equal(chapter.facts.homeInvitationResponse,null);assert.equal(chapter.facts.relationshipResponse,null);assert.equal(validateDay28V4(chapter),true);const forged=structuredClone(chapter);forged.facts.currentContact='KISS';assert.equal(validateDay28V4(forged),false);});

test('no accepted conversation or next talk stays solo without invented person response',()=>{const state=finishSolo(),entry=getDay28V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.relationshipContinues,false);assert.equal(entry.input.haeunMeetingEligible,false);assert.equal(entry.input.newMeetingEligible,false);assert.equal(entry.input.actualConversation,null);beginDay28V4(state);assert.equal(state.storyFlags.day28V4.facts.route,null);const forged=structuredClone(state.storyFlags.day28V4);forged.input.currentMoney+=1;assert.equal(validateDay28V4(forged),false);});
