import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {applyDay29V4Choice,beginDay29V4,getDay29V4Options,resolveDay29V4Contact,resolveDay29V4Evening,resolveDay29V4Future,resolveDay29V4Stay,validateDay29V4} from '../src/day29-v4-state-contract.mjs';
import {getDay29V4PlayableOpening} from '../src/day29-v4-playable-opening.mjs';
import {getDay29V4PlayableHaeunEvening} from '../src/day29-v4-playable-haeun-evening.mjs';
import {getDay29V4RuntimeResolution} from '../src/day29-v4-runtime-resolution.mjs';
import {validateDay29V4SourceStep} from '../src/day29-v4-source-selection.mjs';

const choose=(state,getOptions,apply,suffix)=>{const options=getOptions(state.storyFlags[apply===applyDay28V4Choice?'day28V4':'day29V4']),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${suffix}:${options.map(item=>item.id).join(',')}`);apply(state,option.id);};
const choose28=(state,suffix)=>choose(state,getDay28V4Options,applyDay28V4Choice,suffix);
const choose29=(state,suffix)=>choose(state,getDay29V4Options,applyDay29V4Choice,suffix);
function sourced(steps){for(const step of steps)if(['dialogue','monologue','playerNarration','storyActionCue'].includes(step.type))assert.equal(validateDay29V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);}

function fixture({home=false,relationship='CONTINUE',resolveEvening=true}={}){const state=day28FriendlyFixture();while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:relationship,contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:home,location:home?'HAEUN_HOME':'OUTSIDE'});continue;}const suffix=phase==='continuing_distance'?'talk_only':phase==='continuing_night'&&home?'together_if_mutual':null;choose28(state,suffix);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});beginDay29V4(state);while(state.storyFlags.day29V4.phase!=='evening_resolution')choose29(state);if(resolveEvening){const cue=getDay29V4PlayableOpening(state.storyFlags.day29V4).at(-1),response=getDay29V4RuntimeResolution(state,cue);resolveDay29V4Evening(state,response);}return state;}

test('SCENE10-17 home evening preserves source order and independent consent',()=>{const state=fixture({home:true}),seen=[];while(!['truth','tomorrow'].includes(state.storyFlags.day29V4.phase)){const chapter=state.storyFlags.day29V4,steps=getDay29V4PlayableHaeunEvening(chapter);sourced(steps);const scene=steps.find(step=>step.type==='sceneDirection');if(scene)seen.push(scene.number);const cue=steps.find(step=>step.type?.endsWith('Cue'));if(cue){const response=getDay29V4RuntimeResolution(state,cue);if(cue.type==='day29ContactCue')assert.equal(chapter.facts.currentContact,null);if(cue.type==='day29StayCue')assert.equal(chapter.facts.stayResponse,null);if(cue.type==='day29FutureCue')resolveDay29V4Future(state,response);else if(cue.type==='day29ContactCue')resolveDay29V4Contact(state,response);else resolveDay29V4Stay(state,response);continue;}const choiceStep=steps.find(step=>step.type==='choice');assert.ok(choiceStep,chapter.phase);choose29(state,chapter.phase==='haeun_close'?'stay':null);}assert.deepEqual(seen,[10,11,12,13,14,15,16,17]);assert.equal(state.storyFlags.day29V4.facts.currentContact,'KISS');assert.equal(state.storyFlags.day29V4.facts.stayResponse,true);assert.equal(validateDay29V4(state.storyFlags.day29V4),true);const close=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(close);assert.equal(close.at(-1).nextScene,21);assert.match(JSON.stringify(close),/이후에 무슨 일이 더 있었다는 설명은 붙지 않았다/);});

test('outside evening never shows home changing or lodging choices',()=>{const state=fixture({home:false});assert.equal(state.storyFlags.day29V4.facts.eveningLocation,'OUTSIDE');while(state.storyFlags.day29V4.phase!=='haeun_comfort'){const steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);const cue=steps.find(step=>step.type==='day29FutureCue');if(cue){resolveDay29V4Future(state,getDay29V4RuntimeResolution(state,cue));continue;}choose29(state);}const comfort=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(comfort);assert.doesNotMatch(JSON.stringify(comfort),/나 옷 좀 갈아입고 올게|사라진 방 안/);assert.match(JSON.stringify(comfort),/바깥에서는 옷을 갈아입는 장면 없이/);while(state.storyFlags.day29V4.phase!=='haeun_close'){const steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4),cue=steps.find(step=>step.type==='day29ContactCue');if(cue){resolveDay29V4Contact(state,getDay29V4RuntimeResolution(state,cue));continue;}choose29(state);}const options=getDay29V4Options(state.storyFlags.day29V4);assert.equal(options.some(option=>option.id.endsWith('_stay')),false);const pending=fixture({home:false,resolveEvening:false});assert.throws(()=>resolveDay29V4Evening(pending,{type:'day29EveningResponse',target:'HAEUN',accepted:true,location:'HAEUN_HOME'}),/INVALID_EVENING/);});

test('alternate C10-17 choices remain source-backed without inflating contact',()=>{const state=fixture({home:false}),suffixes={haeun_success:'sit_here',haeun_meal:'enough',haeun_identity:'beside',haeun_future:'prepare',haeun_comfort:'ask_tired',haeun_music:'listen',haeun_intimacy:'talk',haeun_close:'little_longer'};while(!['truth','tomorrow'].includes(state.storyFlags.day29V4.phase)){const steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(steps);const cue=steps.find(step=>step.type==='day29FutureCue');if(cue){resolveDay29V4Future(state,getDay29V4RuntimeResolution(state,cue));continue;}choose29(state,suffixes[state.storyFlags.day29V4.phase]);}const end=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(end);assert.equal(state.storyFlags.day29V4.facts.currentContact,null);assert.equal(state.storyFlags.day29V4.facts.close,'LITTLE_LONGER');assert.equal(end.at(-1).nextScene,21);});

test('changed future waits for Haeun and stops the affectionate night',()=>{const state=fixture({home:true});while(state.storyFlags.day29V4.phase!=='haeun_future')choose29(state);choose29(state,'changed');let steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(steps);const cue=steps.at(-1);assert.equal(cue.type,'day29FutureCue');const response=getDay29V4RuntimeResolution(state,cue);assert.equal(response.outcome,'NEED_TIME');assert.throws(()=>resolveDay29V4Future(structuredClone(state),{type:'day29FutureResponse',outcome:'CONTINUE',contactAllowed:true}),/INVALID_FUTURE/);resolveDay29V4Future(state,response);assert.equal(state.storyFlags.day29V4.phase,'tomorrow');steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).nextScene,21);assert.doesNotMatch(JSON.stringify(steps),/SCENE 14|키스하고 싶어|오늘 여기 있어도/);assert.equal(state.storyFlags.day29V4.facts.currentContact,null);});

test('KNOW_AGAIN relationship skips SCENE16 intimacy even after a calm song',()=>{const state=fixture({home:false,relationship:'KNOW_AGAIN'});while(state.storyFlags.day29V4.phase!=='haeun_music'){const steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4),cue=steps.find(step=>step.type==='day29FutureCue');if(cue){resolveDay29V4Future(state,getDay29V4RuntimeResolution(state,cue));continue;}choose29(state);}choose29(state,'listen');assert.equal(state.storyFlags.day29V4.phase,'haeun_close');const steps=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.find(step=>step.type==='sceneDirection').number,17);assert.doesNotMatch(JSON.stringify(steps),/키스하고 싶어|오늘은 이렇게 안고/);});
