import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4NextMeeting,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {getDay29V4Options} from '../src/day29-v4-state-contract.mjs';
import {applyDay29V4GameChoice,applyDay29V4GameResolution,completeDay29V4GameChapter,getDay29V4GameCompatibility,getDay29V4GameResumePresentation,getDay29V4GameSegment,isDay29V4ResolutionStep,prepareDay29V4GameEntry} from '../src/day29-v4-game-bridge.mjs';
import {getDay29V4RuntimeResolution} from '../src/day29-v4-runtime-resolution.mjs';

const pick=(options,suffix)=>{const option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${suffix}:${options.map(item=>item.id).join(',')}`);return option.id;};
const choose28=(state,suffix)=>applyDay28V4Choice(state,pick(getDay28V4Options(state.storyFlags.day28V4),suffix));
function ready(state,{newRoute=false,friendly=false}={}){while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});continue;}if(phase==='next_meeting_resolution'){resolveDay28V4NextMeeting(state,{type:'day28NextMeetingResponse',outcome:'ACCEPTED'});continue;}if(phase==='new_relationship_resolution'){resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});continue;}const suffix=phase==='continuing_distance'?'talk_only':phase==='continuing_farewell'&&friendly?'next_when_possible':phase==='new_meeting_wish'&&newRoute?'want_romance':null;choose28(state,suffix);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});return state;}
const choose29=state=>applyDay29V4GameChoice(state,getDay29V4Options(state.storyFlags.day29V4)[0].id);
function finish(state){const all=[];let guard=0;while(state.storyFlags.day29V4.phase!=='ending'){assert.ok(guard++<80,state.storyFlags.day29V4.phase);const steps=getDay29V4GameSegment(state);all.push(...steps);const cue=steps.find(isDay29V4ResolutionStep);if(cue)all.push(...applyDay29V4GameResolution(state,getDay29V4RuntimeResolution(state,cue)).steps);else all.push(...choose29(state).steps);}all.push(...getDay29V4GameSegment(state));return all;}
const storage=()=>{const data=new Map();return {setItem:(key,value)=>data.set(key,value),getItem:key=>data.get(key)??null,removeItem:key=>data.delete(key)};};

test('bridge maps Friendly, Solo and Ara routes without crossing characters',()=>{const friendly=ready(day28FriendlyFixture(),{friendly:true});assert.equal(getDay29V4GameCompatibility(friendly).mode,'V4_NEW');prepareDay29V4GameEntry(friendly);const friendlySteps=finish(friendly),friendlyScenes=new Set(friendlySteps.filter(step=>step.type==='transition').map(step=>step.sceneNumber));for(const number of [1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,21,22,23,24])assert.ok(friendlyScenes.has(number),`friendly:${number}`);assert.equal(friendlyScenes.has(4),friendly.storyFlags.day29V4.input.haeunCardReceived);const solo=ready(day28SoloFixture());prepareDay29V4GameEntry(solo);const soloSteps=finish(solo),soloScenes=new Set(soloSteps.filter(step=>step.type==='transition').map(step=>step.sceneNumber));assert.ok(soloScenes.has(19));assert.equal(soloScenes.has(10),false);assert.equal(soloScenes.has(23),false);assert.equal(soloSteps.some(isDay29V4ResolutionStep),false);const newer=ready(day28NewMeetingFixture(),{newRoute:true});prepareDay29V4GameEntry(newer);const newSteps=finish(newer),newScenes=new Set(newSteps.filter(step=>step.type==='transition').map(step=>step.sceneNumber));assert.ok(newScenes.has(18));assert.ok(newScenes.has(23));assert.equal(newScenes.has(10),false);assert.doesNotMatch(JSON.stringify(newSteps),/유리|서진/);for(const step of [...friendlySteps,...soloSteps,...newSteps].filter(step=>step.type==='transition')){assert.ok(step.backgroundUrl);assert.ok(step.storyClock);}});

test('resolution failure restores replay state atomically',()=>{const state=ready(day28FriendlyFixture(),{friendly:true});prepareDay29V4GameEntry(state);while(state.storyFlags.day29V4.phase!=='evening_resolution')choose29(state);const before=structuredClone(state.storyFlags.day29V4);assert.throws(()=>applyDay29V4GameResolution(state,{type:'day29EveningResponse',target:'ARA',accepted:true,location:'OUTSIDE'}),/INVALID_EVENING/);assert.deepEqual(state.storyFlags.day29V4,before);});

test('mid-day save round-trip preserves segment and presentation',()=>{let state=ready(day28FriendlyFixture(),{friendly:true});prepareDay29V4GameEntry(state);for(let index=0;index<12;index++){const steps=getDay29V4GameSegment(state),cue=steps.find(isDay29V4ResolutionStep);if(cue)applyDay29V4GameResolution(state,getDay29V4RuntimeResolution(state,cue));else choose29(state);}const chapter=structuredClone(state.storyFlags.day29V4),expected=getDay29V4GameSegment(state),presentation=getDay29V4GameResumePresentation(state),store=storage(),shell=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});Object.assign(shell,state);SaveManager.save(shell,store);state=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.deepEqual(state.storyFlags.day29V4,chapter);assert.deepEqual(getDay29V4GameSegment(state),expected);assert.deepEqual(getDay29V4GameResumePresentation(state),presentation);});

test('completion records one DAY29 history and opens only DAY30 hook',()=>{const state=ready(day28FriendlyFixture(),{friendly:true});prepareDay29V4GameEntry(state);state.storyHistory=[];const cue=finish(state).at(-1);completeDay29V4GameChapter(state,cue);completeDay29V4GameChapter(state,cue);assert.equal(state.storyHistory.length,1);assert.equal(state.storyHistory[0].scenarioId,'day29-notion-v4');assert.equal(state.storyFlags.day29V4.complete,true);assert.equal(state.storyFlags.day29V4Day30HookPending,true);assert.equal(state.storyFlags.day28V4Day29HookPending,false);assert.equal(state.storyFlags.day29RuntimeComplete,true);assert.equal(state.storyFlags.day29FreeActionComplete,undefined);});

test('main game wires DAY29 V4 entry, choices, resolutions, completion and Story/Free exclusion',()=>{const source=readFileSync(new URL('../game.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(source,/day29-v4-game-bridge\.mjs\?v=1/);assert.match(source,/day29-v4-runtime-resolution\.mjs\?v=2/);assert.match(source,/if\(day29V4\)prepareDay29V4GameEntry\(state\)/);assert.match(source,/applyDay29V4GameChoice\(state,choiceId\)/);assert.match(source,/getDay29V4RuntimeResolution\(state,step\)/);assert.match(source,/applyDay29V4GameResolution\(state,response\)/);assert.match(source,/step\.day===29\?completeDay29V4GameChapter/);assert.match(source,/isDay29V4ResolutionStep\(step\)/);assert.match(source,/lockedDay29&&!day29V4\?29/);assert.match(source,/completedSession\?\.id===LOCKED_DAY29_SCENE_ID&&!state\.storyFlags\?\.day29V4/);assert.match(source,/!\(lockedDay29&&day29V4\)/);assert.ok(Number(html.match(/game\.js\?v=(\d+)/)?.[1])>=290);});
