import assert from 'node:assert/strict';
import test from 'node:test';
import {completedDay23ForDay24} from './day24-v4-fixture.mjs';
import {applyDay24V4Choice,beginDay24V4,completeDay24V4,getDay24V4Options,resolveDay24V4Contact,resolveDay24V4Conversation,resolveDay24V4Future,resolveDay24V4Relationship} from '../src/day24-v4-state-contract.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Entry,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location,resolveDay25V4NewMeeting,validateDay25V4} from '../src/day25-v4-state-contract.mjs';

const choose24=(state,suffix)=>{const options=getDay24V4Options(state.storyFlags.day24V4);const selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected);applyDay24V4Choice(state,selected.id);};
function finish24(state,{relationship='CONTINUE',future=true}={}){let guard=0;while(state.storyFlags.day24V4.phase!=='ending'){assert.ok(guard++<40);const phase=state.storyFlags.day24V4.phase;if(phase==='conversation_resolution'){resolveDay24V4Conversation(state,{type:'haeunConversationResponse',accepted:true,mode:'MEET'});continue;}if(phase==='relationship_resolution'){resolveDay24V4Relationship(state,{type:'haeunRelationshipResponse',outcome:relationship});continue;}if(phase==='contact_resolution'){resolveDay24V4Contact(state,{type:'otherContactResponse',outcome:'ACKNOWLEDGED'});continue;}if(phase==='future_resolution'){resolveDay24V4Future(state,{type:'haeunFutureTalkResponse',accepted:future,time:future?'tomorrow-dinner':null});continue;}choose24(state);}completeDay24V4(state,{type:'chapterCompletionCue',day:24,finalSceneReached:true});return state;}
function continuedState(){const state=completedDay23ForDay24('SEOUL_DAY',{jihoon:true});state.money=730000;state.economyLedger=[{day:22,amount:-30000},{day:24,amount:-12000},{day:24,amount:5000}];state.storyFlags.day11V3AttendedSoraMeeting=true;beginDay24V4(state);return finish24(state);}
function endedNewMeetingState(){const state=completedDay23ForDay24('SEOUL_DAY',{pendingContacts:['ARA']});beginDay24V4(state);choose24(state);choose24(state);resolveDay24V4Conversation(state,{type:'haeunConversationResponse',accepted:true,mode:'MEET'});choose24(state);choose24(state);choose24(state);choose24(state);resolveDay24V4Relationship(state,{type:'haeunRelationshipResponse',outcome:'END'});choose24(state,'rest');choose24(state,'relationship_ended');choose24(state,'personal_interest');resolveDay24V4Contact(state,{type:'otherContactResponse',outcome:'ACCEPT_MEETING'});while(state.storyFlags.day24V4.phase!=='ending')choose24(state);completeDay24V4(state,{type:'chapterCompletionCue',day:24,finalSceneReached:true});return state;}
const choose25=(state,suffix)=>{const options=getDay25V4Options(state.storyFlags.day25V4);const selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`${state.storyFlags.day25V4.phase}:${suffix}`);return applyDay25V4Choice(state,selected.id);};

test('DAY25 entry freezes only verified DAY22-24 facts and preserves legacy saves',()=>{const state=continuedState();const entry=getDay25V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.route,'HAEUN_FUTURE');assert.equal(entry.input.currentMoney,730000);assert.equal(entry.input.recentExpense,42000);assert.equal(entry.input.trustEligible,true);assert.equal(entry.input.soraKnown,true);const legacy=structuredClone(state);legacy.storyFlags.day25RuntimeStage=1;assert.equal(getDay25V4Entry(legacy).mode,'LEGACY');const broken=structuredClone(state);broken.storyFlags.day24V4.facts.day25Route='RELATIONSHIP_ENDED';assert.equal(getDay25V4Entry(broken).mode,'BLOCKED_PREREQUISITE');});

test('special and home meal choices wait for Haeun and never auto-reserve',()=>{for(const [suffix,fit,expected] of [['special',true,'SPECIAL'],['home',false,'HOME']]){const state=continuedState();beginDay25V4(state);choose25(state,suffix);assert.equal(state.storyFlags.day25V4.phase,'location_resolution');assert.equal(state.storyFlags.day25V4.facts.reservationMade,false);resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:fit});assert.equal(state.storyFlags.day25V4.facts.mealLocation,expected);assert.equal(state.storyFlags.day25V4.facts.reservationMade,false);}const rejected=continuedState();beginDay25V4(rejected);choose25(rejected,'home');resolveDay25V4Location(rejected,{type:'haeunMealLocationResponse',accepted:false});assert.equal(rejected.storyFlags.day25V4.facts.mealLocation,'COMFORTABLE');});

test('mutual future path keeps proposal, Haeun response, kiss consent and friend availability separate',()=>{const state=continuedState();beginDay25V4(state);choose25(state);choose25(state);choose25(state);for(let i=0;i<6;i++)choose25(state);choose25(state,'prepare');assert.equal(state.storyFlags.day25V4.phase,'future_resolution');resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});choose25(state,'more_time');choose25(state,'kiss');assert.equal(state.storyFlags.day25V4.facts.kissOccurred,false);resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:'KISS',accepted:true});assert.equal(state.storyFlags.day25V4.facts.kissOccurred,true);choose25(state);choose25(state);choose25(state,'meet');assert.equal(state.storyFlags.day25V4.facts.friendMealScheduled,false);resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});assert.equal(state.storyFlags.day25V4.facts.friendMealScheduled,true);choose25(state);assert.equal(state.storyFlags.day25V4.phase,'ending');assert.equal(validateDay25V4(state.storyFlags.day25V4),true);completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});assert.equal(state.storyFlags.day25V4Day26HookPending,true);assert.equal(state.storyFlags.day24V4Day25HookPending,false);});

test('ended relationship uses solo and actual accepted new-person route without inventing romance',()=>{const state=endedNewMeetingState();beginDay25V4(state);choose25(state);choose25(state);choose25(state);assert.equal(state.storyFlags.day25V4.phase,'solo_goal');choose25(state);choose25(state);choose25(state);assert.equal(state.storyFlags.day25V4.phase,'new_meeting');choose25(state);resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:'ARA',outcome:'RESCHEDULED'});choose25(state);assert.equal(state.storyFlags.day25V4.phase,'public_boundary');choose25(state);const chapter=state.storyFlags.day25V4;assert.equal(chapter.facts.newMeetingResponse,'RESCHEDULED');assert.equal(chapter.facts.relationshipContinues,null);assert.equal(chapter.facts.kissOccurred,false);assert.equal(chapter.facts.day26Route,'INDEPENDENT_LIFE');assert.equal(validateDay25V4(chapter),true);});

test('future and contact responses cannot be promoted from the player choice',()=>{const state=continuedState();beginDay25V4(state);choose25(state);choose25(state);choose25(state);for(let i=0;i<6;i++)choose25(state);choose25(state,'rediscuss');assert.throws(()=>resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'}),/PREPARATION_NOT_PROPOSED/);resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'REDISCUSS'});assert.equal(state.storyFlags.day25V4.facts.relationshipContinues,true);});

test('DAY25 replay validator rejects frozen history and resolution tampering',()=>{const state=continuedState();beginDay25V4(state);choose25(state);const valid=state.storyFlags.day25V4;assert.equal(validateDay25V4(valid),true);const money=structuredClone(valid);money.input.currentMoney+=1;assert.equal(validateDay25V4(money),false);const fake=structuredClone(valid);fake.facts.kissOccurred=true;assert.equal(validateDay25V4(fake),false);assert.throws(()=>completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true}),/INVALID_COMPLETION/);});
