import assert from 'node:assert/strict';
import test from 'node:test';
import {getDay21V4PlayableFeelings} from '../src/day21-v4-playable-feelings.mjs';
import {resolveDay21V4Contact} from '../src/day21-v4-state-contract.mjs';
import {validateDay21V4SourceStep} from '../src/day21-v4-source-selection.mjs';
import {chooseDay21,day21State} from './day21-v4-fixture.mjs';

const assertSourced=steps=>{for(const step of steps)if(step.source)assert.equal(validateDay21V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel??step.prompt}`);};
const reachFeelings=(state,venue=0)=>{for(const index of [0,0,venue,0,0,0,0])chooseDay21(state,index);};

test('park route presents SCENE 13-16 and waits for fresh contact consent',()=>{const s=day21State();reachFeelings(s);let steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.deepEqual(steps.filter(step=>step.type==='sceneDirection').map(step=>step.number),[13,14]);assert.equal(steps.at(-1).choiceNumber,8);assertSourced(steps);chooseDay21(s);steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.equal(steps.at(-1).choiceNumber,9);assertSourced(steps);chooseDay21(s);steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.equal(steps.at(-1).choiceNumber,10);assertSourced(steps);chooseDay21(s);steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.equal(steps.length,1);assert.equal(steps[0].type,'contactConsentCue');assert.equal(s.storyFlags.day21V4.facts.todayContact,null);assertSourced(steps);resolveDay21V4Contact(s,{type:'haeunContactResponse',contact:'HUG',accepted:true});steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.status==='hug-accepted'));assert.equal(steps.at(-1).nextScene,17);assert.equal(s.storyFlags.day21V4.facts.todayContact,'HUG');assertSourced(steps);});

test('declined park contact creates no hug or hand fact',()=>{const s=day21State();reachFeelings(s);chooseDay21(s);chooseDay21(s);chooseDay21(s,1);resolveDay21V4Contact(s,{type:'haeunContactResponse',contact:'HAND',accepted:false});const steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.status==='contact-declined'));assert.equal(steps.some(step=>['hug-accepted','hand-accepted'].includes(step.status)),false);assert.equal(s.storyFlags.day21V4.facts.todayContact,'NONE');assertSourced(steps);});

test('phone route has no Haeun visual, does not request contact resolution, and imagines no hug',()=>{const s=day21State({morningMode:'MESSAGE_MORNING',day20StayedOver:false});reachFeelings(s,1);for(let i=0;i<3;i++){const steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.equal(steps.filter(step=>step.type==='sceneDirection').some(step=>step.character==='girlfriend'),false);assert.equal(steps.some(step=>['bottle-close','park-continues','stretch','stand-walk','hug-accepted','hand-accepted'].includes(step.status)),false);assertSourced(steps);chooseDay21(s);}const end=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.ok(end.some(step=>step.status==='separate-window'));assert.equal(end.some(step=>step.type==='contactConsentCue'),false);assert.equal(s.storyFlags.day21V4.phase,'dinner');assert.equal(s.storyFlags.day21V4.facts.todayContact,'NONE');assert.equal(s.storyFlags.day21V4.choices.some(record=>record.kind==='resolution'),false);assertSourced(end);});

test('distance choice needs no fabricated consent response',()=>{const s=day21State();reachFeelings(s);chooseDay21(s,1);chooseDay21(s,2);chooseDay21(s,2);const steps=getDay21V4PlayableFeelings(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.status==='walk-apart'));assert.equal(steps.some(step=>step.type==='contactConsentCue'),false);assert.equal(s.storyFlags.day21V4.facts.todayContact,'NONE');assertSourced(steps);});
