import assert from 'node:assert/strict';
import test from 'node:test';
import {applyDay24V4Choice,beginDay24V4,completeDay24V4,getDay24V4Options,resolveDay24V4Contact,resolveDay24V4Conversation,resolveDay24V4Relationship} from '../src/day24-v4-state-contract.mjs';
import {applyDay25V4Choice,beginDay25V4,getDay25V4Options,resolveDay25V4NewMeeting} from '../src/day25-v4-state-contract.mjs';
import {getDay25V4PlayableSolo} from '../src/day25-v4-playable-solo.mjs';
import {validateDay25V4SourceStep} from '../src/day25-v4-source-selection.mjs';
import {completedDay23ForDay24} from './day24-v4-fixture.mjs';
import {day25EndedFixture} from './day25-v4-playable-fixture.mjs';

const choose25=(state,suffix)=>{const options=getDay25V4Options(state.storyFlags.day25V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`${state.storyFlags.day25V4.phase}:${suffix}`);applyDay25V4Choice(state,selected.id);};
const choose24=(state,suffix)=>{const options=getDay24V4Options(state.storyFlags.day24V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`${state.storyFlags.day24V4.phase}:${suffix}`);applyDay24V4Choice(state,selected.id);};
const sourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay25V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);};
function enterSolo(state){beginDay25V4(state);choose25(state);choose25(state);choose25(state);assert.equal(state.storyFlags.day25V4.phase,'solo_goal');}
function newMeetingFixture(recipient='ARA'){const state=completedDay23ForDay24('SEOUL_DAY',{pendingContacts:[recipient]});beginDay24V4(state);choose24(state);choose24(state);resolveDay24V4Conversation(state,{type:'haeunConversationResponse',accepted:true,mode:'MEET'});choose24(state);choose24(state);choose24(state);choose24(state);resolveDay24V4Relationship(state,{type:'haeunRelationshipResponse',outcome:'END'});choose24(state,'rest');choose24(state,'relationship_ended');choose24(state,'personal_interest');resolveDay24V4Contact(state,{type:'otherContactResponse',outcome:'ACCEPT_MEETING'});while(state.storyFlags.day24V4.phase!=='ending')choose24(state);completeDay24V4(state,{type:'chapterCompletionCue',day:24,finalSceneReached:true});return state;}

test('SCENE17-18 keeps an ended route on independent life choices',()=>{const state=day25EndedFixture();enterSolo(state);let steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,4);assert.doesNotMatch(JSON.stringify(steps),/하은\*\*|speaker":"하은/);choose25(state,'solo_trip');steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,5);choose25(state,'food');steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,6);choose25(state,'friend');steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).nextScene,20);assert.equal(state.storyFlags.day25V4.facts.newMeetingResponse,null);assert.match(JSON.stringify(steps),/응답이 오기 전에 약속이나 새 연애로 만들지 않았다/);});

test('SCENE19 opens only for the one accepted DAY24 contact and waits for a current response',()=>{const state=newMeetingFixture('ARA');enterSolo(state);choose25(state,'work');choose25(state,'schedule');choose25(state,'rest');let steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,7);assert.match(JSON.stringify(steps),/아라/);assert.doesNotMatch(JSON.stringify(steps),/유리와는|서진에게/);choose25(state,'talk_slow');steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).type,'newMeetingCue');assert.equal(state.storyFlags.day25V4.facts.newMeetingResponse,null);resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:'ARA',outcome:'RESCHEDULED'});steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).nextScene,20);assert.equal(steps.at(-1).newMeetingResponse,'RESCHEDULED');assert.doesNotMatch(JSON.stringify(steps),/연애하고 싶다”고 답했다/);});

test('cancelled new meeting does not cascade the same message to another person',()=>{const state=newMeetingFixture('SEOJIN');enterSolo(state);choose25(state);choose25(state);choose25(state);choose25(state,'slow_down');resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:'SEOJIN',outcome:'CANCELLED'});const steps=getDay25V4PlayableSolo(state.storyFlags.day25V4);sourced(steps);assert.match(JSON.stringify(steps),/다른 사람에게 같은 말을 보내지 않았다/);assert.doesNotMatch(JSON.stringify(steps),/유리와는|아라와/);assert.equal(steps.at(-1).nextScene,20);});
