import assert from 'node:assert/strict';
import test from 'node:test';
import {applyDay21V4GameChoice,applyDay21V4GameResolution,completeDay21V4GameChapter,getDay21V4GameCompatibility,getDay21V4GameResumePresentation,getDay21V4GameSegment,prepareDay21V4GameEntry} from '../src/day21-v4-game-bridge.mjs';
import {getDay21V4Options} from '../src/day21-v4-state-contract.mjs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {day21State} from './day21-v4-fixture.mjs';

const state=(overrides={})=>{const s=day21State(overrides);return {day:21,money:180000,economyLedger:[],storyHistory:[],pendingStoryId:'m30-day21-current-full-workday',breakup:null,ended:false,...s};};
const choose=(s,index=0)=>applyDay21V4GameChoice(s,getDay21V4Options(s.storyFlags.day21V4)[index].id);
const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};};

test('bridge compatibility preserves legacy and resumes validated V4',()=>{const s=state();assert.equal(getDay21V4GameCompatibility(s).mode,'V4');assert.equal(prepareDay21V4GameEntry(s).mode,'V4');assert.equal(getDay21V4GameSegment(s).at(-1).choiceNumber,1);const legacy={storyFlags:{day20RuntimeComplete:true,day21RuntimeStage:1}};assert.equal(getDay21V4GameCompatibility(legacy).mode,'LEGACY');assert.equal(legacy.storyFlags.day21V4,undefined);});

test('park bridge stitches all modules and strips internal boundaries',()=>{const s=state();let guard=0;while(s.storyFlags.day21V4.phase!=='ending'){assert.ok(guard++<30);const phase=s.storyFlags.day21V4.phase;let packet;if(phase==='contact_resolution')packet=applyDay21V4GameResolution(s,{type:'haeunContactResponse',contact:'HUG',accepted:true});else if(phase==='lodging_resolution')packet=applyDay21V4GameResolution(s,{type:'haeunLodgingResponse',accepted:true});else if(phase==='travel_resolution')packet=applyDay21V4GameResolution(s,{type:'travelConfirmation',confirmed:true,dateConfirmed:true,transportConfirmed:true,budgetConfirmed:true,lodgingConfirmed:true,mutualConsent:true,quoteId:'fixture-busan-1',playerCost:60000});else{const phase=s.storyFlags.day21V4.phase,index=phase==='contact'?0:phase==='dinner'?2:phase==='travel'?0:phase==='lodging'?1:0;packet=choose(s,index);}assert.equal(packet.steps.some(step=>/Boundary$/.test(step.type)),false);assert.ok(packet.steps.some(step=>step.type==='choice'||step.type==='contactConsentCue'||step.type==='lodgingConsentCue'||step.type==='travelConfirmationCue'||step.type==='chapterCompletionCue'));}const final=getDay21V4GameSegment(s);assert.ok(final.some(step=>step.type==='transition'&&step.sceneNumber===24));assert.equal(final.at(-1).type,'chapterCompletionCue');assert.equal(s.money,120000);assert.equal(s.economyLedger.filter(entry=>entry.category==='travel').length,1);assert.equal(s.storyFlags.day21V4.facts.bookingConfirmed,true);assert.doesNotThrow(()=>getDay21V4GameResumePresentation(s));});

test('deferred bridge has no Haeun character, story knowledge, or transaction',()=>{const s=state({relationshipActive:false,contactAllowed:false,relationshipTone:'DIFFICULT',morningMode:'SOLO_MORNING',day20VisitMode:'SOLO',day20StayedOver:false});for(let guard=0;s.storyFlags.day21V4.phase!=='ending';guard++){assert.ok(guard<12);const opts=getDay21V4Options(s.storyFlags.day21V4),index=s.storyFlags.day21V4.phase==='venue'?0:0,packet=applyDay21V4GameChoice(s,opts[index].id);for(const step of packet.steps.filter(step=>step.type==='transition'))assert.equal(step.characterId,null);assert.equal(packet.steps.some(step=>step.type==='message'),false);}const final=getDay21V4GameSegment(s);assert.equal(final.some(step=>/맛있었던 첫입|양말을 보고/.test(step.text??'')),false);assert.equal(s.storyFlags.day21V4.facts.heardHaeunStory,false);assert.equal(s.economyLedger.length,0);});

test('travel confirmation requires an explicit quote and rolls back money and chapter',()=>{const s=state();for(const index of [0,0,0,0,0,0,0,0,0,2,2,0,0])choose(s,index);assert.equal(s.storyFlags.day21V4.phase,'travel_resolution');const before=structuredClone(s);assert.throws(()=>applyDay21V4GameResolution(s,{type:'travelConfirmation',confirmed:true,dateConfirmed:true,transportConfirmed:true,budgetConfirmed:true,lodgingConfirmed:true,mutualConsent:true}),/COST_REQUIRED/);assert.deepEqual(s,before);assert.throws(()=>applyDay21V4GameResolution(s,{type:'travelConfirmation',confirmed:true,dateConfirmed:true,transportConfirmed:true,budgetConfirmed:true,lodgingConfirmed:true,mutualConsent:true,quoteId:'too-much',playerCost:999999}),/BUDGET_CHANGED/);assert.deepEqual(s,before);});

test('failed contact resolution is atomic',()=>{const s=state();for(const index of [0,0,0,0,0,0,0,0,0,0])choose(s,index);const before=structuredClone(s.storyFlags.day21V4);assert.throws(()=>applyDay21V4GameResolution(s,{type:'haeunContactResponse',contact:'HAND',accepted:true}),/MISMATCH/);assert.deepEqual(s.storyFlags.day21V4,before);});

test('completion records V4 history once and opens DAY22 hook',()=>{const s=state({relationshipActive:false,contactAllowed:false,relationshipTone:'DIFFICULT',morningMode:'SOLO_MORNING',day20VisitMode:'SOLO',day20StayedOver:false});while(s.storyFlags.day21V4.phase!=='ending')choose(s);completeDay21V4GameChapter(s,{type:'chapterCompletionCue',day:21,finalSceneReached:true});completeDay21V4GameChapter(s,{type:'chapterCompletionCue',day:21,finalSceneReached:true});assert.equal(s.storyFlags.day21V4.complete,true);assert.equal(s.storyFlags.day20V4Day21HookPending,false);assert.equal(s.storyFlags.day21V4Day22HookPending,true);assert.equal(s.storyHistory.length,1);assert.equal(s.storyHistory[0].scenarioId,'day21-notion-v4');assert.equal(s.storyFlags.day21RuntimeComplete,true);});

test('SaveManager round-trip preserves a mid-DAY21 checkpoint and next segment',()=>{const s=state();for(let index=0;index<6;index++)choose(s);const expected=getDay21V4GameSegment(s),store=storage(),shell=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});Object.assign(shell,s);SaveManager.save(shell,store);const loaded=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.deepEqual(loaded.storyFlags.day21V4,s.storyFlags.day21V4);assert.deepEqual(getDay21V4GameSegment(loaded),expected);assert.deepEqual(getDay21V4GameResumePresentation(loaded),getDay21V4GameResumePresentation(s));});
