import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {applyDay24V4GameChoice,applyDay24V4GameResolution,completeDay24V4GameChapter,getDay24V4GameCompatibility,getDay24V4GameResumePresentation,getDay24V4GameSegment,isDay24V4ResolutionStep,prepareDay24V4GameEntry} from '../src/day24-v4-game-bridge.mjs';
import {getDay24V4RuntimeResolution} from '../src/day24-v4-runtime-resolution.mjs';
import {getDay24V4Options} from '../src/day24-v4-state-contract.mjs';
import {completedDay23ForDay24} from './day24-v4-fixture.mjs';

const state=(route='SEOUL_DAY',options={})=>{const value=completedDay23ForDay24(route,options);value.storyHistory=[];return value;};
const choose=(state,index=0)=>applyDay24V4GameChoice(state,getDay24V4Options(state.storyFlags.day24V4)[index].id);
function finish(state){let guard=0;while(state.storyFlags.day24V4.phase!=='ending'){assert.ok(guard++<40);const steps=getDay24V4GameSegment(state),cue=steps.find(isDay24V4ResolutionStep);if(cue)applyDay24V4GameResolution(state,getDay24V4RuntimeResolution(state,cue));else choose(state);}return getDay24V4GameSegment(state);}
const storage=()=>{const data=new Map();return {setItem:(key,value)=>data.set(key,value),getItem:key=>data.get(key)??null,removeItem:key=>data.delete(key)};};

test('bridge starts only from verified DAY23 V4 and preserves legacy DAY24',()=>{const s=state();assert.equal(getDay24V4GameCompatibility(s).mode,'V4_NEW');assert.equal(prepareDay24V4GameEntry(s).mode,'V4');assert.equal(getDay24V4GameSegment(s).at(-1).choiceNumber,1);const legacy={storyFlags:{day23RuntimeComplete:true,day24RuntimeStage:1}};assert.equal(getDay24V4GameCompatibility(legacy).mode,'LEGACY');});

test('calm continuation stitches all playables and keeps every response separate',()=>{const s=state();prepareDay24V4GameEntry(s);const all=[];let guard=0;while(s.storyFlags.day24V4.phase!=='ending'){assert.ok(guard++<40);const steps=getDay24V4GameSegment(s);all.push(...steps);const cue=steps.find(isDay24V4ResolutionStep);if(cue)applyDay24V4GameResolution(s,getDay24V4RuntimeResolution(s,cue));else choose(s);}all.push(...getDay24V4GameSegment(s));assert.ok(all.some(step=>step.type==='transition'&&step.sceneNumber===24));assert.ok(all.some(step=>step.type==='haeunConversationCue'));assert.ok(all.some(step=>step.type==='haeunRelationshipCue'));assert.ok(all.some(step=>step.type==='haeunFutureTalkCue'));assert.equal(s.storyFlags.day24V4.facts.haeunRelationshipOutcome,'CONTINUE');assert.equal(s.storyFlags.day24V4.facts.futureTalkAccepted,true);for(const step of all.filter(step=>step.type==='transition')){assert.ok(step.backgroundUrl);assert.ok(step.storyClock);}});

test('ended relationship can accept one actual new meeting without creating a new relationship',()=>{const s=state('SEOUL_DAY',{pendingContacts:['YURI']});prepareDay24V4GameEntry(s);let guard=0;while(s.storyFlags.day24V4.phase!=='ending'){assert.ok(guard++<40);const chapter=s.storyFlags.day24V4,steps=getDay24V4GameSegment(s),cue=steps.find(isDay24V4ResolutionStep);if(cue){let response=getDay24V4RuntimeResolution(s,cue);if(cue.type==='haeunRelationshipCue')response={type:'haeunRelationshipResponse',outcome:'END'};applyDay24V4GameResolution(s,response);continue;}const options=getDay24V4Options(chapter);const selected=chapter.phase==='relationship_proposal'?options.find(item=>item.id.endsWith('_break_up')):chapter.phase==='contact_expectation'?options.find(item=>item.id.endsWith('_relationship_ended')):options[0];applyDay24V4GameChoice(s,selected.id);}assert.equal(s.storyFlags.day24V4.facts.newMeetingAccepted,true);assert.equal(s.storyFlags.day24V4.facts.day25Route,'RELATIONSHIP_ENDED');assert.doesNotMatch(JSON.stringify(getDay24V4GameSegment(s)),/새 연인|교제 시작했다/);});

test('resolution errors restore the whole DAY24 chapter atomically',()=>{const s=state();prepareDay24V4GameEntry(s);choose(s);choose(s);const before=structuredClone(s.storyFlags.day24V4);assert.throws(()=>applyDay24V4GameResolution(s,{type:'haeunConversationResponse',accepted:true,mode:'INVALID'}),/MODE_INVALID/);assert.deepEqual(s.storyFlags.day24V4,before);});

test('mid-day save round-trip preserves segment and resume presentation',()=>{const s=state();prepareDay24V4GameEntry(s);for(let i=0;i<8;i++){const steps=getDay24V4GameSegment(s),cue=steps.find(isDay24V4ResolutionStep);if(cue)applyDay24V4GameResolution(s,getDay24V4RuntimeResolution(s,cue));else choose(s);}const expected=getDay24V4GameSegment(s),store=storage(),shell=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});Object.assign(shell,s);SaveManager.save(shell,store);const loaded=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.deepEqual(loaded.storyFlags.day24V4,s.storyFlags.day24V4);assert.deepEqual(getDay24V4GameSegment(loaded),expected);assert.deepEqual(getDay24V4GameResumePresentation(loaded),getDay24V4GameResumePresentation(s));});

test('completion records one route history and opens DAY25 without legacy free action',()=>{const s=state();prepareDay24V4GameEntry(s);const cue=finish(s).at(-1);completeDay24V4GameChapter(s,cue);completeDay24V4GameChapter(s,cue);assert.equal(s.storyFlags.day24V4.complete,true);assert.equal(s.storyFlags.day23V4Day24HookPending,false);assert.equal(s.storyFlags.day24V4Day25HookPending,true);assert.equal(s.storyHistory.length,1);assert.equal(s.storyHistory[0].scenarioId,'day24-notion-v4');assert.equal(s.storyFlags.day24RuntimeComplete,true);assert.equal(s.storyFlags.day24FreeActionComplete,undefined);});

test('main Story loop connects DAY24 V4 while legacy-only Free Action stays excluded',()=>{const source=readFileSync(new URL('../game.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(source,/day24-v4-game-bridge\.mjs\?v=1/);assert.match(source,/day24-v4-runtime-resolution\.mjs\?v=1/);assert.match(source,/if\(day24V4\)prepareDay24V4GameEntry/);assert.match(source,/applyDay24V4GameChoice\(currentState,id\)/);assert.match(source,/getDay24V4RuntimeResolution\(state,step\)/);assert.match(source,/applyDay24V4GameResolution\(state,response\)/);assert.match(source,/step\.day===24\?completeDay24V4GameChapter/);assert.match(source,/completionCue\.day===24\)completeDay24V4GameChapter/);assert.match(source,/isDay24V4ResolutionStep\(step\)/);assert.match(source,/lockedDay24&&!day24V4\?24/);assert.match(source,/completedSession\?\.id===LOCKED_DAY24_SCENE_ID&&!state\.storyFlags\?\.day24V4/);assert.match(source,/!\(lockedDay24&&day24V4\)/);assert.match(html,/game\.js\?v=269/);});
