import assert from 'node:assert/strict';
import test from 'node:test';
import {day25ContinuedFixture,day25NewMeetingFixture} from './day25-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location,resolveDay25V4NewMeeting} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,completeDay26V4,getDay26V4Options,resolveDay26V4Jihoon} from '../src/day26-v4-state-contract.mjs';
import {getDay26V4PlayableEnding} from '../src/day26-v4-playable-ending.mjs';
import {validateDay26V4SourceStep} from '../src/day26-v4-source-selection.mjs';

const choose25=(state,suffix)=>{const option=getDay25V4Options(state.storyFlags.day25V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option);applyDay25V4Choice(state,option.id);};
function day26(state,{friends='later',meeting='RESCHEDULED'}={}){beginDay25V4(state);let guard=0;while(state.storyFlags.day25V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}if(phase==='new_meeting_resolution'){resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:state.storyFlags.day25V4.input.newMeeting.recipient,outcome:meeting});continue;}choose25(state,phase==='friend_meal'?friends:undefined);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});beginDay26V4(state);return state;}
const choose26=(state,suffix)=>{const option=getDay26V4Options(state.storyFlags.day26V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day26V4.phase}:${suffix}`);applyDay26V4Choice(state,option.id);};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay26V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}

test('SCENE21 solo route exposes only alternate C2-C8 and preserves absent people',()=>{const state=day26(day25NewMeetingFixture());choose26(state,'rest');let steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,2);const seen=[];while(state.storyFlags.day26V4.phase!=='closing'){const chapter=state.storyFlags.day26V4;steps=getDay26V4PlayableEnding(chapter);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered,chapter.phase);seen.push(offered.choiceNumber);choose26(state,chapter.phase==='solo_friend'?'no_contact':undefined);}assert.deepEqual(seen,[2,3,4,5,6,7,8]);steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,14);assert.doesNotMatch(JSON.stringify(steps),/괜찮다고 먼저 말해/);});

test('solo future meal waits for Jihoon response before continuing',()=>{const state=day26(day25ContinuedFixture());choose26(state,'rest');choose26(state);choose26(state,'ask_later');let steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).type,'jihoonMealCue');resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:false});steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,4);assert.match(JSON.stringify(steps),/다음으로 두었다/);});

test('C12 respect-rest skips Haeun night call while ordinary message opens C13',()=>{for(const [message,expected] of [['respect_rest','closing'],['good_day','haeun_night']]){const state=day26(day25ContinuedFixture(),{friends:'meet'});choose26(state);choose26(state);choose26(state,'no_announcement');while(state.storyFlags.day26V4.phase!=='group_message')choose26(state);choose26(state,message);assert.equal(state.storyFlags.day26V4.phase,expected);const steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,expected==='haeun_night'?13:14);if(expected==='closing')assert.doesNotMatch(JSON.stringify(steps),/괜찮다고 먼저 말해/);}});

test('C14 records a concrete DAY27 handoff and final completion cue',()=>{const state=day26(day25NewMeetingFixture());choose26(state,'rest');while(state.storyFlags.day26V4.phase!=='closing')choose26(state,state.storyFlags.day26V4.phase==='solo_friend'?'no_contact':undefined);let steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,14);choose26(state,'listen_first');assert.deepEqual(state.storyFlags.day26V4.facts.day27Handoff,{listenTarget:null,correctionTarget:null,nextTalk:'ASK_WHEN_NEEDED',respectRequestedTime:false});steps=getDay26V4PlayableEnding(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.equal(steps.at(-1).day27Route,'INDEPENDENT_LIFE');completeDay26V4(state,steps.at(-1));assert.equal(state.storyFlags.day26V4.complete,true);assert.equal(state.storyFlags.day26V4Day27HookPending,true);});
