import assert from 'node:assert/strict';
import test from 'node:test';
import {day25MixedFixture} from './day25-v4-playable-fixture.mjs';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,completeDay26V4,getDay26V4Options,resolveDay26V4Attendance,resolveDay26V4Jihoon,resolveDay26V4NewMeaning,resolveDay26V4NewNext} from '../src/day26-v4-state-contract.mjs';
import {applyDay27V4Choice,beginDay27V4,completeDay27V4,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4TruthRecipient} from '../src/day27-v4-state-contract.mjs';
import {applyDay28V4Choice,beginDay28V4,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {applyDay29V4Choice,beginDay29V4,getDay29V4Options,resolveDay29V4Evening,resolveDay29V4New,resolveDay29V4Truth,validateDay29V4} from '../src/day29-v4-state-contract.mjs';
import {getDay29V4PlayableOpening} from '../src/day29-v4-playable-opening.mjs';
import {getDay29V4PlayableEveningBranches} from '../src/day29-v4-playable-evening-branches.mjs';
import {getDay29V4RuntimeResolution} from '../src/day29-v4-runtime-resolution.mjs';
import {validateDay29V4SourceStep} from '../src/day29-v4-source-selection.mjs';

const pick=(options,suffix)=>{const option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${suffix}:${options.map(item=>item.id).join(',')}`);return option.id;};
const choose25=(state,suffix)=>applyDay25V4Choice(state,pick(getDay25V4Options(state.storyFlags.day25V4),suffix));
const choose26=(state,suffix)=>applyDay26V4Choice(state,pick(getDay26V4Options(state.storyFlags.day26V4),suffix));
const choose27=(state,suffix)=>applyDay27V4Choice(state,pick(getDay27V4Options(state.storyFlags.day27V4),suffix));
const choose28=(state,suffix)=>applyDay28V4Choice(state,pick(getDay28V4Options(state.storyFlags.day28V4),suffix));
const choose29=(state,suffix)=>applyDay29V4Choice(state,pick(getDay29V4Options(state.storyFlags.day29V4),suffix));
function sourced(steps){for(const step of steps)if(['dialogue','monologue','playerNarration','storyActionCue'].includes(step.type))assert.equal(validateDay29V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);}

function finish28(state,newRoute=false){while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});continue;}if(phase==='new_relationship_resolution'){resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});continue;}choose28(state,phase==='continuing_distance'?'talk_only':phase==='new_meeting_wish'&&newRoute?'want_romance':null);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});beginDay29V4(state);return state;}
function toEvening(state,suffix=null){while(state.storyFlags.day29V4.phase!=='evening'&&state.storyFlags.day29V4.phase!=='solo_evening')choose29(state);if(state.storyFlags.day29V4.phase==='evening')choose29(state,suffix);if(state.storyFlags.day29V4.phase==='evening_resolution'){const cue=getDay29V4PlayableOpening(state.storyFlags.day29V4).at(-1);resolveDay29V4Evening(state,getDay29V4RuntimeResolution(state,cue));}return state;}

function unresolvedTruthFixture(){const state=day25MixedFixture();beginDay25V4(state);while(state.storyFlags.day25V4.phase!=='ending'){const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}choose25(state);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});beginDay26V4(state);while(state.storyFlags.day26V4.phase!=='ending'){const phase=state.storyFlags.day26V4.phase;if(phase==='attendance_resolution'){resolveDay26V4Attendance(state,{type:'attendanceChangeResponse',accepted:true});continue;}if(phase==='jihoon_resolution'||phase==='solo_friend_resolution'){resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:false});continue;}if(phase==='new_meaning_resolution'){resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'SEOJIN',outcome:'NEED_TIME'});continue;}if(phase==='new_next_resolution'){resolveDay26V4NewNext(state,{type:'newMeetingNextResponse',recipient:'SEOJIN',outcome:'DEFERRED'});continue;}choose26(state);}completeDay26V4(state,{type:'chapterCompletionCue',day:26,finalSceneReached:true});beginDay27V4(state);choose27(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'SEOJIN',outcome:'ACCEPTED',method:'IN_PERSON'});choose27(state);choose27(state,'deflect');resolveDay27V4TruthRecipient(state,{type:'day27TruthRecipientResponse',recipient:'SEOJIN',outcome:'END_TODAY'});choose27(state);choose27(state);completeDay27V4(state,{type:'chapterCompletionCue',day:27,finalSceneReached:true});beginDay28V4(state);while(state.storyFlags.day28V4.phase!=='ending')choose28(state);completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});beginDay29V4(state);return toEvening(state);}

test('SCENE18 renders only sealed Ara and waits for her current answer',()=>{const state=toEvening(finish28(day28NewMeetingFixture(),true));assert.equal(state.storyFlags.day29V4.phase,'new_evening');let steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.find(step=>step.type==='sceneDirection').number,18);assert.match(JSON.stringify(steps),/아라/);assert.doesNotMatch(JSON.stringify(steps),/유리|서진/);choose29(state,'meet_again');steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).type,'day29NewCue');assert.equal(state.storyFlags.day29V4.facts.newResponse,null);resolveDay29V4New(state,getDay29V4RuntimeResolution(state,steps.at(-1)));assert.equal(state.storyFlags.day29V4.facts.newResponse,'ACCEPTED');steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).nextScene,21);assert.equal(validateDay29V4(state.storyFlags.day29V4),true);});

test('SCENE19 solo route has no person response and hides unknown Jihoon',()=>{const state=toEvening(finish28(day28SoloFixture()));assert.equal(state.storyFlags.day29V4.phase,'solo_evening');let steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.find(step=>step.type==='sceneDirection').number,19);assert.equal(steps.at(-1).options.some(option=>option.id.endsWith('_jihoon')),false);assert.doesNotMatch(JSON.stringify(steps),/speaker|day29.*Cue/);choose29(state,'watch');steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).nextScene,21);assert.doesNotMatch(JSON.stringify(steps),/하은|유리|서진|아라|지훈/);});

test('known but busy Jihoon receives only a message without invented dialogue',()=>{const state=toEvening(finish28(day28FriendlyFixture()),'solo');assert.equal(state.storyFlags.day29V4.input.jihoonKnown,true);assert.equal(state.storyFlags.day29V4.input.jihoonAvailable,false);const opening=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);assert.equal(opening.at(-1).options.some(option=>option.id.endsWith('_jihoon')),true);choose29(state,'jihoon');const steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.match(JSON.stringify(steps),/바쁜 지훈에게 안부만 남기고/);assert.equal(steps.some(step=>step.type==='dialogue'&&step.speaker==='지훈'),false);});

test('SCENE20 addresses only the actual lie recipient and preserves NEED_TIME',()=>{const state=unresolvedTruthFixture();assert.equal(state.storyFlags.day29V4.input.unresolvedLie.recipient,'SEOJIN');choose29(state,'tidy');assert.equal(state.storyFlags.day29V4.phase,'truth');let steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.find(step=>step.type==='sceneDirection').number,20);choose29(state,'correct');steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);const cue=steps.at(-1);assert.equal(cue.type,'day29TruthCue');assert.equal(cue.target,'SEOJIN');const response=getDay29V4RuntimeResolution(state,cue);assert.equal(response.outcome,'NEED_TIME');resolveDay29V4Truth(state,response);steps=getDay29V4PlayableEveningBranches(state.storyFlags.day29V4);sourced(steps);assert.equal(steps.at(-1).nextScene,21);assert.equal(state.storyFlags.day29V4.facts.truthResponse,'NEED_TIME');assert.doesNotMatch(JSON.stringify(steps),/speaker":"하은|하은이/);});
