import assert from 'node:assert/strict';
import test from 'node:test';
import {day27EndedFixture,day27MixedFixture} from './day27-v4-playable-fixture.mjs';
import {applyDay27V4Choice,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4HaeunListening,resolveDay27V4Relationship,resolveDay27V4TruthRecipient} from '../src/day27-v4-state-contract.mjs';
import {getDay27V4PlayableOpening} from '../src/day27-v4-playable-opening.mjs';
import {validateDay27V4SourceStep} from '../src/day27-v4-source-selection.mjs';

const choose=(state,suffix)=>{const option=getDay27V4Options(state.storyFlags.day27V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day27V4.phase}:${suffix}`);applyDay27V4Choice(state,option.id);};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay27V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}

test('SCENE01 waits for current conversation response and no-conversation history never renders a person',()=>{const state=day27MixedFixture();let steps=getDay27V4PlayableOpening(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.find(step=>step.type==='choice').choiceNumber,1);choose(state);steps=getDay27V4PlayableOpening(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).type,'day27ConversationCue');assert.doesNotMatch(JSON.stringify(steps),/어제 물었던 이야기/);const ended=day27EndedFixture();choose(ended);steps=getDay27V4PlayableOpening(ended.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).nextScene,23);assert.doesNotMatch(JSON.stringify(steps),/speaker|characterId/);});

test('SCENE02-09 renders only the sealed lie recipient and exact-backed C2-C7',()=>{const state=day27MixedFixture(),seen=[];choose(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'SEOJIN',outcome:'ACCEPTED',method:'CALL'});let guard=0;while(state.storyFlags.day27V4.phase!=='relationship_resolution'){assert.ok(guard++<20);const chapter=state.storyFlags.day27V4,steps=getDay27V4PlayableOpening(chapter);sourced(steps);const offered=steps.find(step=>step.type==='choice');if(offered){seen.push(offered.choiceNumber);choose(state);}else if(chapter.phase==='truth_recipient_resolution')resolveDay27V4TruthRecipient(state,{type:'day27TruthRecipientResponse',recipient:'SEOJIN',outcome:'CONTINUE'});else if(chapter.phase==='haeun_listen_resolution')resolveDay27V4HaeunListening(state,{type:'day27HaeunListeningResponse',outcome:'LISTEN'});else assert.fail(chapter.phase);}const final=getDay27V4PlayableOpening(state.storyFlags.day27V4);sourced(final);assert.equal(final.at(-1).type,'day27RelationshipCue');assert.deepEqual(seen,[2,3,4,5,6,7]);const all=JSON.stringify(final);assert.doesNotMatch(all,/유리|아라/);resolveDay27V4Relationship(state,{type:'day27RelationshipResponse',outcome:'PAUSE',contactAllowed:false});assert.equal(getDay27V4PlayableOpening(state.storyFlags.day27V4).at(-1).nextScene,18);});

test('a recipient ending the truth talk skips apology and does not fabricate Haeun listening',()=>{const state=day27MixedFixture();choose(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'SEOJIN',outcome:'ACCEPTED',method:'IN_PERSON'});choose(state);choose(state);let steps=getDay27V4PlayableOpening(state.storyFlags.day27V4);sourced(steps);resolveDay27V4TruthRecipient(state,{type:'day27TruthRecipientResponse',recipient:'SEOJIN',outcome:'END_TODAY'});steps=getDay27V4PlayableOpening(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).nextScene,19);assert.doesNotMatch(JSON.stringify(steps),/하은이 지금 들을 수 있는지/);});
