import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,completeDay19V4,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {applyDay20V4Choice,beginDay20V4,getDay20V4Options,resolveDay20V4Contact} from '../src/day20-v4-state-contract.mjs';
import {getDay20V4PlayableIntimacy} from '../src/day20-v4-playable-intimacy.mjs';
import {validateDay20V4SourceStep} from '../src/day20-v4-source-selection.mjs';

function state(){const s={breakup:null,ended:false,money:42000,storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:'HAEUN',day17V4Choice9:'day17_v4_life_haeun',day17V4DinnerAgreement:{day:18,partner:'HAEUN',status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,{});for(const key of['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near'])applyDay18V4Choice(s,`day18_v4_${key}`);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);while(s.storyFlags.day19V4.phase!=='ending'){const opts=getDay19V4Options(s.storyFlags.day19V4),i=s.storyFlags.day19V4.phase==='dinner'?2:s.storyFlags.day19V4.phase==='tomorrow_table'?0:0;applyDay19V4Choice(s,opts[i].id);}completeDay19V4(s,{type:'chapterCompletionCue',day:19,finalSceneReached:true});beginDay20V4(s);while(s.storyFlags.day20V4.phase!=='clothes')applyDay20V4Choice(s,getDay20V4Options(s.storyFlags.day20V4)[0].id);return s;}
const choose=(s,index=0)=>applyDay20V4Choice(s,getDay20V4Options(s.storyFlags.day20V4)[index].id);
const sourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay20V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);};

test('intimacy playable uses the no-borrow branch and preserves current-distance choice',()=>{const s=state();let steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.equal(steps[0].number,12);assert.ok(steps.some(step=>step.text?.includes('옷을 바꾸지 않은 저녁')));assert.equal(s.storyFlags.day20V4.facts.borrowedClothes,false);sourced(steps);choose(s,2);steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===13));assert.equal(steps.at(-1).choiceNumber,10);sourced(steps);choose(s,2);steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.equal(s.storyFlags.day20V4.facts.firstHug,false);assert.equal(s.storyFlags.day20V4.facts.heldHands,false);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===15));assert.equal(steps.at(-1).choiceNumber,11);sourced(steps);});

test('hug request remains unrealized until Haeun response is recorded',()=>{const s=state();choose(s);choose(s,0);let steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.equal(steps.at(-1).type,'haeunContactResolution');assert.equal(steps.at(-1).contact,'HUG');assert.equal(s.storyFlags.day20V4.facts.firstHug,false);sourced(steps);resolveDay20V4Contact(s,{type:'haeunContactResponse',contact:'HUG',accepted:true});steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.equal(s.storyFlags.day20V4.facts.firstHug,true);assert.ok(steps.some(step=>step.status==='first-hug'));assert.ok(steps.some(step=>step.text==='응.'));assert.equal(steps.at(-1).choiceNumber,11);sourced(steps);});

test('SCENE 17 and 18 continue from only the recorded closeness path',()=>{const s=state();choose(s);choose(s,2);choose(s,1);let steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.equal(steps.at(-1).choiceNumber,12);assert.equal(steps.some(step=>step.status==='first-hug'),false);sourced(steps);choose(s,2);steps=getDay20V4PlayableIntimacy(s.storyFlags.day20V4);assert.equal(steps.at(-1).type,'intimacyBoundary');assert.equal(steps.at(-1).nextScene,20);sourced(steps);});
