import assert from 'node:assert/strict';
import test from 'node:test';
import {day25ContinuedFixture,day25EndedFixture,day25MixedFixture} from './day25-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,completeDay26V4,getDay26V4Options,resolveDay26V4Attendance,resolveDay26V4Jihoon,resolveDay26V4NewMeaning,resolveDay26V4NewNext} from '../src/day26-v4-state-contract.mjs';
import {applyDay27V4Choice,beginDay27V4,completeDay27V4,getDay27V4Entry,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4HaeunListening,resolveDay27V4Jihoon,resolveDay27V4NextTalk,resolveDay27V4Relationship,resolveDay27V4TruthRecipient,validateDay27V4} from '../src/day27-v4-state-contract.mjs';

const choose25=(state,suffix)=>{const options=getDay25V4Options(state.storyFlags.day25V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected);applyDay25V4Choice(state,selected.id);};
function complete25(state){beginDay25V4(state);let guard=0;while(state.storyFlags.day25V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){const proposal=state.storyFlags.day25V4.facts.proposal;resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:proposal==='PREPARE_MARRIAGE'?'PREPARE_MARRIAGE':'REDISCUSS'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}choose25(state);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});return state;}
const choose26=state=>{const option=getDay26V4Options(state.storyFlags.day26V4)[0];assert.ok(option);applyDay26V4Choice(state,option.id);};
function complete26(state){complete25(state);beginDay26V4(state);let guard=0;while(state.storyFlags.day26V4.phase!=='ending'){assert.ok(guard++<60);const phase=state.storyFlags.day26V4.phase;if(phase==='attendance_resolution'){resolveDay26V4Attendance(state,{type:'attendanceChangeResponse',accepted:true});continue;}if(phase==='jihoon_resolution'||phase==='solo_friend_resolution'){resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:false});continue;}if(phase==='new_meaning_resolution'){resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:state.storyFlags.day26V4.input.newMeeting.recipient,outcome:'NEED_TIME'});continue;}if(phase==='new_next_resolution'){resolveDay26V4NewNext(state,{type:'newMeetingNextResponse',recipient:state.storyFlags.day26V4.input.newMeeting.recipient,outcome:'DEFERRED'});continue;}choose26(state);}completeDay26V4(state,{type:'chapterCompletionCue',day:26,finalSceneReached:true});return state;}
const choose27=(state,suffix)=>{const options=getDay27V4Options(state.storyFlags.day27V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`DAY27:${state.storyFlags.day27V4.phase}:${suffix}`);applyDay27V4Choice(state,selected.id);};

test('DAY27 entry freezes verified DAY24-26 history and preserves legacy saves',()=>{const state=complete26(day25ContinuedFixture());const entry=getDay27V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.relationshipContinues,true);assert.equal(entry.input.conversationTarget,'HAEUN');assert.equal(entry.input.publicOverstatement,false);assert.equal(entry.input.source.day26Schema,'day26-notion-v4/1');const legacy=structuredClone(state);legacy.storyFlags.day27RuntimeStage=1;assert.equal(getDay27V4Entry(legacy).mode,'LEGACY');const broken=structuredClone(state);broken.storyFlags.day26V4.facts.day27Handoff.listenTarget='ARA';assert.equal(getDay27V4Entry(broken).mode,'BLOCKED_PREREQUISITE');});

test('honest conversation keeps Haeun relationship and next appointment responses independent',()=>{const state=complete26(day25ContinuedFixture());beginDay27V4(state);choose27(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'HAEUN',outcome:'ACCEPTED',method:'CALL'});choose27(state);assert.equal(state.storyFlags.day27V4.facts.route,'HONEST_LISTENING');choose27(state);choose27(state);choose27(state);choose27(state,'stop_today');resolveDay27V4Relationship(state,{type:'day27RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});resolveDay27V4Jihoon(state,{type:'day27JihoonResponse',available:false});choose27(state);choose27(state);choose27(state,'short_meeting');resolveDay27V4NextTalk(state,{type:'day27NextTalkResponse',outcome:'ACCEPTED'});assert.equal(state.storyFlags.day27V4.phase,'ending');assert.equal(state.storyFlags.day27V4.facts.nextTalkResponse,'ACCEPTED');assert.equal(validateDay27V4(state.storyFlags.day27V4),true);completeDay27V4(state,{type:'chapterCompletionCue',day:27,finalSceneReached:true});assert.equal(state.storyFlags.day27V4Day28HookPending,true);assert.equal(state.storyFlags.day26V4Day27HookPending,false);});

test('actual unresolved lie is routed only to its recipient and does not auto-forgive Haeun',()=>{const state=complete26(day25MixedFixture());beginDay27V4(state);assert.equal(state.storyFlags.day27V4.input.conversationTarget,'SEOJIN');choose27(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'SEOJIN',outcome:'ACCEPTED',method:'IN_PERSON'});choose27(state);assert.equal(state.storyFlags.day27V4.facts.route,'RELATIONSHIP_TRUTH');choose27(state,'admit_lie');resolveDay27V4TruthRecipient(state,{type:'day27TruthRecipientResponse',recipient:'SEOJIN',outcome:'CONTINUE'});choose27(state);choose27(state,'disclose');resolveDay27V4HaeunListening(state,{type:'day27HaeunListeningResponse',outcome:'LISTEN'});choose27(state);choose27(state);resolveDay27V4Relationship(state,{type:'day27RelationshipResponse',outcome:'PAUSE',contactAllowed:false});resolveDay27V4Jihoon(state,{type:'day27JihoonResponse',available:false});choose27(state);choose27(state);assert.equal(state.storyFlags.day27V4.phase,'ending');assert.equal(state.storyFlags.day27V4.facts.lieCorrected,true);assert.equal(state.storyFlags.day27V4.facts.relationshipContinues,false);assert.equal(validateDay27V4(state.storyFlags.day27V4),true);});

test('no-conversation history reaches only the six alternate choices without invented answers',()=>{const state=complete26(day25EndedFixture());beginDay27V4(state);assert.equal(state.storyFlags.day27V4.input.conversationTarget,null);choose27(state);for(let i=0;i<6;i++)choose27(state);assert.equal(state.storyFlags.day27V4.phase,'ending');assert.equal(state.storyFlags.day27V4.facts.conversationOutcome,null);assert.equal(state.storyFlags.day27V4.facts.noConversation.length,6);assert.equal(validateDay27V4(state.storyFlags.day27V4),true);const forged=structuredClone(state.storyFlags.day27V4);forged.input.currentMoney+=1;assert.equal(validateDay27V4(forged),false);});
