import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {applyDay29V4Choice,beginDay29V4,completeDay29V4,getDay29V4Options,resolveDay29V4Contact,resolveDay29V4Evening,resolveDay29V4Future,resolveDay29V4New,resolveDay29V4Stay} from '../src/day29-v4-state-contract.mjs';
import {getDay29V4PlayableOpening} from '../src/day29-v4-playable-opening.mjs';
import {getDay29V4PlayableHaeunEvening} from '../src/day29-v4-playable-haeun-evening.mjs';
import {getDay29V4PlayableEveningBranches} from '../src/day29-v4-playable-evening-branches.mjs';
import {getDay29V4PlayableClose} from '../src/day29-v4-playable-close.mjs';
import {getDay29V4RuntimeResolution} from '../src/day29-v4-runtime-resolution.mjs';
import {validateDay29V4SourceStep} from '../src/day29-v4-source-selection.mjs';

const pick=(options,suffix)=>{const option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${suffix}:${options.map(item=>item.id).join(',')}`);return option.id;};
const choose28=(state,suffix)=>applyDay28V4Choice(state,pick(getDay28V4Options(state.storyFlags.day28V4),suffix));
const choose29=(state,suffix)=>applyDay29V4Choice(state,pick(getDay29V4Options(state.storyFlags.day29V4),suffix));
function sourced(steps){for(const step of steps)if(step.source)assert.equal(validateDay29V4SourceStep(step),true,`${step.type}:${step.text??step.prompt??''}`);}
function finish28(state,{home=false,newRoute=false}={}){while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:home,location:home?'HAEUN_HOME':'OUTSIDE'});continue;}if(phase==='new_relationship_resolution'){resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});continue;}const suffix=phase==='continuing_distance'?'talk_only':phase==='continuing_night'&&home?'together_if_mutual':phase==='new_meeting_wish'&&newRoute?'want_romance':null;choose28(state,suffix);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});beginDay29V4(state);return state;}
function throughOpening(state,eveningSuffix=null){while(!['evening_resolution','solo_evening'].includes(state.storyFlags.day29V4.phase))choose29(state, state.storyFlags.day29V4.phase==='evening'?eveningSuffix:null);if(state.storyFlags.day29V4.phase==='evening_resolution'){const cue=getDay29V4PlayableOpening(state.storyFlags.day29V4).at(-1);resolveDay29V4Evening(state,getDay29V4RuntimeResolution(state,cue));}return state;}
function toClose(state){while(state.storyFlags.day29V4.phase!=='tomorrow'){const chapter=state.storyFlags.day29V4;let steps;if(chapter.phase.startsWith('haeun_')||['future_resolution','contact_resolution','stay_resolution'].includes(chapter.phase))steps=getDay29V4PlayableHaeunEvening(chapter);else steps=getDay29V4PlayableEveningBranches(chapter);const cue=steps.find(step=>step.type?.endsWith('Cue'));if(cue){const response=getDay29V4RuntimeResolution(state,cue);if(cue.type==='day29FutureCue')resolveDay29V4Future(state,response);else if(cue.type==='day29ContactCue')resolveDay29V4Contact(state,response);else if(cue.type==='day29StayCue')resolveDay29V4Stay(state,response);else if(cue.type==='day29NewCue')resolveDay29V4New(state,response);continue;}const suffix=chapter.phase==='haeun_close'?'stay':chapter.phase==='new_evening'?'meet_again':null;choose29(state,suffix);}return state;}

test('SCENE21-24 Haeun route reaches DAY30 only after sourced final scene',()=>{const state=toClose(throughOpening(finish28(day28FriendlyFixture(),{home:true})));const seen=[];while(state.storyFlags.day29V4.phase!=='ending'){const steps=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(steps);seen.push(steps.find(step=>step.type==='sceneDirection').number);choose29(state);}const ending=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(ending);seen.push(ending.find(step=>step.type==='sceneDirection').number);assert.deepEqual(seen,[21,22,23,24]);assert.equal(state.storyFlags.day29V4.facts.day30Handoff.tomorrowRecipient,'HAEUN');assert.equal(ending.at(-1).type,'chapterCompletionCue');assert.equal(state.storyFlags.day29V4.complete,false);completeDay29V4(state,ending.at(-1));assert.equal(state.storyFlags.day29V4.complete,true);assert.equal(state.storyFlags.day29V4Day30HookPending,true);assert.equal(state.storyFlags.day28V4Day29HookPending,false);});

test('solo close skips person-addressed C23 and invents no possessions',()=>{const state=toClose(throughOpening(finish28(day28SoloFixture()))),seen=[],shown=[];while(state.storyFlags.day29V4.phase!=='ending'){const steps=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(steps);shown.push(...steps);seen.push(steps.find(step=>step.type==='sceneDirection').number);choose29(state);}const ending=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(ending);shown.push(...ending);seen.push(ending.find(step=>step.type==='sceneDirection').number);assert.deepEqual(seen,[21,22,24]);assert.equal(state.storyFlags.day29V4.facts.goodnight,null);assert.equal(state.storyFlags.day29V4.facts.day30Handoff.tomorrowRecipient,null);assert.equal(shown.some(step=>step.type==='dialogue'&&step.speaker!=='나'),false);assert.equal(shown.filter(step=>step.text).some(step=>/실제로 가진 사진·카드·꽃/.test(step.text)),false);assert.match(shown.filter(step=>step.text).map(step=>step.text).join(' '),/받지 않은 카드와 사지 않은 꽃|알람을 확인/);});

test('new relationship C23 uses only accepted Ara appointment without Haeun lines',()=>{const state=toClose(throughOpening(finish28(day28NewMeetingFixture(),{newRoute:true}))),seen=[];while(state.storyFlags.day29V4.phase!=='ending'){const steps=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(steps);seen.push(steps.find(step=>step.type==='sceneDirection').number);if(state.storyFlags.day29V4.phase==='goodnight'){assert.deepEqual(steps.find(step=>step.type==='sceneDirection').characters,['ARA']);assert.doesNotMatch(steps.filter(step=>step.text).map(step=>step.text).join(' '),/하은/);}choose29(state);}assert.deepEqual(seen,[21,22,23]);assert.equal(state.storyFlags.day29V4.facts.day30Handoff.tomorrowRecipient,'ARA');const ending=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(ending);assert.equal(ending.find(step=>step.type==='sceneDirection').number,24);});

test('Haeun NEED_TIME overrides an older accepted appointment and skips C23',()=>{const state=throughOpening(finish28(day28FriendlyFixture(),{home:true}));while(state.storyFlags.day29V4.phase!=='haeun_future')choose29(state);choose29(state,'changed');const cue=getDay29V4PlayableHaeunEvening(state.storyFlags.day29V4).at(-1),response=getDay29V4RuntimeResolution(state,cue);assert.equal(response.outcome,'NEED_TIME');resolveDay29V4Future(state,response);assert.equal(state.storyFlags.day29V4.phase,'tomorrow');choose29(state);choose29(state);assert.equal(state.storyFlags.day29V4.phase,'ending');assert.equal(state.storyFlags.day29V4.facts.day30Handoff.tomorrowRecipient,null);assert.equal(state.storyFlags.day29V4.facts.goodnight,null);const ending=getDay29V4PlayableClose(state.storyFlags.day29V4);sourced(ending);assert.doesNotMatch(ending.filter(step=>step.text).map(step=>step.text).join(' '),/내일 너무 일찍 나오지 마|기다리면서 긴장/);});
