import assert from 'node:assert/strict';
import test from 'node:test';
import {day25ContinuedFixture,day25NewMeetingFixture} from './day25-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location,resolveDay25V4NewMeeting} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,getDay26V4Options,resolveDay26V4Jihoon,resolveDay26V4NewLie,resolveDay26V4NewMeaning,resolveDay26V4NewNext} from '../src/day26-v4-state-contract.mjs';
import {getDay26V4PlayableAlternates} from '../src/day26-v4-playable-alternates.mjs';
import {validateDay26V4SourceStep} from '../src/day26-v4-source-selection.mjs';

const choose25=(state,suffix)=>{const option=getDay25V4Options(state.storyFlags.day25V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day25V4.phase}:${suffix}`);applyDay25V4Choice(state,option.id);};
function complete25(state,{friends='later',meeting='ACCEPTED'}={}){beginDay25V4(state);let guard=0;while(state.storyFlags.day25V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){const proposal=state.storyFlags.day25V4.facts.proposal;resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:proposal==='PREPARE_MARRIAGE'?'PREPARE_MARRIAGE':'REDISCUSS'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}if(phase==='new_meeting_resolution'){resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:state.storyFlags.day25V4.input.newMeeting.recipient,outcome:meeting});continue;}choose25(state,phase==='friend_meal'?friends:undefined);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});beginDay26V4(state);return state;}
const choose26=(state,suffix)=>{const option=getDay26V4Options(state.storyFlags.day26V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day26V4.phase}:${suffix}`);applyDay26V4Choice(state,option.id);};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay26V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}
const seal=input=>{let hash=2166136261;for(const char of JSON.stringify(input)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0');};

test('Jihoon meal exists only after his current response and exposes alternate C2-C3',()=>{const state=complete25(day25ContinuedFixture());choose26(state);assert.equal(state.storyFlags.day26V4.phase,'jihoon_resolution');resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:true});let steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,2);assert.match(JSON.stringify(steps),/다른 사람이 물으면 뭐라고 하면 돼/);choose26(state,'his_work');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,3);choose26(state,'later');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).nextScene,22);assert.equal(state.storyFlags.day26V4.facts.route,'JIHOON_MEAL');});

test('accepted ARA meeting renders only ARA and waits independently for intent',()=>{const state=complete25(day25NewMeetingFixture());choose26(state);let steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,4);const serialized=JSON.stringify(steps);assert.match(serialized,/아라/);assert.doesNotMatch(serialized,/예전에 이거 좋아했|오늘도 일한 것/);choose26(state,'good_today');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,5);choose26(state,'romance');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).type,'newMeetingIntentCue');assert.equal(state.storyFlags.day26V4.facts.newMeaningResponse,null);resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'ARA',outcome:'NEED_TIME'});assert.equal(state.storyFlags.day26V4.phase,'new_close');});

test('next meeting is not scheduled until the same recipient accepts',()=>{const state=complete25(day25NewMeetingFixture());choose26(state);choose26(state);choose26(state,'slow');resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'ARA',outcome:'RECIPROCATE'});let steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,7);choose26(state,'meet_again');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).type,'newMeetingNextCue');assert.equal(state.storyFlags.day26V4.facts.newNextResponse,null);resolveDay26V4NewNext(state,{type:'newMeetingNextResponse',recipient:'ARA',outcome:'DECLINED'});steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,8);assert.match(JSON.stringify(steps),/수락하지 않은 약속을 만들지 않았다/);choose26(state,'rest');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).nextScene,23);});

test('a meeting without a matching lie never invents SCENE19 or C6',()=>{const state=complete25(day25NewMeetingFixture());choose26(state);choose26(state);choose26(state);resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'ARA',outcome:'DISTANCE'});const steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,7);assert.equal(steps.some(step=>step.type==='choice'&&step.choiceNumber===6),false);assert.doesNotMatch(JSON.stringify(steps),/지난번에 혼자라고 한 건/);});

test('matching prior lie waits for the recipient response and END_TODAY skips C7',()=>{const state=complete25(day25NewMeetingFixture()),chapter=state.storyFlags.day26V4;chapter.input.relationshipStatusLie={recipient:'ARA',statement:'SINGLE',truth:'RELATIONSHIP_NOT_ENDED',corrected:false};chapter.inputSeal=seal(chapter.input);choose26(state);choose26(state);choose26(state);resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'ARA',outcome:'NEED_TIME'});let steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,6);choose26(state,'correct');steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).type,'newMeetingTruthCue');assert.equal(state.storyFlags.day26V4.facts.newLieResponse,null);resolveDay26V4NewLie(state,{type:'newMeetingTruthResponse',recipient:'ARA',outcome:'END_TODAY'});steps=getDay26V4PlayableAlternates(state.storyFlags.day26V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,8);assert.equal(steps.some(step=>step.type==='choice'&&step.choiceNumber===7),false);assert.match(JSON.stringify(steps),/제가 생각한 만남이랑 다르네요/);});
