import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {getDay28V4PlayableEnding} from '../src/day28-v4-playable-ending.mjs';
import {validateDay28V4SourceStep} from '../src/day28-v4-source-selection.mjs';

const choose=(state,suffix)=>{const options=getDay28V4Options(state.storyFlags.day28V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day28V4.phase}:${suffix}`);applyDay28V4Choice(state,option.id);};
const seal=input=>{let hash=2166136261;for(const char of JSON.stringify(input)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0');};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction','storyActionCue'].includes(step.type))assert.equal(validateDay28V4SourceStep(step),true,`${step.type}:${step.text??step.description??step.actionLabel}`);}

test('SCENE20-24 solo route has seven choices, no person response, and a DAY29 handoff',()=>{const state=day28SoloFixture();choose(state);const seen=[];while(state.storyFlags.day28V4.phase!=='ending'){const steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered);seen.push(offered.choiceNumber);choose(state);}const ending=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(ending);assert.deepEqual(seen,[2,3,4,5,6,7,8]);assert.doesNotMatch(JSON.stringify(ending),/speaker|girlfriend/);assert.equal(ending.at(-1).type,'chapterCompletionCue');completeDay28V4(state,ending.at(-1));assert.equal(state.storyFlags.day28V4.complete,true);assert.equal(state.storyFlags.day28V4Day29HookPending,true);assert.equal(state.storyFlags.day27V4Day28HookPending,false);});

test('SCENE17-18 uses only the actual new person and waits for a new relationship response',()=>{const state=day28NewMeetingFixture();assert.equal(state.storyFlags.day28V4.input.newMeetingEligible,true);choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'ARA',outcome:'ACCEPTED',method:'IN_PERSON'});let steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.match(JSON.stringify(steps),/아라/);assert.doesNotMatch(JSON.stringify(steps),/유리|서진|하은/);choose(state,'want_romance');steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'day28NewRelationshipCue');resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'NEED_TIME'});assert.equal(state.storyFlags.day28V4.phase,'ending');assert.equal(state.storyFlags.day28V4.facts.relationshipState,'SINGLE');assert.equal(state.storyFlags.day28V4.facts.day29Handoff.newRelationship,null);});

test('SCENE22 appears only for continuing contact and completes without fabricating a visit',()=>{const state=day28FriendlyFixture();choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});for(let number=2;number<=8;number++)choose(state);resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});choose(state);choose(state,'talk_only');choose(state);resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});choose(state);assert.equal(state.storyFlags.day28V4.phase,'continuing_night');let steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,16);assert.equal(state.storyFlags.day28V4.facts.homeInvitationResponse,'DECLINED');choose(state,'own_work_first');steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.equal(steps.at(-1).handoff.homeInvitation,null);});

test('SCENE20-21 turns each solo selection into an experienced action or first-person thought',()=>{const state=day28SoloFixture();choose(state);const rendered=[];while(state.storyFlags.day28V4.phase!=='ending'){const steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);rendered.push(...steps);choose(state);}rendered.push(...getDay28V4PlayableEnding(state.storyFlags.day28V4));const text=JSON.stringify(rendered);assert.match(text,/휴대전화를 열었다가 다시 닫았다/);assert.match(text,/short-walk-home/);assert.match(text,/조금 슬퍼도 오늘을 살 수 있다고/);assert.match(text,/familiar-meal/);assert.match(text,/wash-cup/);assert.match(text,/prepare-clothes/);assert.match(text,/오늘 들은 답을 내게 편한 말로 고치지 않고/);assert.doesNotMatch(text,/DAY 28|플래그|다음 DAY/);});

test('SCENE21 simple-new meal branch keeps the complete original source line',()=>{const state=day28SoloFixture();choose(state);choose(state,'own_task');choose(state,'keep_words');choose(state,'simple_new');const steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);const meal=steps.find(step=>step.actionLabel==='오늘 가능한 간단한 음식을 골라 한 끼를 차린다.');assert.equal(meal?.source?.exact,'남은 것이 있으면 먹을 수 있는지 보고 먹었다. 없으면 오늘 가능한 한 끼를 골랐다.');});

test('SCENE20 wait-contact branch keeps the complete original source line',()=>{const state=day28SoloFixture();choose(state);choose(state,'ask_jihoon');choose(state,'wait_contact');const steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps[0].source.exact,'마음이 좋아지는 말을 외운다고 바로 좋아지지는 않았다. 그래도 그 마음으로 상대에게 계속 연락하는 행동을 하지 않을 수는 있었다.');});

test('SCENE17-24 gives the actual new person full dialogue, a private scope response and a non-Haeun night',()=>{const state=day28NewMeetingFixture(),chapter=state.storyFlags.day28V4;chapter.input.jihoonAvailable=true;chapter.inputSeal=seal(chapter.input);choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'ARA',outcome:'ACCEPTED',method:'IN_PERSON'});let steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);let text=JSON.stringify(steps);assert.match(text,/보는 것까지 다 일로 만들고 싶지 않을 때요|좋았는데 안 찍기도 하고요|그럼 제가 본 게 되잖아요/);assert.doesNotMatch(text,/유리|서진|하은/);choose(state,'want_romance');resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,15);choose(state,'private');steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);text=JSON.stringify(steps);assert.match(text,/오늘은 자세히 말하지 않을게|나중에 말하고 싶을 때/);assert.match(text,/아라.*내일은 제 할 일을 먼저 하고/);assert.equal(steps.at(-1).prompt,'내일을 나누는 방법');assert.doesNotMatch(JSON.stringify(steps.map(({source,...step})=>step)),/하은|의자|옷을 정리/);choose(state,'own_work_first');steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);text=JSON.stringify(steps);assert.match(text,/아라.*할 일부터 하고 연락해요/);assert.match(text,/자기 하루를 가진 사람|lights-off|오늘 들은 말만큼 달라진 거리/);assert.doesNotMatch(JSON.stringify(steps.map(({source,...step})=>step)),/하은|우리가 한 말은 이미 있잖아|플래그|다음 DAY/);});
