import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,completeDay28V4,getDay28V4Options,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {getDay28V4PlayableEnding} from '../src/day28-v4-playable-ending.mjs';
import {validateDay28V4SourceStep} from '../src/day28-v4-source-selection.mjs';

const choose=(state,suffix)=>{const options=getDay28V4Options(state.storyFlags.day28V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day28V4.phase}:${suffix}`);applyDay28V4Choice(state,option.id);};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction','storyActionCue'].includes(step.type))assert.equal(validateDay28V4SourceStep(step),true,`${step.type}:${step.text??step.description??step.actionLabel}`);}

test('SCENE20-24 solo route has seven choices, no person response, and a DAY29 handoff',()=>{const state=day28SoloFixture();choose(state);const seen=[];while(state.storyFlags.day28V4.phase!=='ending'){const steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered);seen.push(offered.choiceNumber);choose(state);}const ending=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(ending);assert.deepEqual(seen,[2,3,4,5,6,7,8]);assert.doesNotMatch(JSON.stringify(ending),/speaker|girlfriend/);assert.equal(ending.at(-1).type,'chapterCompletionCue');completeDay28V4(state,ending.at(-1));assert.equal(state.storyFlags.day28V4.complete,true);assert.equal(state.storyFlags.day28V4Day29HookPending,true);assert.equal(state.storyFlags.day27V4Day28HookPending,false);});

test('SCENE17-18 uses only the actual new person and waits for a new relationship response',()=>{const state=day28NewMeetingFixture();assert.equal(state.storyFlags.day28V4.input.newMeetingEligible,true);choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'ARA',outcome:'ACCEPTED',method:'IN_PERSON'});let steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.match(JSON.stringify(steps),/아라/);assert.doesNotMatch(JSON.stringify(steps),/유리|서진|하은/);choose(state,'want_romance');steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'day28NewRelationshipCue');resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'NEED_TIME'});assert.equal(state.storyFlags.day28V4.phase,'ending');assert.equal(state.storyFlags.day28V4.facts.relationshipState,'SINGLE');assert.equal(state.storyFlags.day28V4.facts.day29Handoff.newRelationship,null);});

test('SCENE22 appears only for continuing contact and completes without fabricating a visit',()=>{const state=day28FriendlyFixture();choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});for(let number=2;number<=8;number++)choose(state);resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});choose(state);choose(state,'talk_only');choose(state);resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});choose(state);assert.equal(state.storyFlags.day28V4.phase,'continuing_night');let steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,16);assert.equal(state.storyFlags.day28V4.facts.homeInvitationResponse,'DECLINED');choose(state,'own_work_first');steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.equal(steps.at(-1).handoff.homeInvitation,null);});

test('SCENE20-21 turns each solo selection into an experienced action or first-person thought',()=>{const state=day28SoloFixture();choose(state);const rendered=[];while(state.storyFlags.day28V4.phase!=='ending'){const steps=getDay28V4PlayableEnding(state.storyFlags.day28V4);sourced(steps);rendered.push(...steps);choose(state);}rendered.push(...getDay28V4PlayableEnding(state.storyFlags.day28V4));const text=JSON.stringify(rendered);assert.match(text,/휴대전화를 열었다가 다시 닫았다/);assert.match(text,/short-walk-home/);assert.match(text,/조금 슬퍼도 오늘을 살 수 있다고/);assert.match(text,/familiar-meal/);assert.match(text,/wash-cup/);assert.match(text,/prepare-clothes/);assert.match(text,/오늘 들은 답을 내게 편한 말로 고치지 않고/);assert.doesNotMatch(text,/DAY 28|플래그|다음 DAY/);});
