import assert from 'node:assert/strict';
import test from 'node:test';
import {day27EndedFixture,day27FriendlyFixture,day27MixedFixture,day27PublicCorrectionFixture} from './day27-v4-playable-fixture.mjs';
import {applyDay27V4Choice,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4Jihoon,resolveDay27V4NextTalk,resolveDay27V4Relationship,resolveDay27V4TruthRecipient} from '../src/day27-v4-state-contract.mjs';
import {getDay27V4PlayableEnding} from '../src/day27-v4-playable-ending.mjs';
import {validateDay27V4SourceStep} from '../src/day27-v4-source-selection.mjs';

const choose=(state,suffix)=>{const option=getDay27V4Options(state.storyFlags.day27V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option,`${state.storyFlags.day27V4.phase}:${suffix}`);applyDay27V4Choice(state,option.id);};
const enterHonest=state=>{choose(state);resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'HAEUN',outcome:'ACCEPTED',method:'CALL'});choose(state);choose(state);choose(state);choose(state);choose(state);resolveDay27V4Relationship(state,{type:'day27RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay27V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}

test('SCENE18-24 waits for Jihoon and next-talk responses and completes the honest continuing route',()=>{const state=day27FriendlyFixture();enterHonest(state);let steps=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).type,'day27JihoonCue');assert.doesNotMatch(JSON.stringify(steps),/지금은 잠깐/);resolveDay27V4Jihoon(state,{type:'day27JihoonResponse',available:false});steps=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.find(step=>step.type==='choice').choiceNumber,14);choose(state);steps=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(steps);assert.match(JSON.stringify(steps),/피곤하고, 내일은 네가 보고 싶어/);choose(state);choose(state,'short_meeting');steps=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).type,'day27NextTalkCue');resolveDay27V4NextTalk(state,{type:'day27NextTalkResponse',outcome:'ACCEPTED'});steps=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(steps);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.equal(steps.at(-1).finalSceneReached,true);});

test('SCENE23 no-conversation route exposes exactly alternate C3-C8 and no unheard response',()=>{const state=day27EndedFixture(),seen=[];choose(state);while(state.storyFlags.day27V4.phase!=='ending'){const steps=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered);seen.push(offered.choiceNumber);assert.doesNotMatch(JSON.stringify(steps),/speaker|message/);choose(state);}const ending=getDay27V4PlayableEnding(state.storyFlags.day27V4);sourced(ending);assert.deepEqual(seen,[3,4,5,6,7,8]);assert.equal(ending.at(-1).type,'chapterCompletionCue');assert.equal(state.storyFlags.day27V4.facts.conversationOutcome,null);});

test('night affection is blocked when truth was not disclosed and unperformed correction cannot be reported complete',()=>{const state=day27FriendlyFixture();enterHonest(state);resolveDay27V4Jihoon(state,{type:'day27JihoonResponse',available:false});choose(state);assert.equal(state.storyFlags.day27V4.phase,'continuing_night');const mixed=day27MixedFixture();choose(mixed);resolveDay27V4Conversation(mixed,{type:'day27ConversationResponse',target:'SEOJIN',outcome:'ACCEPTED',method:'CALL'});choose(mixed);choose(mixed);resolveDay27V4TruthRecipient(mixed,{type:'day27TruthRecipientResponse',recipient:'SEOJIN',outcome:'END_TODAY'});choose(mixed);assert.equal(mixed.storyFlags.day27V4.phase,'separation_night');assert.doesNotMatch(JSON.stringify(getDay27V4PlayableEnding(mixed.storyFlags.day27V4)),/피곤하고, 내일은 네가 보고 싶어/);const publicState=day27PublicCorrectionFixture();choose(publicState);resolveDay27V4Conversation(publicState,{type:'day27ConversationResponse',target:'HAEUN',outcome:'ACCEPTED',method:'CALL'});choose(publicState);choose(publicState);choose(publicState);choose(publicState);assert.equal(publicState.storyFlags.day27V4.phase,'public_correction');assert.equal(getDay27V4Options(publicState.storyFlags.day27V4).some(option=>option.id.endsWith('_report_actual')),false);});
