import assert from 'node:assert/strict';
import test from 'node:test';
import {applyDay21V4GameChoice,applyDay21V4GameResolution,completeDay21V4GameChapter,getDay21V4GameSegment} from '../src/day21-v4-game-bridge.mjs';
import {getDay21V4Options} from '../src/day21-v4-state-contract.mjs';
import {getDay21V4RuntimeResolution} from '../src/day21-v4-runtime-resolution.mjs';
import {day21State} from './day21-v4-fixture.mjs';

const configs=Object.freeze({
  friendly_busan:{venue:'park',contact:'hug',dinner:'travel',travel:'busan',lodging:'shared',quote:true},
  neutral_park:{venue:'park',contact:'distance',dinner:'nearby'},
  mixed_phone_seoul:{venue:'phone',contact:'hug',dinner:'travel',travel:'seoul',lodging:'daytrip'},
  distant_deferred:{deferred:true},
  rest_separately:{venue:'park',contact:'distance',dinner:'travel',travel:'rest',lodging:'separate'}
});
const suffix={venue:{park:'_park',phone:'_phone'},contact:{hug:'_hug',distance:'_walk_apart'},dinner:{nearby:'_eat_nearby',travel:'_talk_travel'},travel:{busan:'_busan',seoul:'_seoul',rest:'_rest_separately'},lodging:{shared:'_shared_room_wish',daytrip:'_day_trip',separate:'_separate_spaces'}};

function play(name){const c=configs[name],base=c.deferred?day21State({relationshipActive:false,contactAllowed:false,relationshipTone:'DIFFICULT',morningMode:'SOLO_MORNING',day20VisitMode:'SOLO',day20StayedOver:false}):day21State({morningMode:name.includes('phone')?'MESSAGE_MORNING':'STAYED_MORNING',day20StayedOver:!name.includes('phone')}),s={day:21,money:200000,economyLedger:[],storyHistory:[],pendingStoryId:'m30-day21-current-full-workday',...base};if(c.quote)s.storyFlags.day21V4TravelQuote={quoteId:'qa-busan',playerCost:60000,dateConfirmed:true,transportConfirmed:true,budgetConfirmed:true,lodgingConfirmed:true,mutualConsent:true};const steps=[...getDay21V4GameSegment(s)];let guard=0;while(s.storyFlags.day21V4.phase!=='ending'){assert.ok(guard++<30,`${name}:loop`);const chapter=s.storyFlags.day21V4,segment=getDay21V4GameSegment(s),cue=segment.find(step=>['contactConsentCue','lodgingConsentCue','travelConfirmationCue'].includes(step.type));if(cue){const packet=applyDay21V4GameResolution(s,getDay21V4RuntimeResolution(s,cue));steps.push(...packet.steps);continue;}const options=getDay21V4Options(chapter);let selected=options[0];for(const [phase,key] of [['venue','venue'],['contact','contact'],['dinner','dinner'],['travel','travel'],['lodging','lodging']])if(chapter.phase===phase&&c[key])selected=options.find(option=>option.id.endsWith(suffix[key][c[key]]));assert.ok(selected,`${name}:${chapter.phase}`);steps.push(...applyDay21V4GameChoice(s,selected.id).steps);}const final=getDay21V4GameSegment(s);steps.push(...final);completeDay21V4GameChapter(s,final.at(-1));return {s,steps};}

for(const name of Object.keys(configs))test(`DAY21 ${name} bridge route keeps its own facts`,()=>{const {s,steps}=play(name),chapter=s.storyFlags.day21V4,scenes=new Set(steps.filter(step=>step.type==='transition').map(step=>step.sceneNumber));assert.equal(chapter.complete,true);assert.equal(steps.some(step=>/Boundary$/.test(step.type)),false);assert.equal(s.storyHistory.length,1);assert.equal(s.storyFlags.day21V4Day22HookPending,true);if(name==='friendly_busan'){assert.equal(chapter.facts.bookingConfirmed,true);assert.equal(chapter.facts.todayContact,'HUG');assert.equal(chapter.facts.lodgingAgreement,'SHARED_ROOM_AGREED');assert.equal(s.money,140000);assert.ok(scenes.has(20)&&scenes.has(22));}if(name==='neutral_park'){assert.equal(chapter.facts.travelDiscussion,false);assert.equal(chapter.facts.todayContact,'NONE');assert.equal(s.economyLedger.length,0);}if(name==='mixed_phone_seoul'){assert.equal(chapter.facts.conversationMode,'PHONE');assert.equal(chapter.facts.todayContact,'NONE');assert.equal(chapter.facts.travelResult,'SEOUL_DAY');assert.equal(steps.filter(step=>step.type==='transition').some(step=>step.characterId==='girlfriend'),false);assert.equal(s.economyLedger.length,0);}if(name==='distant_deferred'){assert.equal(chapter.facts.heardHaeunStory,false);assert.equal(steps.some(step=>step.type==='message'||step.characterId==='girlfriend'),false);assert.equal(scenes.has(5),false);assert.equal(scenes.has(21),true);}if(name==='rest_separately'){assert.equal(chapter.facts.travelResult,'REST_SEPARATELY');assert.equal(chapter.facts.bookingConfirmed,false);assert.equal(s.economyLedger.length,0);}});
