import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {createInitialState} from '../src/game-core.mjs';
import {createGirlfriendFromProfile} from '../src/girlfriend-manager.mjs';
import {GAME_MODES} from '../src/scenario-state.mjs';
import {SaveManager} from '../src/save-manager.mjs';
import {day25ContinuedFixture,day25NewMeetingFixture} from './day25-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location,resolveDay25V4NewMeeting} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4GameChoice,applyDay26V4GameResolution,completeDay26V4GameChapter,getDay26V4GameCompatibility,getDay26V4GameResumePresentation,getDay26V4GameSegment,isDay26V4ResolutionStep,prepareDay26V4GameEntry} from '../src/day26-v4-game-bridge.mjs';
import {getDay26V4RuntimeResolution} from '../src/day26-v4-runtime-resolution.mjs';
import {getDay26V4Options} from '../src/day26-v4-state-contract.mjs';

const choose25=(state,suffix)=>{const option=getDay25V4Options(state.storyFlags.day25V4).find(item=>!suffix||item.id.endsWith(`_${suffix}`));assert.ok(option);applyDay25V4Choice(state,option.id);};
function fixture(state,{friends='meet',meeting='ACCEPTED'}={}){beginDay25V4(state);let guard=0;while(state.storyFlags.day25V4.phase!=='ending'){assert.ok(guard++<50);const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}if(phase==='new_meeting_resolution'){resolveDay25V4NewMeeting(state,{type:'newMeetingResponse',recipient:state.storyFlags.day25V4.input.newMeeting.recipient,outcome:meeting});continue;}choose25(state,phase==='friend_meal'?friends:undefined);}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});return state;}
const choose=(state,index=0)=>applyDay26V4GameChoice(state,getDay26V4Options(state.storyFlags.day26V4)[index].id);
function finish(state){const all=[];let guard=0;while(state.storyFlags.day26V4.phase!=='ending'){assert.ok(guard++<50,state.storyFlags.day26V4.phase);const steps=getDay26V4GameSegment(state);all.push(...steps);const cue=steps.find(isDay26V4ResolutionStep);if(cue)applyDay26V4GameResolution(state,getDay26V4RuntimeResolution(state,cue));else choose(state);}all.push(...getDay26V4GameSegment(state));return all;}
const storage=()=>{const data=new Map();return {setItem:(key,value)=>data.set(key,value),getItem:key=>data.get(key)??null,removeItem:key=>data.delete(key)};};

test('bridge starts only from verified DAY25 V4 and preserves legacy DAY26',()=>{const state=fixture(day25ContinuedFixture());assert.equal(getDay26V4GameCompatibility(state).mode,'V4_NEW');assert.equal(prepareDay26V4GameEntry(state).mode,'V4');assert.equal(getDay26V4GameSegment(state).at(-1).choiceNumber,1);const legacy={storyFlags:{day25RuntimeComplete:true,day26RuntimeStage:1}};assert.equal(getDay26V4GameCompatibility(legacy).mode,'LEGACY');});

test('group route stitches SCENE01-24 with C13 and one meal charge',()=>{const state=fixture(day25ContinuedFixture());state.storyHistory=[];prepareDay26V4GameEntry(state);const before=state.money,all=finish(state);for(const number of [1,2,6,10,14,22,23,24])assert.ok(all.some(step=>step.type==='transition'&&step.sceneNumber===number),`scene ${number}`);assert.equal(all.some(step=>step.type==='transition'&&[15,16,21].includes(step.sceneNumber)),false);assert.equal(state.money,before-24000);assert.equal(state.economyLedger.filter(entry=>entry.day===26&&entry.category==='food').length,1);assert.equal(state.storyFlags.day26V4MealSettlement.route,'GROUP_MEAL');for(const step of all.filter(step=>step.type==='transition')){assert.ok(step.backgroundUrl);assert.ok(step.storyClock);}});

test('rescheduled meeting produces solo day without a meal transaction',()=>{const state=fixture(day25NewMeetingFixture(),{meeting:'RESCHEDULED'});prepareDay26V4GameEntry(state);const before=state.money,all=finish(state);assert.ok(all.some(step=>step.type==='transition'&&step.sceneNumber===21));assert.equal(all.some(step=>step.type==='transition'&&[2,15,16,22].includes(step.sceneNumber)),false);assert.equal(state.money,before);assert.equal(state.storyFlags.day26V4MealSettlement,undefined);});

test('choice and resolution failures atomically restore chapter and economy',()=>{const state=fixture(day25ContinuedFixture());prepareDay26V4GameEntry(state);choose(state);const before={chapter:structuredClone(state.storyFlags.day26V4),money:state.money,ledger:structuredClone(state.economyLedger),meal:structuredClone(state.storyFlags.day26V4MealSettlement)};assert.throws(()=>applyDay26V4GameResolution(state,{type:'newMeetingNextResponse',recipient:'ARA',outcome:'ACCEPTED'}),/INVALID_NEW_NEXT|UNKNOWN_RESOLUTION/);assert.deepEqual({chapter:state.storyFlags.day26V4,money:state.money,ledger:state.economyLedger,meal:state.storyFlags.day26V4MealSettlement},before);});

test('mid-day save round-trip preserves exact segment and presentation',()=>{const state=fixture(day25ContinuedFixture());prepareDay26V4GameEntry(state);for(let i=0;i<7;i++){const steps=getDay26V4GameSegment(state),cue=steps.find(isDay26V4ResolutionStep);if(cue)applyDay26V4GameResolution(state,getDay26V4RuntimeResolution(state,cue));else choose(state);}const expected=getDay26V4GameSegment(state),store=storage(),shell=createInitialState(createGirlfriendFromProfile('haeun',()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});Object.assign(shell,state);SaveManager.save(shell,store);const loaded=SaveManager.load(store,GAME_MODES.MARRIAGE_30);assert.deepEqual(loaded.storyFlags.day26V4,state.storyFlags.day26V4);assert.deepEqual(getDay26V4GameSegment(loaded),expected);assert.deepEqual(getDay26V4GameResumePresentation(loaded),getDay26V4GameResumePresentation(state));});

test('completion records one DAY26 history and opens only DAY27 hook',()=>{const state=fixture(day25ContinuedFixture());state.storyHistory=[];prepareDay26V4GameEntry(state);const cue=finish(state).at(-1);completeDay26V4GameChapter(state,cue);completeDay26V4GameChapter(state,cue);assert.equal(state.storyHistory.length,1);assert.equal(state.storyHistory[0].scenarioId,'day26-notion-v4');assert.equal(state.storyFlags.day26V4.complete,true);assert.equal(state.storyFlags.day26V4Day27HookPending,true);assert.equal(state.storyFlags.day26RuntimeComplete,true);assert.equal(state.storyFlags.day26FreeActionComplete,undefined);});

test('main game wires DAY26 V4 entry, choices, resolutions, completion, and cache version',()=>{const source=readFileSync(new URL('../game.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(source,/day26-v4-game-bridge\.mjs\?v=3/);assert.match(source,/day26-v4-runtime-resolution\.mjs\?v=1/);assert.match(source,/if\(day26V4\)prepareDay26V4GameEntry\(state\)/);assert.match(source,/applyDay26V4GameChoice\(currentState,id\)/);assert.match(source,/getDay26V4RuntimeResolution\(state,step\)/);assert.match(source,/applyDay26V4GameResolution\(state,response\)/);assert.match(source,/completionCue\.day===26\)completeDay26V4GameChapter/);assert.match(source,/isDay26V4ResolutionStep\(step\)/);assert.match(source,/lockedDay26&&!day26V4\?26/);assert.match(source,/completedSession\?\.id===LOCKED_DAY26_SCENE_ID&&!state\.storyFlags\?\.day26V4/);assert.match(source,/!\(lockedDay26&&day26V4\)/);assert.match(html,/game\.js\?v=(?:27[7-9]|2[89]\d|[3-9]\d{2}|[1-9]\d{3,})/);});
