import assert from 'node:assert/strict';
import test from 'node:test';
import {beginDay18V4,applyDay18V4Choice,completeDay18V4} from '../src/day18-v4-state-contract.mjs';
import {beginDay19V4,applyDay19V4Choice,completeDay19V4,getDay19V4Options} from '../src/day19-v4-state-contract.mjs';
import {applyDay20V4Choice,beginDay20V4,getDay20V4Options,resolveDay20V4Stay} from '../src/day20-v4-state-contract.mjs';
import {getDay20V4PlayableEnding} from '../src/day20-v4-playable-ending.mjs';
import {validateDay20V4SourceStep} from '../src/day20-v4-source-selection.mjs';

function state(){const s={breakup:null,ended:false,money:42000,storyFlags:{day17V4Completed:true,day17V4Day18HookPending:true,day17V4TomorrowPlan:'HAEUN',day17V4Choice9:'day17_v4_life_haeun',day17V4DinnerAgreement:{day:18,partner:'HAEUN',status:'ACCEPTED',sourceChoiceId:'day17_v4_life_haeun'},day16V4YuriEncountered:false,day16V4YuriContact:'ENDED_HERE',day16V4YuriInvitation:'NONE'}};beginDay18V4(s,{});for(const key of['morning_keep','disclose_together','menu_each','topic_good','close_home','night_good','calm_trip','travel_near'])applyDay18V4Choice(s,`day18_v4_${key}`);completeDay18V4(s,{type:'chapterCompletionCue',day:18,finalSceneReached:true});beginDay19V4(s);while(s.storyFlags.day19V4.phase!=='ending'){const opts=getDay19V4Options(s.storyFlags.day19V4),i=s.storyFlags.day19V4.phase==='dinner'?2:s.storyFlags.day19V4.phase==='tomorrow_table'?0:0;applyDay19V4Choice(s,opts[i].id);}completeDay19V4(s,{type:'chapterCompletionCue',day:19,finalSceneReached:true});beginDay20V4(s);return s;}
const choose=(s,index=0)=>applyDay20V4Choice(s,getDay20V4Options(s.storyFlags.day20V4)[index].id);
const sourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay20V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);};
function reachNightEnd(s){while(s.storyFlags.day20V4.phase!=='night_end'){if(s.storyFlags.day20V4.phase==='closeness')choose(s,2);else choose(s,0);}}

test('conflict ending uses SCENE 19, 21 and 24 without intimacy or stay',()=>{const s=state();s.storyFlags.day20V4.input.day18DiscussionPending=true;while(s.storyFlags.day20V4.phase!=='dinner')choose(s);choose(s,2);let steps=getDay20V4PlayableEnding(s.storyFlags.day20V4);assert.equal(steps[0].number,19);assert.equal(steps.at(-1).choiceNumber,10);sourced(steps);choose(s,2);steps=getDay20V4PlayableEnding(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===21));assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===24));assert.equal(steps.some(step=>step.type==='sceneDirection'&&step.number===22),false);assert.equal(s.storyFlags.day20V4.facts.firstHug,false);assert.equal(s.storyFlags.day20V4.facts.stayedOver,false);assert.equal(steps.at(-1).type,'chapterCompletionCue');sourced(steps);});

test('ordinary leave ends through SCENE 21 and never creates a farewell hug',()=>{const s=state();reachNightEnd(s);let steps=getDay20V4PlayableEnding(s.storyFlags.day20V4);assert.equal(steps[0].number,20);assert.equal(steps.at(-1).choiceNumber,13);sourced(steps);choose(s,0);steps=getDay20V4PlayableEnding(s.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===21));assert.equal(steps.some(step=>step.status==='first-hug'),false);assert.equal(steps.at(-1).type,'chapterCompletionCue');sourced(steps);});

test('stay offer waits for response and only accepted prepared stay reaches SCENE 22',()=>{const declined=state();reachNightEnd(declined);choose(declined,2);let steps=getDay20V4PlayableEnding(declined.storyFlags.day20V4);assert.equal(steps.at(-1).type,'haeunStayResolution');assert.equal(declined.storyFlags.day20V4.facts.stayedOver,false);sourced(steps);resolveDay20V4Stay(declined,{type:'haeunStayResponse',accepted:false});steps=getDay20V4PlayableEnding(declined.storyFlags.day20V4);assert.equal(steps.some(step=>step.type==='sceneDirection'&&step.number===22),false);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===21));sourced(steps);
  const accepted=state();reachNightEnd(accepted);choose(accepted,2);resolveDay20V4Stay(accepted,{type:'haeunStayResponse',accepted:true,prepared:true,sleepingPlan:'SEPARATE_BEDDING'});steps=getDay20V4PlayableEnding(accepted.storyFlags.day20V4);assert.equal(steps[0].number,22);assert.equal(steps.at(-1).choiceNumber,14);sourced(steps);choose(accepted,1);steps=getDay20V4PlayableEnding(accepted.storyFlags.day20V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===24));assert.equal(steps.some(step=>step.type==='sceneDirection'&&step.number===21),false);assert.equal(accepted.storyFlags.day20V4.facts.stayedOver,true);assert.equal(steps.at(-1).type,'chapterCompletionCue');sourced(steps);});
