import assert from 'node:assert/strict';
import test from 'node:test';
import {applyDay25V4Choice,beginDay25V4,getDay25V4Options,resolveDay25V4Friends,resolveDay25V4Future} from '../src/day25-v4-state-contract.mjs';
import {getDay25V4PlayableEnding} from '../src/day25-v4-playable-ending.mjs';
import {validateDay25V4SourceStep} from '../src/day25-v4-source-selection.mjs';
import {day25ContinuedFixture,day25EndedFixture} from './day25-v4-playable-fixture.mjs';

const choose=(state,suffix)=>{const options=getDay25V4Options(state.storyFlags.day25V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`${state.storyFlags.day25V4.phase}:${suffix}`);applyDay25V4Choice(state,selected.id);};
const sourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay25V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);};
function continued(){const state=day25ContinuedFixture();beginDay25V4(state);for(let i=0;i<9;i++)choose(state);choose(state,'prepare');resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});choose(state,'goodbye');assert.equal(state.storyFlags.day25V4.phase,'social_scope');return state;}
function solo(){const state=day25EndedFixture();beginDay25V4(state);for(let i=0;i<6;i++)choose(state);assert.equal(state.storyFlags.day25V4.phase,'social_scope');return state;}

test('C14-C16 schedules four-person meal only after both friends answer available',()=>{const state=continued();let steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,14);choose(state,'shared_name');steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,15);choose(state,'meet');steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).type,'friendAvailabilityCue');assert.equal(state.storyFlags.day25V4.facts.friendMealScheduled,false);resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,16);assert.equal(state.storyFlags.day25V4.facts.friendMealScheduled,true);assert.match(JSON.stringify(steps),/네 사람의 식사 시간을 정했다/);choose(state,'undecided');steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.equal(steps.at(-1).nextDay,26);assert.doesNotMatch(JSON.stringify(steps),/날짜나 식장까지 정했다/);});

test('one unavailable friend prevents a fabricated gathering',()=>{const state=continued();choose(state,'keep_private');choose(state,'meet');resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:false});const steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(state.storyFlags.day25V4.facts.friendMealScheduled,false);assert.match(JSON.stringify(steps),/모임을 만들지 않았다/);assert.equal(steps.at(-1).choiceNumber,16);});

test('ended route skips Haeun and four-person meal while retaining C14 and adapted C16',()=>{const state=solo();let steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,14);choose(state,'own_worry');steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.some(step=>step.number===21),false);assert.equal(steps.at(-1).choiceNumber,16);assert.doesNotMatch(JSON.stringify(steps),/speaker":"하은|네 사람의 식사/);choose(state,'meal_only');steps=getDay25V4PlayableEnding(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.match(JSON.stringify(steps),/새 사람이 나를 좋아한다고 말해 줘야만/);assert.doesNotMatch(JSON.stringify(steps),/짧은 입맞춤/);});
