import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,getDay28V4Options,resolveDay28V4Meeting,resolveDay28V4Relationship,validateDay28V4} from '../src/day28-v4-state-contract.mjs';
import {getDay28V4PlayableOpening} from '../src/day28-v4-playable-opening.mjs';
import {validateDay28V4SourceStep} from '../src/day28-v4-source-selection.mjs';

const choose=(state,suffix)=>{const options=getDay28V4Options(state.storyFlags.day28V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day28V4.phase}:${suffix}`);applyDay28V4Choice(state,option.id);};
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction','storyActionCue'].includes(step.type))assert.equal(validateDay28V4SourceStep(step),true,`${step.type}:${step.text??step.description??step.actionLabel}`);}

test('SCENE01 waits for a current meeting response and a solo history renders no Haeun',()=>{const state=day28FriendlyFixture();let steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,1);choose(state);steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'day28MeetingCue');assert.doesNotMatch(JSON.stringify(steps),/speaker|characterId/);const solo=day28SoloFixture();choose(solo);steps=getDay28V4PlayableOpening(solo.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).nextScene,20);assert.doesNotMatch(JSON.stringify(steps),/하은|girlfriend/);});

test('SCENE02-08 exposes exact-backed C2-C8 only after Haeun accepts',()=>{const state=day28FriendlyFixture(),seen=[];choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});let guard=0;while(state.storyFlags.day28V4.phase!=='relationship_resolution'){assert.ok(guard++<12);const steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered);seen.push(offered.choiceNumber);choose(state);}const final=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(final);assert.equal(final.at(-1).type,'day28RelationshipCue');assert.deepEqual(seen,[2,3,4,5,6,7,8]);assert.equal(validateDay28V4(state.storyFlags.day28V4),true);resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});assert.equal(getDay28V4PlayableOpening(state.storyFlags.day28V4).at(-1).nextScene,11);});

test('a deferred meeting skips every Haeun scene and cannot claim relationship restoration',()=>{const state=day28FriendlyFixture();choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'HAEUN',outcome:'DEFERRED',method:'CALL'});const steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).nextScene,20);assert.equal(state.storyFlags.day28V4.facts.relationshipResponse,null);assert.equal(state.storyFlags.day28V4.facts.currentContact,null);assert.doesNotMatch(JSON.stringify(steps),/보고 싶었어|왔네/);});

test('SCENE03-07 plays Haeun corrections, promises, path banter and bench action instead of hidden summaries',()=>{const state=day28FriendlyFixture();choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});choose(state,'nervous');let steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.match(JSON.stringify(steps),/나도 조금|haeun-small-smile/);choose(state);steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.match(JSON.stringify(steps),/그 부분은 조금 달라|어떤 부분/);choose(state);choose(state);steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.match(JSON.stringify(steps),/바뀌면 다시 말하고|그렇게 말해도 안 싸우네|지금까지는/);choose(state,'ask_pressure');steps=getDay28V4PlayableOpening(state.storyFlags.day28V4);sourced(steps);assert.match(JSON.stringify(steps),/지금은 괜찮았어|bench-dust|벤치 주인까지는 아닌데/);});
