import assert from 'node:assert/strict';
import test from 'node:test';
import {getDay21V4PlayableOpening} from '../src/day21-v4-playable-opening.mjs';
import {validateDay21V4SourceStep} from '../src/day21-v4-source-selection.mjs';
import {chooseDay21,day21State} from './day21-v4-fixture.mjs';

const assertSourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','stageAction'].includes(step.type))assert.equal(validateDay21V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);};

test('shared morning replays SCENE 01-04 without inventing borrowed clothes',()=>{const s=day21State();let steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.equal(steps[0].number,1);assert.equal(steps.at(-1).choiceNumber,1);assertSourced(steps);chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.equal(steps.at(-1).choiceNumber,2);assertSourced(steps);chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===3));assert.ok(steps.some(step=>step.type==='sceneDirection'&&step.number===4));assert.equal(steps.some(step=>step.status==='borrowed-clothes-return'),false);assert.ok(steps.some(step=>step.text==='나는 하은이 내 집에 남겨 두지 않은 물건을 찾지 않았다.'));assert.equal(steps.at(-1).choiceNumber,3);assertSourced(steps);chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.deepEqual(steps.at(-1),{type:'openingBoundary',nextScene:5,route:'PARK'});assertSourced(steps);});

test('message morning stays in separate homes and phone choice stays audio-only',()=>{const s=day21State({morningMode:'MESSAGE_MORNING',day20StayedOver:false});let steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.type==='message'&&step.text==='잘 잤어?'));assert.equal(steps.some(step=>step.text?.includes('컵 위치는 이제 알아')),false);chooseDay21(s);chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.equal(steps.some(step=>step.status==='borrowed-clothes-return'),false);chooseDay21(s,1);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.deepEqual(steps.at(-1),{type:'openingBoundary',nextScene:5,route:'PHONE'});assert.ok(steps.some(step=>step.device==='phone-call'));assertSourced(steps);});

test('no-contact solo morning exposes only defer and never creates a Haeun message',()=>{const s=day21State({relationshipActive:false,contactAllowed:false,relationshipTone:'DIFFICULT',morningMode:'SOLO_MORNING',day20VisitMode:'SOLO',day20StayedOver:false});let steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.equal(steps.some(step=>step.type==='message'||step.speaker==='하은'||step.sender==='하은'),false);chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.equal(steps.some(step=>step.type==='message'),false);chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.equal(steps.some(step=>step.status==='story-message-arrive'),false);assert.equal(steps.some(step=>step.type==='message'||step.speaker==='하은'||step.sender==='하은'),false);assert.equal(steps.at(-1).options.length,1);assert.ok(steps.at(-1).options[0].id.endsWith('_defer'));chooseDay21(s);steps=getDay21V4PlayableOpening(s.storyFlags.day21V4);assert.deepEqual(steps.at(-1),{type:'openingBoundary',nextScene:17,route:'DEFERRED'});assert.equal(s.storyFlags.day21V4.facts.heardHaeunStory,false);assertSourced(steps);});
