import assert from 'node:assert/strict';
import test from 'node:test';
import {getDay21V4PlayableEvening} from '../src/day21-v4-playable-evening.mjs';
import {resolveDay21V4Lodging,resolveDay21V4Travel} from '../src/day21-v4-state-contract.mjs';
import {validateDay21V4SourceStep} from '../src/day21-v4-source-selection.mjs';
import {chooseDay21,day21State} from './day21-v4-fixture.mjs';

const assertSourced=steps=>{for(const step of steps)if(step.source)assert.equal(validateDay21V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel??step.prompt}`);};
const reachDinner=state=>{for(const index of [0,0,0,0,0,0,0,0,0,2])chooseDay21(state,index);};

test('confirmed Busan route separates lodging consent, all travel checks, packing, and ending',()=>{const s=day21State();reachDinner(s);let steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps[0].number,17);assert.equal(steps.at(-1).choiceNumber,11);chooseDay21(s,2);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.number===18));assert.equal(steps.at(-1).choiceNumber,12);chooseDay21(s);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.number===19));assert.equal(steps.at(-1).choiceNumber,13);chooseDay21(s,1);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.at(-1).type,'lodgingConsentCue');assert.equal(s.storyFlags.day21V4.facts.lodgingAgreement,null);resolveDay21V4Lodging(s,{type:'haeunLodgingResponse',accepted:true});steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.at(-1).type,'travelConfirmationCue');assert.deepEqual(steps.at(-1).requiredChecks,['date','transport','budget','mutual','lodging']);assert.equal(s.storyFlags.day21V4.facts.bookingConfirmed,false);resolveDay21V4Travel(s,{type:'travelConfirmation',confirmed:true,dateConfirmed:true,transportConfirmed:true,budgetConfirmed:true,lodgingConfirmed:true,mutualConsent:true});steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.status==='booking-complete'));assert.equal(steps.at(-1).choiceNumber,14);chooseDay21(s);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.status==='bag-open'));assert.equal(steps.at(-1).choiceNumber,15);chooseDay21(s);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.at(-1).choiceNumber,16);chooseDay21(s);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.at(-1).type,'chapterCompletionCue');assert.equal(steps.at(-1).day,21);assertSourced(steps);});

test('unconfirmed Busan closes booking and never opens a travel bag',()=>{const s=day21State();reachDinner(s);chooseDay21(s,2);chooseDay21(s);chooseDay21(s);let steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.at(-1).type,'travelConfirmationCue');resolveDay21V4Travel(s,{type:'travelConfirmation',confirmed:false,dateConfirmed:false,transportConfirmed:true,budgetConfirmed:true,lodgingConfirmed:false,mutualConsent:true});steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.status==='booking-close'));assert.equal(steps.some(step=>step.status==='booking-complete'),false);chooseDay21(s);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.some(step=>step.status==='bag-open'),false);assert.equal(s.storyFlags.day21V4.facts.travelPaymentMade,false);assertSourced(steps);});

test('Seoul day route reserves no room and creates no travel payment',()=>{const s=day21State();reachDinner(s);chooseDay21(s,2);chooseDay21(s,1);let steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.text?.includes('숙소는 예약하지 않았다')));chooseDay21(s);steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.equal(steps.some(step=>step.status==='booking-close'||step.status==='booking-complete'),false);assert.equal(steps.some(step=>step.type==='travelConfirmationCue'||step.type==='lodgingConsentCue'),false);assert.equal(s.storyFlags.day21V4.facts.bookingConfirmed,false);assert.equal(s.storyFlags.day21V4.facts.travelPaymentMade,false);assertSourced(steps);});

test('nearby dinner skips travel and still reaches truthful preparation choice',()=>{const s=day21State();reachDinner(s);chooseDay21(s);const steps=getDay21V4PlayableEvening(s.storyFlags.day21V4);assert.ok(steps.some(step=>step.text?.includes('서로 배고픈 만큼만 골랐다')));assert.ok(steps.some(step=>step.number===20));assert.equal(steps.some(step=>step.status==='booking-close'||step.status==='booking-complete'),false);assert.equal(steps.some(step=>step.number===19),false);assert.equal(steps.at(-1).choiceNumber,14);assert.equal(s.storyFlags.day21V4.facts.travelDiscussion,false);assertSourced(steps);});
