import assert from 'node:assert/strict';
import test from 'node:test';
import {day28FriendlyFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay28V4Choice,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NextMeeting,resolveDay28V4Relationship,validateDay28V4} from '../src/day28-v4-state-contract.mjs';
import {getDay28V4PlayableMiddle} from '../src/day28-v4-playable-middle.mjs';
import {validateDay28V4SourceStep} from '../src/day28-v4-source-selection.mjs';

const choose=(state,suffix)=>{const options=getDay28V4Options(state.storyFlags.day28V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day28V4.phase}:${suffix}`);applyDay28V4Choice(state,option.id);};
function toRelationship(){const state=day28FriendlyFixture();choose(state);resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',method:'IN_PERSON'});for(let number=2;number<=8;number++)choose(state);return state;}
function sourced(steps){for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay28V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);}

test('SCENE09-10 breakup exposes no invented belongings and closes without contact',()=>{const state=toRelationship();resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'END',contactAllowed:false});let steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,9);choose(state);steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.deepEqual(steps.at(-1).options.map(item=>item.id.endsWith('_none')),[true]);choose(state,'none');steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).route,'BREAKUP');assert.equal(state.storyFlags.day28V4.facts.currentContact,null);assert.equal(validateDay28V4(state.storyFlags.day28V4),true);});

test('SCENE11-16 keeps hand, kiss, home invitation and next meeting as independent responses',()=>{const state=toRelationship();resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});choose(state);choose(state,'hand');let steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'day28ContactCue');resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:'HAND',outcome:'ACCEPTED'});assert.equal(state.storyFlags.day28V4.phase,'continuing_intimacy');choose(state,'kiss');steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).contact,'KISS');resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:'KISS',outcome:'DECLINED'});choose(state);steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'day28HomeInvitationCue');resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:true,location:'PLAYER_HOME'});choose(state);choose(state,'next_when_possible');steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).type,'day28NextMeetingCue');resolveDay28V4NextMeeting(state,{type:'day28NextMeetingResponse',outcome:'DEFERRED'});steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).route,'HAEUN_CONTINUING');assert.equal(state.storyFlags.day28V4.facts.currentContact,'NONE');assert.equal(state.storyFlags.day28V4.facts.homeInvitationResponse,'ACCEPTED');assert.equal(state.storyFlags.day28V4.facts.nextMeetingResponse,'DEFERRED');assert.equal(validateDay28V4(state.storyFlags.day28V4),true);});

test('declined hug and outside ending never enter intimacy or home scene',()=>{const state=toRelationship();resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'KNOW_AGAIN',contactAllowed:true});choose(state);choose(state,'hug');resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:'HUG',outcome:'DECLINED'});assert.equal(state.storyFlags.day28V4.phase,'daily_listening');choose(state);resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});assert.equal(state.storyFlags.day28V4.phase,'continuing_farewell');const steps=getDay28V4PlayableMiddle(state.storyFlags.day28V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,14);assert.doesNotMatch(JSON.stringify(steps),/오늘의 집 초대/);assert.equal(state.storyFlags.day28V4.facts.currentContact,'NONE');});
