import assert from 'node:assert/strict';
import test from 'node:test';
import {applyDay25V4Choice,beginDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Future} from '../src/day25-v4-state-contract.mjs';
import {getDay25V4PlayableRelationship} from '../src/day25-v4-playable-relationship.mjs';
import {validateDay25V4SourceStep} from '../src/day25-v4-source-selection.mjs';
import {day25ContinuedFixture} from './day25-v4-playable-fixture.mjs';
const choose=(state,suffix)=>{const options=getDay25V4Options(state.storyFlags.day25V4),selected=suffix?options.find(option=>option.id.endsWith(`_${suffix}`)):options[0];assert.ok(selected,`${state.storyFlags.day25V4.phase}:${suffix}`);applyDay25V4Choice(state,selected.id);};
const sourced=steps=>{for(const step of steps)if(['dialogue','message','monologue','playerNarration','stageAction'].includes(step.type))assert.equal(validateDay25V4SourceStep(step),true,`${step.type}:${step.text??step.description}`);};
function proposal(){const state=day25ContinuedFixture();beginDay25V4(state);for(let i=0;i<9;i++)choose(state);return state;}

test('C10 proposal waits for Haeun independent future response',()=>{const state=proposal();let steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,10);choose(state,'prepare');steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).type,'haeunFutureCue');assert.equal(state.storyFlags.day25V4.facts.haeunFutureOutcome,null);resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,11);assert.match(JSON.stringify(steps),/아직 모르는 게 많은 채로/);});

test('kiss appears only after explicit current consent and leads to C13',()=>{const state=proposal();choose(state,'prepare');resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});choose(state,'more_time');let steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,12);choose(state,'kiss');steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).type,'haeunContactCue');assert.equal(state.storyFlags.day25V4.facts.kissOccurred,false);assert.doesNotMatch(JSON.stringify(steps),/입술이 짧게 닿았다/);resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:'KISS',accepted:true});steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).choiceNumber,13);assert.match(JSON.stringify(steps),/입술이 짧게 닿았다/);});

test('hand refusal and goodbye skip kiss scene without weakening the future agreement',()=>{for(const route of ['hand','goodbye']){const state=proposal();choose(state,'rediscuss');resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'REDISCUSS'});choose(state,route);if(route==='hand'){let cue=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(cue);assert.equal(cue.at(-1).type,'haeunContactCue');resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:'HAND',accepted:false});}const steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).nextScene,20);assert.doesNotMatch(JSON.stringify(steps),/입술이 짧게 닿았다|오늘의 첫 입맞춤/);if(route==='hand')assert.match(JSON.stringify(steps),/아직 손잡기가 편하지 않아/);assert.equal(state.storyFlags.day25V4.facts.haeunFutureOutcome,'REDISCUSS');}}
);

test('explicit relationship end crosses to solo without warm farewell or contact choices',()=>{const state=proposal();choose(state,'different');resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'END'});const steps=getDay25V4PlayableRelationship(state.storyFlags.day25V4);sourced(steps);assert.equal(steps.at(-1).nextScene,17);assert.equal(steps.some(step=>step.type==='choice'&&[11,12,13].includes(step.choiceNumber)),false);assert.doesNotMatch(JSON.stringify(steps),/입술이 짧게 닿았다|손가락을 맞췄다/);});
