import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {getDay30V4Options} from '../src/day30-v4-state-contract.mjs';
import {getDay30V4RuntimeResolution} from '../src/day30-v4-runtime-resolution.mjs';
import {applyDay30V4GameChoice,applyDay30V4GameResolution,completeDay30V4GameChapter,getDay30V4GameResumePresentation,getDay30V4GameSegment,isDay30V4ResolutionStep,prepareDay30V4GameEntry} from '../src/day30-v4-game-bridge.mjs';
import {day30FriendlyFixture,day30NewRelationshipFixture,day30SoloFixture} from './day30-v4-playable-fixture.mjs';

function finish(state){prepareDay30V4GameEntry(state);const scenes=[];let guard=0;while(state.storyFlags.day30V4.phase!=='ending'){if(guard++>60)throw new Error('DAY30_BRIDGE_GUARD');const steps=getDay30V4GameSegment(state);for(const step of steps)if(step.type==='transition'&&step.sceneNumber<=30)scenes.push(step.sceneNumber);const cue=steps.find(isDay30V4ResolutionStep);if(cue){applyDay30V4GameResolution(state,getDay30V4RuntimeResolution(state,cue));continue;}const option=getDay30V4Options(state.storyFlags.day30V4)[0];assert.ok(option,state.storyFlags.day30V4.phase);applyDay30V4GameChoice(state,option.id);}const ending=getDay30V4GameSegment(state);for(const step of ending)if(step.type==='transition'&&step.sceneNumber<=30)scenes.push(step.sceneNumber);const cue=ending.find(step=>step.type==='chapterCompletionCue');assert.ok(cue);completeDay30V4GameChapter(state,cue);return [...new Set(scenes)];}

test('bridge plays friendly, solo, and Ara histories through the real DAY30 completion hook',()=>{const friendly=day30FriendlyFixture(),solo=day30SoloFixture(),ara=day30NewRelationshipFixture();const friendlyScenes=finish(friendly),soloScenes=finish(solo),araScenes=finish(ara);assert.ok(friendlyScenes.includes(5)&&friendlyScenes.includes(30));assert.ok(!soloScenes.includes(5)&&soloScenes.includes(20)&&soloScenes.includes(30));assert.ok(araScenes.includes(18)&&!araScenes.includes(16)&&!araScenes.includes(17));for(const state of [friendly,solo,ara]){assert.equal(state.storyFlags.day30V4.complete,true);assert.equal(state.storyFlags.day30RuntimeComplete,true);assert.equal(state.storyHistory.filter(record=>record.scenarioId==='day30-notion-v4').length,1);}});

test('bridge choice and resolution mutations roll back atomically',()=>{const state=day30FriendlyFixture();prepareDay30V4GameEntry(state);const before=structuredClone(state.storyFlags.day30V4);assert.throws(()=>applyDay30V4GameChoice(state,'day30_v4_bad'),/UNAVAILABLE/);assert.deepEqual(state.storyFlags.day30V4,before);while(state.storyFlags.day30V4.phase!=='meeting_resolution')applyDay30V4GameChoice(state,getDay30V4Options(state.storyFlags.day30V4)[0].id);const pending=structuredClone(state.storyFlags.day30V4);assert.throws(()=>applyDay30V4GameResolution(state,{type:'day30MeetingResponse',target:'ARA',outcome:'ACCEPTED',location:'OUTSIDE'}),/INVALID_MEETING/);assert.deepEqual(state.storyFlags.day30V4,pending);});

test('resume presentation and mapped story steps are renderer-ready',()=>{const state=day30FriendlyFixture();prepareDay30V4GameEntry(state);const presentation=getDay30V4GameResumePresentation(state),steps=getDay30V4GameSegment(state);assert.ok(presentation.backgroundUrl);assert.equal(steps[0].type,'transition');assert.equal(steps.some(step=>step.type==='sceneDirection'||step.type==='day30Boundary'||step.type==='titleCardCue'),false);});

test('main game wires DAY30 V4 entry, choices, resolutions, completion and legacy/free exclusion',()=>{const source=readFileSync(new URL('../game.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(source,/day30-v4-game-bridge\.mjs\?v=1/);assert.match(source,/day30-v4-runtime-resolution\.mjs\?v=1/);assert.match(source,/if\(day30V4\)prepareDay30V4GameEntry\(state\)/);assert.match(source,/applyDay30V4GameChoice\(state,choiceId\)/);assert.match(source,/getDay30V4RuntimeResolution\(state,step\)/);assert.match(source,/applyDay30V4GameResolution\(state,response\)/);assert.match(source,/step\.day===30\?completeDay30V4GameChapter/);assert.match(source,/isDay30V4ResolutionStep\(step\)/);assert.match(source,/completedSession\?\.id===LOCKED_DAY30_SCENE_ID&&!state\.storyFlags\?\.day30V4/);assert.match(source,/!\(lockedDay30&&day30V4\)/);assert.ok(Number(html.match(/game\.js\?v=(\d+)/)?.[1])>=291);});
