import assert from "node:assert/strict";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { selectNextStoryScene } from "../src/story-manager.mjs";
import { DAY30_BODY_CHOICES,DAY30_CONSENT_CHOICES,DAY30_DECISION_CHOICES,applyLockedDay30ChoiceState,getLockedDay30ResumePresentation,getLockedDay30Segment,validateLockedDay30Runtime } from "../src/day30-campaign-runtime.mjs";

const create=()=>{const s=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});s.day=30;s.storyHistory=[{sceneId:"m30-day29-current-eve-reconfirmation",choiceId:"eve29_plan_proceed_reask",day:29,response:"완료"}];s.storyFlags={day30CurrentWeddingDecisionPending:true};return s;};
const s=create();assert.equal(selectNextStoryScene(s)?.id,"m30-day30-current-wedding-decision");assert.equal(validateLockedDay30Runtime(),true);assert.equal(getLockedDay30Segment(s).filter(x=>x.type==="choice").length,1);assert.equal(applyLockedDay30ChoiceState(s,DAY30_BODY_CHOICES[0].id).stage,1);assert.equal(getLockedDay30ResumePresentation(s).backgroundId,"home-morning");assert.equal(applyLockedDay30ChoiceState(s,DAY30_CONSENT_CHOICES[0].id).stage,2);assert.equal(applyLockedDay30ChoiceState(s,DAY30_DECISION_CHOICES[0].id).stage,3);assert.equal(s.storyFlags.day30CurrentWeddingDecisionCompleted,true);assert.equal(s.storyFlags.marriage30CampaignCompleted,true);assert.equal(s.storyFlags.day30CurrentWeddingDecisionPending,false);for(const id of ["wedding-day-current-body-scope","wedding-day-stepwise-consent","wedding-outcome-without-penalty"])assert.ok(s.scenario.unlockedActions.includes(id));assert.ok(s.scenario.followUpHooks.includes("marriage30-current-choice-complete"));assert.ok(s.scenario.clues.includes("current-wedding-decision-record"));assert.equal(getLockedDay30Segment(structuredClone(s)).at(-1).type,"sceneEnd");for(const decision of DAY30_DECISION_CHOICES){const alternate=create();applyLockedDay30ChoiceState(alternate,DAY30_BODY_CHOICES[1].id);applyLockedDay30ChoiceState(alternate,DAY30_CONSENT_CHOICES[1].id);applyLockedDay30ChoiceState(alternate,decision.id);assert.equal(alternate.storyFlags.marriage30CampaignCompleted,true);}console.log("day30-runtime.test: all assertions passed");
