import assert from 'node:assert/strict';
import test from 'node:test';
import {day25MixedFixture} from './day25-v4-playable-fixture.mjs';
import {day28FriendlyFixture,day28NewMeetingFixture,day28SoloFixture} from './day28-v4-playable-fixture.mjs';
import {applyDay25V4Choice,beginDay25V4,completeDay25V4,getDay25V4Options,resolveDay25V4Contact,resolveDay25V4Friends,resolveDay25V4Future,resolveDay25V4Location} from '../src/day25-v4-state-contract.mjs';
import {applyDay26V4Choice,beginDay26V4,completeDay26V4,getDay26V4Options,resolveDay26V4Attendance,resolveDay26V4Jihoon,resolveDay26V4NewMeaning,resolveDay26V4NewNext} from '../src/day26-v4-state-contract.mjs';
import {applyDay27V4Choice,beginDay27V4,completeDay27V4,getDay27V4Options,resolveDay27V4Conversation,resolveDay27V4TruthRecipient} from '../src/day27-v4-state-contract.mjs';
import {applyDay28V4Choice,beginDay28V4,completeDay28V4,getDay28V4Options,resolveDay28V4Contact,resolveDay28V4HomeInvitation,resolveDay28V4Meeting,resolveDay28V4NewRelationship,resolveDay28V4NextMeeting,resolveDay28V4Relationship} from '../src/day28-v4-state-contract.mjs';
import {applyDay29V4Choice,beginDay29V4,completeDay29V4,getDay29V4Options,resolveDay29V4Contact,resolveDay29V4Evening,resolveDay29V4Future,resolveDay29V4New,resolveDay29V4Stay} from '../src/day29-v4-state-contract.mjs';
import {applyDay30V4Choice,beginDay30V4,completeDay30V4,getDay30V4Entry,getDay30V4Options,resolveDay30V4Future,resolveDay30V4Meeting,resolveDay30V4Next,resolveDay30V4Photo,resolveDay30V4Truth,validateDay30V4} from '../src/day30-v4-state-contract.mjs';
import {getDay30V4PlayableBranches} from '../src/day30-v4-playable-branches.mjs';
import {getDay30V4RuntimeResolution} from '../src/day30-v4-runtime-resolution.mjs';
import {validateDay30V4SourceStep} from '../src/day30-v4-source-selection.mjs';

const pick=(options,suffix)=>{const option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${suffix}:${options.map(item=>item.id).join(',')}`);return option.id;};
const choose28=(state,suffix)=>applyDay28V4Choice(state,pick(getDay28V4Options(state.storyFlags.day28V4),suffix));
function finish28(state,{friendly=false,newRoute=false}={}){while(state.storyFlags.day28V4.phase!=='ending'){const phase=state.storyFlags.day28V4.phase;if(phase==='meeting_resolution'){resolveDay28V4Meeting(state,{type:'day28MeetingResponse',target:state.storyFlags.day28V4.facts.meetingTarget,outcome:'ACCEPTED',method:'IN_PERSON'});continue;}if(phase==='relationship_resolution'){resolveDay28V4Relationship(state,{type:'day28RelationshipResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay28V4Contact(state,{type:'day28ContactResponse',contact:state.storyFlags.day28V4.facts.contactRequest,outcome:'DECLINED'});continue;}if(phase==='home_invitation_resolution'){resolveDay28V4HomeInvitation(state,{type:'day28HomeInvitationResponse',accepted:false,location:'OUTSIDE'});continue;}if(phase==='next_meeting_resolution'){resolveDay28V4NextMeeting(state,{type:'day28NextMeetingResponse',outcome:'ACCEPTED'});continue;}if(phase==='new_relationship_resolution'){resolveDay28V4NewRelationship(state,{type:'day28NewRelationshipResponse',recipient:'ARA',outcome:'RECIPROCATE'});continue;}const suffix=phase==='continuing_distance'?'talk_only':phase==='continuing_farewell'&&friendly?'next_when_possible':phase==='new_meeting_wish'&&newRoute?'want_romance':null;choose28(state,suffix);}completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});return state;}
const choose29=(state,suffix)=>applyDay29V4Choice(state,pick(getDay29V4Options(state.storyFlags.day29V4),suffix));
function finish29(state,kind){finish28(state,{friendly:kind==='friendly',newRoute:kind==='mixed'});beginDay29V4(state);let guard=0;while(state.storyFlags.day29V4.phase!=='ending'){assert.ok(guard++<80,state.storyFlags.day29V4.phase);const chapter=state.storyFlags.day29V4,phase=chapter.phase;if(phase==='evening_resolution'){resolveDay29V4Evening(state,{type:'day29EveningResponse',target:chapter.facts.eveningTarget,accepted:true,location:'OUTSIDE'});continue;}if(phase==='future_resolution'){resolveDay29V4Future(state,{type:'day29FutureResponse',outcome:'CONTINUE',contactAllowed:true});continue;}if(phase==='contact_resolution'){resolveDay29V4Contact(state,{type:'day29ContactResponse',contact:chapter.facts.contactRequest,accepted:false});continue;}if(phase==='stay_resolution'){resolveDay29V4Stay(state,{type:'day29StayResponse',accepted:false});continue;}if(phase==='new_resolution'){resolveDay29V4New(state,{type:'day29NewResponse',target:chapter.facts.eveningTarget,outcome:'ACCEPTED'});continue;}choose29(state);}completeDay29V4(state,{type:'chapterCompletionCue',day:29,finalSceneReached:true});return state;}
const friendly=()=>finish29(day28FriendlyFixture(),'friendly');
const solo=()=>finish29(day28SoloFixture(),'solo');
const mixed=()=>finish29(day28NewMeetingFixture(),'mixed');
const choose30=(state,suffix)=>applyDay30V4Choice(state,pick(getDay30V4Options(state.storyFlags.day30V4),suffix));
function unresolved(){const state=day25MixedFixture(),choose25=suffix=>applyDay25V4Choice(state,pick(getDay25V4Options(state.storyFlags.day25V4),suffix)),choose26=suffix=>applyDay26V4Choice(state,pick(getDay26V4Options(state.storyFlags.day26V4),suffix)),choose27=suffix=>applyDay27V4Choice(state,pick(getDay27V4Options(state.storyFlags.day27V4),suffix));beginDay25V4(state);while(state.storyFlags.day25V4.phase!=='ending'){const phase=state.storyFlags.day25V4.phase;if(phase==='location_resolution'){resolveDay25V4Location(state,{type:'haeunMealLocationResponse',accepted:true,costTimeFit:true});continue;}if(phase==='future_resolution'){resolveDay25V4Future(state,{type:'haeunFutureResponse',outcome:'PREPARE_MARRIAGE'});continue;}if(phase==='contact_resolution'){resolveDay25V4Contact(state,{type:'haeunContactResponse',contact:state.storyFlags.day25V4.facts.requestedContact,accepted:true});continue;}if(phase==='friend_resolution'){resolveDay25V4Friends(state,{type:'friendAvailabilityResponse',jihoonAvailable:true,soraAvailable:true});continue;}choose25();}completeDay25V4(state,{type:'chapterCompletionCue',day:25,finalSceneReached:true});beginDay26V4(state);while(state.storyFlags.day26V4.phase!=='ending'){const phase=state.storyFlags.day26V4.phase;if(phase==='attendance_resolution'){resolveDay26V4Attendance(state,{type:'attendanceChangeResponse',accepted:true});continue;}if(phase==='jihoon_resolution'||phase==='solo_friend_resolution'){resolveDay26V4Jihoon(state,{type:'jihoonMealResponse',accepted:false});continue;}if(phase==='new_meaning_resolution'){resolveDay26V4NewMeaning(state,{type:'newMeetingIntentResponse',recipient:'SEOJIN',outcome:'NEED_TIME'});continue;}if(phase==='new_next_resolution'){resolveDay26V4NewNext(state,{type:'newMeetingNextResponse',recipient:'SEOJIN',outcome:'DEFERRED'});continue;}choose26();}completeDay26V4(state,{type:'chapterCompletionCue',day:26,finalSceneReached:true});beginDay27V4(state);choose27();resolveDay27V4Conversation(state,{type:'day27ConversationResponse',target:'SEOJIN',outcome:'ACCEPTED',method:'IN_PERSON'});choose27();choose27('deflect');resolveDay27V4TruthRecipient(state,{type:'day27TruthRecipientResponse',recipient:'SEOJIN',outcome:'END_TODAY'});choose27();choose27();completeDay27V4(state,{type:'chapterCompletionCue',day:27,finalSceneReached:true});beginDay28V4(state);while(state.storyFlags.day28V4.phase!=='ending')choose28(state);completeDay28V4(state,{type:'chapterCompletionCue',day:28,finalSceneReached:true});beginDay29V4(state);while(!['evening','solo_evening'].includes(state.storyFlags.day29V4.phase))choose29(state);if(state.storyFlags.day29V4.phase==='evening')choose29(state,'solo');choose29(state,'tidy');choose29(state,'avoid');while(state.storyFlags.day29V4.phase!=='ending')choose29(state);completeDay29V4(state,{type:'chapterCompletionCue',day:29,finalSceneReached:true});return state;}

test('DAY30 entry accepts only completed DAY29 V4 and preserves legacy saves',()=>{const state=friendly(),entry=getDay30V4Entry(state);assert.equal(entry.mode,'V4_NEW');assert.equal(entry.input.meetingCandidate,'HAEUN');assert.equal(entry.input.meetingLocation,'OUTSIDE');assert.equal(entry.input.source.day29Schema,'day29-notion-v4/1');const legacy=structuredClone(state);legacy.storyFlags.day30RuntimeStage=1;assert.equal(getDay30V4Entry(legacy).mode,'LEGACY');const broken=structuredClone(state);broken.storyFlags.day29V4.facts.day30Handoff.tomorrowRecipient='ARA';assert.equal(getDay30V4Entry(broken).mode,'BLOCKED_PREREQUISITE');beginDay30V4(state);assert.equal(validateDay30V4(state.storyFlags.day30V4),true);const forged=structuredClone(state.storyFlags.day30V4);forged.input.currentMoney+=1;assert.equal(validateDay30V4(forged),false);});

test('Haeun route keeps meeting, future, next appointment and photo consent independent',()=>{const state=friendly();beginDay30V4(state);while(state.storyFlags.day30V4.phase!=='meeting_resolution')choose30(state);assert.throws(()=>resolveDay30V4Meeting(state,{type:'day30MeetingResponse',target:'ARA',outcome:'ACCEPTED',location:'OUTSIDE'}),/INVALID_MEETING/);resolveDay30V4Meeting(state,{type:'day30MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',location:'OUTSIDE'});choose30(state);choose30(state,'prepare');assert.equal(state.storyFlags.day30V4.facts.futureResponse,null);resolveDay30V4Future(state,{type:'day30FutureResponse',outcome:'PREPARE_MARRIAGE',contactAllowed:true});choose30(state);choose30(state,'set_time');choose30(state,'shop');assert.equal(state.storyFlags.day30V4.phase,'next_resolution');resolveDay30V4Next(state,{type:'day30NextResponse',target:'HAEUN',outcome:'ACCEPTED'});choose30(state);while(state.storyFlags.day30V4.phase!=='photo')choose30(state);choose30(state,'together');assert.equal(state.storyFlags.day30V4.facts.photoResponse,null);resolveDay30V4Photo(state,{type:'day30PhotoResponse',target:'HAEUN',accepted:false});assert.equal(getDay30V4Options(state.storyFlags.day30V4).some(option=>option.id.endsWith('_calendar')),true);choose30(state,'calendar');assert.equal(state.storyFlags.day30V4.phase,'ending');assert.equal(state.storyFlags.day30V4.facts.endingHandoff.route,'HAEUN_PREPARE_MARRIAGE');assert.equal(state.storyFlags.day30V4.facts.endingHandoff.photoAccepted,false);assert.equal(validateDay30V4(state.storyFlags.day30V4),true);completeDay30V4(state,{type:'chapterCompletionCue',day:30,finalSceneReached:true});assert.equal(state.storyFlags.day30V4EndingHookPending,true);assert.equal(state.storyFlags.day29V4Day30HookPending,false);});

test('solo history cannot invent a person, shared money, romantic identity, photo or appointment',()=>{const state=solo();const entry=getDay30V4Entry(state);assert.equal(entry.input.meetingCandidate,null);beginDay30V4(state);choose30(state);choose30(state);assert.deepEqual(getDay30V4Options(state.storyFlags.day30V4).map(option=>option.id.split('_').at(-1)),['solo']);choose30(state);choose30(state);assert.equal(state.storyFlags.day30V4.phase,'solo');choose30(state);choose30(state);assert.equal(getDay30V4Options(state.storyFlags.day30V4).some(option=>option.id.endsWith('_shared_only')),false);choose30(state);choose30(state);assert.equal(state.storyFlags.day30V4.phase,'identity');assert.equal(getDay30V4Options(state.storyFlags.day30V4).some(option=>option.id.endsWith('_liked')),false);choose30(state);assert.equal(getDay30V4Options(state.storyFlags.day30V4).some(option=>option.id.endsWith('_together')),false);choose30(state);assert.equal(getDay30V4Options(state.storyFlags.day30V4).some(option=>option.id.endsWith('_calendar')),false);choose30(state);assert.equal(state.storyFlags.day30V4.facts.endingHandoff.route,'SOLO');assert.equal(state.storyFlags.day30V4.facts.endingHandoff.meetingTarget,null);});

test('new relationship route remains locked to the actual Ara history',()=>{const state=mixed(),entry=getDay30V4Entry(state);assert.equal(entry.input.meetingCandidate,'ARA');assert.equal(entry.input.newRelationship,'ARA');beginDay30V4(state);while(state.storyFlags.day30V4.phase!=='meeting_resolution')choose30(state);assert.throws(()=>resolveDay30V4Meeting(state,{type:'day30MeetingResponse',target:'YURI',outcome:'ACCEPTED',location:'OUTSIDE'}),/INVALID_MEETING/);resolveDay30V4Meeting(state,{type:'day30MeetingResponse',target:'ARA',outcome:'ACCEPTED',location:'OUTSIDE'});assert.equal(state.storyFlags.day30V4.phase,'ara_relationship');choose30(state);while(state.storyFlags.day30V4.phase!=='ending'){if(state.storyFlags.day30V4.phase==='next_resolution'){resolveDay30V4Next(state,{type:'day30NextResponse',target:'ARA',outcome:'ACCEPTED'});continue;}if(state.storyFlags.day30V4.phase==='photo_resolution'){resolveDay30V4Photo(state,{type:'day30PhotoResponse',target:'ARA',accepted:true});continue;}choose30(state);}assert.equal(state.storyFlags.day30V4.facts.endingHandoff.route,'ARA_RELATIONSHIP');assert.equal(state.storyFlags.day30V4.facts.endingHandoff.nightRecipient,'ARA');assert.equal(validateDay30V4(state.storyFlags.day30V4),true);});

test('unresolved lie reaches only its real recipient and remains separate from forgiveness',()=>{const state=unresolved(),entry=getDay30V4Entry(state);assert.deepEqual(entry.input.truth,{recipient:'SEOJIN',remaining:true,corrected:false,response:null});beginDay30V4(state);while(state.storyFlags.day30V4.phase!=='truth')choose30(state);let steps=getDay30V4PlayableBranches(state.storyFlags.day30V4);for(const step of steps)if(['dialogue','monologue','playerNarration','storyActionCue'].includes(step.type))assert.equal(validateDay30V4SourceStep(step),true);assert.equal(steps.find(step=>step.type==='sceneDirection').number,21);assert.match(JSON.stringify(steps),/서진/);choose30(state,'correct');assert.equal(state.storyFlags.day30V4.facts.truthResponse,null);steps=getDay30V4PlayableBranches(state.storyFlags.day30V4);assert.equal(steps.at(-1).type,'day30TruthCue');assert.throws(()=>resolveDay30V4Truth(state,{type:'day30TruthResponse',target:'ARA',outcome:'LISTEN'}),/INVALID_TRUTH/);const response=getDay30V4RuntimeResolution(state,steps.at(-1));assert.deepEqual(response,{type:'day30TruthResponse',target:'SEOJIN',outcome:'NEED_TIME'});resolveDay30V4Truth(state,response);steps=getDay30V4PlayableBranches(state.storyFlags.day30V4);for(const step of steps)if(['dialogue','monologue','playerNarration','storyActionCue'].includes(step.type))assert.equal(validateDay30V4SourceStep(step),true);assert.equal(steps.at(-1).nextScene,22);while(state.storyFlags.day30V4.phase!=='ending')choose30(state);assert.equal(state.storyFlags.day30V4.facts.endingHandoff.truthRemaining,false);assert.equal(state.storyFlags.day30V4.facts.endingHandoff.truthResponse,'NEED_TIME');assert.equal(state.storyFlags.day30V4.facts.endingHandoff.nightRecipient,null);});
