import assert from 'node:assert/strict';
import test from 'node:test';
import {day30FriendlyFixture,day30NewRelationshipFixture,day30SoloFixture} from './day30-v4-playable-fixture.mjs';
import {applyDay30V4Choice,beginDay30V4,getDay30V4Options,resolveDay30V4Meeting} from '../src/day30-v4-state-contract.mjs';
import {getDay30V4PlayableOpening} from '../src/day30-v4-playable-opening.mjs';
import {getDay30V4RuntimeResolution} from '../src/day30-v4-runtime-resolution.mjs';
import {validateDay30V4SourceStep} from '../src/day30-v4-source-selection.mjs';

const choose=(state,suffix)=>{const options=getDay30V4Options(state.storyFlags.day30V4),option=suffix?options.find(item=>item.id.endsWith(`_${suffix}`)):options[0];assert.ok(option,`${state.storyFlags.day30V4.phase}:${suffix}`);applyDay30V4Choice(state,option.id);};
const sourced=steps=>{for(const step of steps)if(['dialogue','monologue','playerNarration','storyActionCue'].includes(step.type))assert.equal(validateDay30V4SourceStep(step),true,`${step.type}:${step.text??step.actionLabel}`);};

test('SCENE01-04 exposes common choices in source order and waits for Haeun',()=>{const state=day30FriendlyFixture();beginDay30V4(state);const seen=[];while(state.storyFlags.day30V4.phase!=='meeting_resolution'){const steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);const offered=steps.find(step=>step.type==='choice');assert.ok(offered,state.storyFlags.day30V4.phase);seen.push(offered.choiceNumber);choose(state);}assert.deepEqual(seen,[1,2,3,4]);const steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);assert.equal(steps.at(-1).type,'day30MeetingCue');assert.equal(steps.at(-1).target,'HAEUN');assert.equal(state.storyFlags.day30V4.facts.meetingAccepted,null);});

test('actual Haeun response opens SCENE05 without another character',()=>{const state=day30FriendlyFixture();beginDay30V4(state);while(state.storyFlags.day30V4.phase!=='meeting_resolution')choose(state);const cue=getDay30V4PlayableOpening(state.storyFlags.day30V4).at(-1),response=getDay30V4RuntimeResolution(state,cue);assert.deepEqual(response,{type:'day30MeetingResponse',target:'HAEUN',outcome:'ACCEPTED',location:'OUTSIDE'});resolveDay30V4Meeting(state,response);const steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);assert.equal(steps.at(-1).nextScene,5);assert.equal(steps.at(-1).route,'HAEUN');assert.doesNotMatch(JSON.stringify(steps),/유리|서진|아라/);});

test('solo history shows no invented person or meeting resolution',()=>{const state=day30SoloFixture();beginDay30V4(state);choose(state);choose(state);let steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);assert.deepEqual(steps.at(-1).options.map(option=>option.id.split('_').at(-1)),['solo']);assert.doesNotMatch(JSON.stringify(steps),/하은|유리|서진|아라/);choose(state);choose(state);steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);assert.equal(steps.at(-1).nextScene,20);assert.equal(steps.at(-1).route,'SOLO');assert.equal(steps.some(step=>step.type==='day30MeetingCue'),false);});

test('new relationship meeting stays locked to Ara and routes only to SCENE18',()=>{const state=day30NewRelationshipFixture();beginDay30V4(state);while(state.storyFlags.day30V4.phase!=='meeting_resolution')choose(state);const cue=getDay30V4PlayableOpening(state.storyFlags.day30V4).at(-1);assert.equal(cue.target,'ARA');const response=getDay30V4RuntimeResolution(state,cue);assert.equal(response.outcome,'ACCEPTED');resolveDay30V4Meeting(state,response);const steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);assert.equal(steps.at(-1).nextScene,18);assert.equal(steps.at(-1).target,'ARA');assert.doesNotMatch(JSON.stringify(steps),/하은|유리|서진/);});

test('alternate opening attitudes stay source-backed and a deferred answer creates no meeting',()=>{const state=day30FriendlyFixture();beginDay30V4(state);for(const suffix of ['window','ask','adjust','no_false_promise']){const steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);choose(state,suffix);}assert.equal(state.storyFlags.day30V4.phase,'meeting_resolution');resolveDay30V4Meeting(state,{type:'day30MeetingResponse',target:'HAEUN',outcome:'DEFERRED',location:'OUTSIDE'});const steps=getDay30V4PlayableOpening(state.storyFlags.day30V4);sourced(steps);assert.equal(state.storyFlags.day30V4.facts.meetingAccepted,false);assert.equal(steps.at(-1).nextScene,20);assert.doesNotMatch(JSON.stringify(steps),/SCENE 05|메뉴부터/);});
