import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {DAY9_SCOPE_CHOICES,DAY9_PRESSURE_CHOICES,DAY9_DEBRIEF_CHOICES,applyLockedDay9ChoiceState,getLockedDay9LegacyChoice,getLockedDay9ResumePresentation,getLockedDay9Segment,validateLockedDay9Runtime} from "../src/day9-campaign-runtime.mjs";
import {createScenarioState,validateScenarioState} from "../src/scenario-state.mjs";
import {getStoryScene,selectNextStoryScene} from "../src/story-manager.mjs";

function stateFor(){const scenario=createScenarioState("marriage-in-30-days");scenario.haeunTrust=30;scenario.seojinAffection=7;scenario.seojinStatusInterest=11;scenario.coworkerRelation=8;scenario.investigation=9;scenario.followUpHooks=["day9-second-office-adaptation"];return {gameMode:"marriage-in-30-days",day:9,money:63000,confidence:29,health:74,stress:8,work:18,social:14,storyFlags:{day5ReturnStrategy:"set-return-boundary",day8ShareStrategy:"errand8_explain_decision_log",day9SecondOfficeAdaptationPending:true},storyHistory:[{day:8,sceneId:"m30-day8-independent-errand",choiceId:"errand8_explain_decision_log",response:"완료"}],scenario,partner:{heroineId:"haeun"}};}

assert.equal(validateLockedDay9Runtime(),true);
assert.deepEqual([DAY9_SCOPE_CHOICES.length,DAY9_PRESSURE_CHOICES.length,DAY9_DEBRIEF_CHOICES.length],[3,3,3]);
assert.equal(getStoryScene("m30-day9-second-office-adaptation").choices.length,3);
const state=stateFor(),path=["office9_scope_current_queue","office9_pressure_route_questions","office9_debrief_write_protocol"],resume=["day9-office-project-room-day","day9-office-project-room-day","office-day"];
for(const [index,id] of path.entries()){assert.deepEqual(applyLockedDay9ChoiceState(state,id),{stage:index+1});const restored=JSON.parse(JSON.stringify(state));assert.equal(restored.storyFlags.day9RuntimeStage,index+1);assert.equal(getLockedDay9ResumePresentation(restored).backgroundId,resume[index]);assert.ok(getLockedDay9Segment(restored,index+1).length>0);assert.equal(validateScenarioState(restored.gameMode,restored.scenario),true);}
assert.equal(getLockedDay9LegacyChoice(state),"office9_debrief_write_protocol");
assert.equal(state.storyFlags.day9SecondOfficeAdaptationPending,false);assert.equal(state.storyFlags.day9SecondOfficeAdaptationCompleted,true);assert.equal(state.storyFlags.day10ThreeHourWorkRhythmPending,true);
assert.ok(state.scenario.clues.includes("second-office-adaptation-record"));assert.ok(state.scenario.followUpHooks.includes("day10-three-hour-work-rhythm"));
let paths=0;for(const scope of DAY9_SCOPE_CHOICES)for(const pressure of DAY9_PRESSURE_CHOICES)for(const debrief of DAY9_DEBRIEF_CHOICES){let branch=stateFor();assert.deepEqual(applyLockedDay9ChoiceState(branch,scope.id),{stage:1});branch=JSON.parse(JSON.stringify(branch));assert.deepEqual(applyLockedDay9ChoiceState(branch,pressure.id),{stage:2});branch=JSON.parse(JSON.stringify(branch));assert.deepEqual(applyLockedDay9ChoiceState(branch,debrief.id),{stage:3});assert.equal(new Set(branch.scenario.clues).size,branch.scenario.clues.length);assert.equal(new Set(branch.scenario.unlockedActions).size,branch.scenario.unlockedActions.length);assert.equal(new Set(branch.scenario.followUpHooks).size,branch.scenario.followUpHooks.length);assert.equal(validateScenarioState(branch.gameMode,branch.scenario),true);paths++;}assert.equal(paths,27);
for(const [key,value,required] of [["day5ReturnStrategy","request-current-briefing","파란 파일만"],["day5ReturnStrategy","rebuild-social-context","현재 담당자"],["day8ShareStrategy","errand8_sort_receipt_together","결과물부터 같이 분류"],["day8ShareStrategy","errand8_set_next_solo_boundary","중단 조건이나 귀가 시각"]]){const callback=stateFor();callback.storyFlags[key]=value;assert.ok(JSON.stringify(getLockedDay9Segment(callback,0)).includes(required),`${key} callback`);}
const allText=JSON.stringify([0,1,2].flatMap(stage=>getLockedDay9Segment(state,stage)).concat(DAY9_DEBRIEF_CHOICES.flatMap(item=>getLockedDay9Segment({...state,storyFlags:{...state.storyFlags,day9DebriefStrategy:item.id}},3))));
for(const phrase of ["자동으로 늘어나지","과거에 했다는 말은 현재 권한이 아니었다","오늘의 나는 종료합니다","어제 심부름이 오늘 출근 규칙"])assert.ok(allText.includes(phrase),phrase);
for(const forbidden of ["가짜 하은","D-29","트럭 충돌","의미심장한 미소"])assert.ok(!allText.includes(forbidden),forbidden);
for(const [id,affectionDelta,statusDelta] of [["office9_debrief_name_limits",3,0],["office9_debrief_write_protocol",0,3],["office9_debrief_targeted_feedback",1,1]]){const branch=stateFor(),before=[branch.scenario.seojinAffection,branch.scenario.seojinStatusInterest];applyLockedDay9ChoiceState(branch,"office9_scope_current_queue");applyLockedDay9ChoiceState(branch,"office9_pressure_route_questions");const afterPressure=[branch.scenario.seojinAffection,branch.scenario.seojinStatusInterest];applyLockedDay9ChoiceState(branch,id);assert.deepEqual([branch.scenario.seojinAffection-afterPressure[0],branch.scenario.seojinStatusInterest-afterPressure[1]],[affectionDelta,statusDelta]);assert.ok(branch.scenario.seojinAffection>=before[0]&&branch.scenario.seojinStatusInterest>=before[1]);}
const day10={...stateFor(),day:10,storyHistory:[...state.storyHistory,{day:9,sceneId:"m30-day9-second-office-adaptation",choiceId:"office9_debrief_write_protocol",response:"완료"}]};assert.notEqual(selectNextStoryScene(day10)?.id,"ex-message");
const game=readFileSync(new URL("../game.js",import.meta.url),"utf8");for(const pattern of [/LOCKED_DAY9_SCENE_ID/,/applyLockedDay9ChoiceState\(state,choiceId\)/,/getLockedDay9LegacyChoice\(state\)/,/day9Prompts/,/getLockedDay9ResumePresentation/])assert.match(game,pattern);
console.log("✓ DAY 9 잠금 시나리오 8 Scene·27경로·DAY 5/8 콜백·저장 복원 검증 통과");
