import assert from "node:assert/strict";
import { advanceTime, applyEffects, createInitialState, determineEnding, MAX_DAY, validateState } from "../src/game-core.mjs";
import { getWrappedFocusIndex } from "../src/ui-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { estimateHint, generateGirlfriend, getVisibleTraitRows, observePersonality, PERSONALITY_KEYS, validateGirlfriend } from "../src/girlfriend-manager.mjs";
import { getEligibleEvents, getEventDiagnostics, getEventProbability, MAX_EVENTS_PER_DAY, meetsConditions, rollEvent } from "../src/event-manager.mjs";
import { EVENT_DEFINITIONS, validateEventData } from "../src/events-data.mjs";
import { ACTIONS, PHASES, validateActionData } from "../src/actions-data.mjs";
import { getActionAvailability, getAvailableActions } from "../src/action-manager.mjs";
import { applySelfManagementModifiers, calculateActionEffects } from "../src/consequence-manager.mjs";
import { getRelationshipState } from "../src/relationship-manager.mjs";
import { generateJob, JOBS, validateJob } from "../src/jobs-data.mjs";
import { addJobProgress, applyJobModifiers, getCareerSummary } from "../src/job-manager.mjs";
import { appendTransaction, BOND_PURCHASE_AMOUNT, calculatePaycheck, createAdvancedEconomyState, DAILY_LIVING_COST, depositSavings, getAssetSummary, getEconomySummary, getNextPayday, PAY_DAYS, processDayEndEconomy, purchaseBond, recordTransaction, SAVINGS_TRANSFER_AMOUNT, validateAdvancedEconomyState, withdrawSavings } from "../src/economy-manager.mjs";
import { ITEMS, getItem, validateItemData } from "../src/items-data.mjs";
import { acquireActionItem, addItem, equipItem, getEffectiveAppearance, getEquipmentBonuses, purchaseItem } from "../src/inventory-manager.mjs";
import { calculateGiftReaction, giveGift } from "../src/gift-manager.mjs";
import { NPC_ARCHETYPES, validateNpcArchetypes } from "../src/npcs-data.mjs";
import { applyNpcActionEffects, generateNpcs, getNpcRelationshipStatus, validateNpcs } from "../src/npc-manager.mjs";
import { getTemptationOpportunity, resolveTemptation } from "../src/temptation-manager.mjs";
import { applyRivalPressure, calculateRivalRisk } from "../src/rival-manager.mjs";
import { calculateBreakupRisk, evaluateBreakup } from "../src/conflict-manager.mjs";
import { buildConversationContext, generateContextualReply, getContextualOpening, recordConversationTurn } from "../src/conversation-manager.mjs";
import { getMemoryContext, recordMemory, validateMemories } from "../src/memory-manager.mjs";
import { getInitiatedMessageChance, maybeGenerateInitiatedMessage } from "../src/initiated-message-manager.mjs";
import { requestGirlfriendReply } from "../src/ai-chat-client.mjs";
import { STOCKS, validateStockData } from "../src/stocks-data.mjs";
import { advanceStockMarket, buyStock, createInvestmentState, getPortfolioSummary, sellStock, validateInvestmentState } from "../src/investment-manager.mjs";
import { buyInstantLottery, createLotteryState, DAILY_TICKET_LIMIT, getLotterySummary, LOTTERY_TICKET_PRICE, validateLotteryState } from "../src/lottery-manager.mjs";
import { analyzePlayHistory, ENDING_DEFINITIONS, selectEnding, validateEndingDefinitions } from "../src/ending-manager.mjs";
import { SoundManager, SOUND_SETTING_KEY, validateSoundPresets } from "../src/sound-manager.mjs";
import { evaluateEndingBalance, summarizeEndingDistribution } from "../src/balance-manager.mjs";

const partner = generateGirlfriend(() => 0.5);
assert.equal(validateNpcArchetypes(), true);
const generatedNpcs = generateNpcs(() => 0.5);
assert.equal(generatedNpcs.length, NPC_ARCHETYPES.length);
assert.equal(new Set(generatedNpcs.map(npc => npc.name)).size, generatedNpcs.length);
assert.equal(validateNpcs(generatedNpcs), true);
assert.ok(generatedNpcs.some(npc => npc.interestInPlayer > 0));
assert.ok(generatedNpcs.some(npc => npc.interestInGirlfriend > 0));
const npcRelationshipState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const coworkerNpc = npcRelationshipState.npcs.find(npc => npc.id === "female-coworker");
const coworkerInterestBefore = coworkerNpc.interestInPlayer;
const npcActionResult = applyNpcActionEffects(npcRelationshipState, ACTIONS.evening.find(action => action.id === "coworker-drinks"));
assert.equal(npcActionResult.npc.instanceId, coworkerNpc.instanceId);
assert.ok(coworkerNpc.interestInPlayer > coworkerInterestBefore);
assert.equal(npcRelationshipState.npcHistory.length, 1);
assert.equal(applyNpcActionEffects(npcRelationshipState, ACTIONS.night.find(action => action.id === "early-sleep")), null);
assert.equal(getNpcRelationshipStatus({ relationshipType:"coworker", interestInPlayer:80, trust:30 }).tone, "danger");
assert.equal(getNpcRelationshipStatus({ relationshipType:"rival", interestInGirlfriend:60, trust:30 }).tone, "warning");
assert.equal(getNpcRelationshipStatus({ relationshipType:"friend", trust:70 }).tone, "safe");
const temptationState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const temptingNpc = temptationState.npcs.find(npc => npc.relationshipType === "coworker");
temptingNpc.interestInPlayer = 65;
assert.equal(getTemptationOpportunity(temptationState).level, "drinks");
const trustBeforeRejection = temptationState.trust;
const rejectedTemptation = resolveTemptation(temptationState, temptingNpc.instanceId, "reject");
assert.ok(rejectedTemptation.npc.interestInPlayer < 65);
assert.ok(temptationState.trust > trustBeforeRejection);
assert.equal(temptationState.temptationHistory.at(-1).choiceId, "reject");
assert.equal(resolveTemptation(temptationState, temptingNpc.instanceId, "unknown"), null);
const rivalPressureState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const rivalNpc = rivalPressureState.npcs.find(npc => npc.relationshipType === "rival");
const safeRivalRisk = calculateRivalRisk(rivalPressureState, rivalNpc);
rivalPressureState.affection = 180; rivalPressureState.trust = 220; rivalPressureState.conflict = 80; rivalPressureState.relationshipStress = 85;
rivalPressureState.partner.personality.loyalty = 15; rivalPressureState.partner.personality.opportunism = 90;
const dangerousRivalRisk = calculateRivalRisk(rivalPressureState, rivalNpc);
assert.ok(dangerousRivalRisk.score > safeRivalRisk.score);
const rivalInterestBefore = rivalNpc.interestInGirlfriend;
const rivalPressure = applyRivalPressure(rivalPressureState, ACTIONS.evening.find(action => action.id === "coworker-drinks"));
assert.ok(rivalPressure.rival.interestInGirlfriend > rivalInterestBefore);
assert.equal(rivalPressureState.rivalHistory.length, 1);
const breakupState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const safeBreakupRisk = calculateBreakupRisk(breakupState);
assert.equal(evaluateBreakup(breakupState), null);
breakupState.affection = 100; breakupState.trust = 120; breakupState.conflict = 100; breakupState.relationshipStress = 100;
breakupState.partner.personality.loyalty = 0; breakupState.partner.personality.emotionalSensitivity = 100;
const crisisBreakupRisk = calculateBreakupRisk(breakupState);
assert.ok(crisisBreakupRisk.score > safeBreakupRisk.score);
const breakupResult = evaluateBreakup(breakupState);
assert.ok(breakupResult && breakupState.ended);
assert.equal(evaluateBreakup(breakupState), breakupResult);
const conversationState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
conversationState.actionHistory.push({ day:1, actionId:"focused-work", tag:"성공" });
conversationState.temptationHistory.push({ day:1, choiceId:"secret", partnerTrust:-20 });
const conversationContext = buildConversationContext(conversationState);
assert.equal(conversationContext.girlfriend.name, conversationState.partner.name);
assert.equal(conversationContext.recentActions.at(-1).actionId, "focused-work");
assert.equal(conversationContext.recentTemptations.at(-1).choiceId, "secret");
assert.ok(getContextualOpening(conversationContext).includes("숨기는 거"));
conversationState.temptationHistory = [];
conversationState.fatigue = 80;
assert.ok(getContextualOpening(buildConversationContext(conversationState)).includes("지쳐"));
recordMemory(conversationState,{type:"gift",summary:"기념일 목걸이 선물",importance:4,tags:["선물"]});
recordMemory(conversationState,{type:"temptation",summary:"비밀 만남을 거절함",importance:5,tags:["유혹","거절"]});
assert.equal(validateMemories(conversationState.memories), true);
assert.equal(getMemoryContext(conversationState,1)[0].type, "temptation");
assert.equal(buildConversationContext(conversationState).importantMemories.length, 2);
const messageState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
messageState.partner.personality.contactImportance = 90;
const highContactChance = getInitiatedMessageChance(messageState);
messageState.partner.personality.contactImportance = 10;
assert.ok(highContactChance > getInitiatedMessageChance(messageState));
messageState.partner.personality.contactImportance = 90;
const initiatedMessage = maybeGenerateInitiatedMessage(messageState, () => 0);
assert.ok(initiatedMessage?.text);
assert.equal(maybeGenerateInitiatedMessage(messageState, () => 0), null);
assert.equal(buildConversationContext(messageState).recentInitiatedMessages.length, 1);
assert.ok(getContextualOpening(buildConversationContext(messageState)).includes(initiatedMessage.text));
const apologyReply = generateContextualReply(buildConversationContext(messageState), "오늘은 내가 미안해");
assert.ok(apologyReply.text.includes("고마워"));
assert.ok(apologyReply.effects.trust > 0);
assert.equal(generateContextualReply(buildConversationContext(messageState), "  "), null);
const savedTurn = recordConversationTurn(messageState, "사랑해", "나도 좋아해");
assert.equal(savedTurn.user, "사랑해");
assert.equal(messageState.conversationHistory.length, 1);
const rememberedContext = buildConversationContext(messageState);
assert.equal(rememberedContext.recentConversation.length, 1);
assert.equal(rememberedContext.recentConversation[0].user, "사랑해");
const rememberedReply = generateContextualReply(rememberedContext, "아까 내가 한 말 기억해?");
assert.ok(rememberedReply.text.includes("사랑해"));
assert.ok(rememberedReply.effects.trust > 0);
const remoteReply = await requestGirlfriendReply({ endpoint:"/api/chat", context:buildConversationContext(messageState), message:"안녕", fetchImpl:async () => ({ ok:true, json:async () => ({ reply:"오늘도 반가워!", effects:{ affection:5 } }) }) });
assert.equal(remoteReply.source, "remote");
assert.equal(remoteReply.effects.affection, 5);
const fallbackReply = await requestGirlfriendReply({ endpoint:"/api/chat", context:buildConversationContext(messageState), message:"오늘 힘들어", fetchImpl:async () => { throw new Error("offline"); } });
assert.equal(fallbackReply.source, "local");
assert.ok(fallbackReply.text.includes("힘들었구나"));
assert.equal(validateStockData(), true);
assert.equal(STOCKS.length, 3);
const marketState = { day:2, investment:createInvestmentState() };
const pricesBefore = marketState.investment.market.map(stock => stock.price);
const marketChanges = advanceStockMarket(marketState, () => 0.9);
assert.equal(marketChanges.length, STOCKS.length);
assert.ok(marketState.investment.market.every((stock,index) => stock.price !== pricesBefore[index] && stock.price >= 1000));
assert.equal(marketState.investment.history.at(-1).day, 2);
assert.equal(validateInvestmentState(marketState.investment), true);
const tradingState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
tradingState.money = 500000;
const tradingStock = tradingState.investment.market[0];
const moneyBeforeBuy = tradingState.money;
const buyResult = buyStock(tradingState,tradingStock.id,2);
assert.equal(buyResult.ok,true);
assert.equal(tradingState.money,moneyBeforeBuy-tradingStock.price*2);
assert.equal(tradingState.investment.holdings[tradingStock.id].quantity,2);
assert.equal(getPortfolioSummary(tradingState).positions,1);
const sellResult = sellStock(tradingState,tradingStock.id,1);
assert.equal(sellResult.ok,true);
assert.equal(tradingState.investment.holdings[tradingStock.id].quantity,1);
assert.equal(tradingState.economyLedger.at(-1).category,"investment");
const lotteryState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const lotteryMoneyBefore = lotteryState.money;
const jackpotResult = buyInstantLottery(lotteryState, () => 0);
assert.equal(jackpotResult.ok,true);
assert.equal(jackpotResult.tierId,"jackpot");
assert.equal(lotteryState.money,lotteryMoneyBefore-LOTTERY_TICKET_PRICE+jackpotResult.prize);
assert.equal(getLotterySummary(lotteryState).tickets,1);
for (let ticket=1;ticket<DAILY_TICKET_LIMIT;ticket+=1) assert.equal(buyInstantLottery(lotteryState, () => 0.9).ok,true);
assert.equal(buyInstantLottery(lotteryState, () => 0.9).ok,false);
assert.equal(validateLotteryState(lotteryState.lottery),true);
assert.equal(validateLotteryState(createLotteryState()),true);
const savingsState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const savingsCashBefore = savingsState.money;
assert.equal(depositSavings(savingsState).ok,true);
assert.equal(savingsState.money,savingsCashBefore-SAVINGS_TRANSFER_AMOUNT);
assert.equal(savingsState.finance.savings,SAVINGS_TRANSFER_AMOUNT);
const assetsAfterDeposit = getAssetSummary(savingsState);
assert.equal(assetsAfterDeposit.netWorth,savingsCashBefore);
const interestEntries = processDayEndEconomy(savingsState,1);
assert.ok(interestEntries.some(entry => entry.category === "savings-interest"));
assert.ok(savingsState.finance.interestEarned > 0);
assert.equal(withdrawSavings(savingsState).ok,true);
const bondState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
bondState.money = BOND_PURCHASE_AMOUNT;
const bondPurchase = purchaseBond(bondState);
assert.equal(bondPurchase.ok,true);
assert.equal(getAssetSummary(bondState).bondValue,BOND_PURCHASE_AMOUNT);
const bondMaturityEntries = processDayEndEconomy(bondState,bondPurchase.bond.maturityDay);
assert.ok(bondMaturityEntries.some(entry => entry.category === "bond-maturity"));
assert.equal(bondState.finance.bonds.length,0);
assert.ok(bondState.finance.bondInterestEarned > 0);
assert.equal(validateAdvancedEconomyState(savingsState.finance),true);
assert.equal(validateAdvancedEconomyState(createAdvancedEconomyState()),true);
const analysisState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
analysisState.day = 31;
analysisState.choices.push("성공","성공","데이트","연락");
analysisState.temptationHistory.push({day:12,choiceId:"secret"});
analysisState.eventHistory.push({day:8,eventId:"surprise"});
analysisState.jobLevel = 2;
const playAnalysis = analyzePlayHistory(analysisState);
assert.equal(playAnalysis.daysPlayed,30);
assert.equal(playAnalysis.totalChoices,4);
assert.deepEqual(playAnalysis.dominantChoice,{tag:"성공",count:2});
assert.equal(playAnalysis.careerLevel,2);
assert.equal(playAnalysis.secretChoices,1);
assert.equal(playAnalysis.highlights.length,4);
assert.ok(playAnalysis.netWorth >= analysisState.money);
assert.equal(validateEndingDefinitions(),true);
assert.equal(ENDING_DEFINITIONS.length,14);
assert.equal(new Set(ENDING_DEFINITIONS.map(ending => ending.id)).size,14);
const betrayalEndingState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
betrayalEndingState.trust = 300;
betrayalEndingState.temptationHistory.push({day:20,choiceId:"secret"});
assert.equal(selectEnding(betrayalEndingState).id,"betrayal-revealed");
const lotteryEndingState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
lotteryEndingState.lottery.totalWon = 500000;
assert.equal(selectEnding(lotteryEndingState).id,"lottery-reversal");
const happyEndingState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
happyEndingState.affection = 900; happyEndingState.trust = 900;
assert.equal(selectEnding(happyEndingState).id,"happy-marriage");
assert.deepEqual(summarizeEndingDistribution(["a","b","a"]),{
  total:3,
  uniqueEndings:2,
  counts:{a:2,b:1},
  dominant:{id:"a",count:2,share:2/3}
});
assert.equal(evaluateEndingBalance([]).balanced,false);
const seededRandom = seed => {
  let value = seed >>> 0;
  return () => ((value = (value * 1664525 + 1013904223) >>> 0) / 4294967296);
};
const balanceEndingIds = [];
for (let run = 1; run <= 200; run += 1) {
  const random = seededRandom(run);
  const balanceState = createInitialState(generateGirlfriend(random), random);
  while (!balanceState.ended) {
    const phase = PHASES[balanceState.phase];
    const available = getAvailableActions(balanceState, ACTIONS[phase.key]);
    const action = available[Math.floor(random() * available.length)];
    const { effects } = calculateActionEffects(balanceState, action);
    if (action.random) {
      const win = random() > 0.48;
      effects.money = win ? Math.round(40000 + random() * 90000) : -Math.round(25000 + random() * 70000);
    }
    applyEffects(balanceState, effects);
    if (effects.money) appendTransaction(balanceState, { category:"action", label:action.title, amount:Math.round(effects.money) });
    addJobProgress(balanceState, action, effects);
    applyNpcActionEffects(balanceState, action);
    applyRivalPressure(balanceState, action);
    balanceState.choices.push(action.tag);
    balanceState.actionHistory.push({ day:balanceState.day, phase:balanceState.phase, actionId:action.id, tag:action.tag });
    observePersonality(balanceState, action.tag, random);
    const finishedDay = balanceState.phase === PHASES.length - 1;
    const completedDay = balanceState.day;
    advanceTime(balanceState);
    if (finishedDay) {
      advanceStockMarket(balanceState, random);
      processDayEndEconomy(balanceState, completedDay);
    }
    rollEvent(balanceState, random);
  }
  balanceEndingIds.push(selectEnding(balanceState).id);
}
const endingBalance = evaluateEndingBalance(balanceEndingIds);
assert.equal(endingBalance.balanced,true,JSON.stringify(endingBalance));
assert.ok(endingBalance.uniqueEndings >= 5);
assert.ok(endingBalance.dominant.share <= 0.5);
console.log(`✓ 200회 플레이 엔딩 균형 검증 통과 · ${endingBalance.uniqueEndings}종 · 최다 ${(endingBalance.dominant.share*100).toFixed(1)}%`);
assert.equal(validateSoundPresets(),true);
const soundValues = new Map();
const soundStorage = { getItem:key => soundValues.get(key) ?? null, setItem:(key,value) => soundValues.set(key,value) };
let soundStopped = 0;
const fakeAudioContext = { currentTime:0, state:"running", destination:{}, createOscillator:()=>({type:"",frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){soundStopped+=1;}}), createGain:()=>({gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}}) };
const soundManager = new SoundManager({storage:soundStorage,contextFactory:()=>fakeAudioContext});
assert.equal(soundManager.enabled,false);
assert.equal(soundManager.play("select"),false);
assert.equal(soundManager.toggle(),true);
assert.equal(soundValues.get(SOUND_SETTING_KEY),"on");
assert.equal(soundManager.play("confirm"),true);
assert.equal(soundStopped,1);
assert.equal(soundManager.toggle(false),false);
assert.equal(getWrappedFocusIndex(0,3,true),2);
assert.equal(getWrappedFocusIndex(2,3,false),0);
assert.equal(getWrappedFocusIndex(-1,3,false),0);
assert.equal(getWrappedFocusIndex(-1,3,true),2);
assert.equal(getWrappedFocusIndex(0,0,false),-1);
const memoryStorage = () => {
  const values = new Map();
  return { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) };
};

for (let run = 0; run < 100; run += 1) {
  const state = createInitialState(partner, () => ((run * 37) % 100) / 100);
  let actions = 0;
  while (!state.ended) {
    const effects = actions % 4 === 0
      ? { money: 25000, work: 5, stress: 4, energy: -6, affection: -2 }
      : { money: -12000, affection: 8, trust: 4, stress: -3, energy: -4 };
    applyEffects(state, effects);
    state.choices.push(actions % 4 === 0 ? "성공" : "연락");
    advanceTime(state);
    actions += 1;
    assert.ok(actions <= 121, "simulation must not stall");
  }
  assert.equal(state.day, MAX_DAY + 1);
  assert.equal(actions, MAX_DAY * 4);
  assert.ok(validateState(state));
  for (const key of ["health", "energy", "stress", "charm", "work", "social"]) assert.ok(state[key] >= 0 && state[key] <= 100);
  for (const key of ["fatigue", "fashion", "confidence"]) assert.ok(state[key] >= 0 && state[key] <= 100);
  assert.ok(state.affection >= 0 && state.affection <= 1000);
  assert.ok(state.trust >= 0 && state.trust <= 1000);
  assert.ok(determineEnding(state)[0].length > 0);
}

const storage = memoryStorage();
const original = createInitialState(partner, () => 0.5);
SaveManager.save(original, storage);
const restored = SaveManager.load(storage);
assert.ok(restored);
assert.equal(restored.partner.name, original.partner.name);
assert.equal(restored.money, original.money);
const legacySave = structuredClone(original);
delete legacySave.npcs;
delete legacySave.lottery;
delete legacySave.finance;
storage.setItem(SaveManager.key, JSON.stringify(legacySave));
const migratedSave = SaveManager.load(storage);
assert.ok(migratedSave);
assert.equal(validateNpcs(migratedSave.npcs), true);
assert.equal(validateLotteryState(migratedSave.lottery), true);
assert.equal(validateAdvancedEconomyState(migratedSave.finance), true);
storage.setItem(SaveManager.key, "{invalid-json");
assert.equal(SaveManager.load(storage), null);

console.log("✓ 100회 × 30일 자동 시뮬레이션 통과");
console.log("✓ 상태 범위, 종료 조건, 엔딩, 저장/불러오기 검증 통과");

const generatedValues = new Set();
for (let seed = 1; seed <= 100; seed += 1) {
  let cursor = seed;
  const random = () => ((cursor = (cursor * 16807) % 2147483647) - 1) / 2147483646;
  const girlfriend = generateGirlfriend(random);
  assert.equal(Object.keys(girlfriend.personality).length, PERSONALITY_KEYS.length);
  for (const value of Object.values(girlfriend.personality)) assert.ok(value >= 8 && value <= 92);
  generatedValues.add(JSON.stringify(girlfriend.personality));
}
assert.ok(generatedValues.size > 95, "personality generation must produce varied results");
assert.equal(validateGirlfriend(generateGirlfriend(() => 0.5)), true);
const corruptGirlfriend = generateGirlfriend(() => 0.5);
corruptGirlfriend.personality.jealousy = 140;
assert.equal(validateGirlfriend(corruptGirlfriend), false);
const missingTraitGirlfriend = generateGirlfriend(() => 0.5);
delete missingTraitGirlfriend.personality.loyalty;
assert.equal(validateGirlfriend(missingTraitGirlfriend), false);

const inferenceState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
for (let i = 0; i < 12; i += 1) observePersonality(inferenceState, "연락", () => 0.1);
assert.ok(inferenceState.revealedTraits.length > 0, "repeated interaction must reveal a trait");
assert.equal(getVisibleTraitRows(inferenceState).length, 5);
const highInferenceState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
highInferenceState.partner.personality.contactImportance = 90;
const highObservation = observePersonality(highInferenceState, "연락", () => 0.5);
assert.equal(highObservation.hint, "높은 편?");
const lowInferenceState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
lowInferenceState.partner.personality.contactImportance = 10;
const lowObservation = observePersonality(lowInferenceState, "연락", () => 0.5);
assert.equal(lowObservation.hint, "낮은 편?");
assert.equal(estimateHint(50), "보통에 가까움?");
console.log("✓ 100명 성향 랜덤 생성과 숨겨진 성향 추론 검증 통과");

const eventState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
eventState.day = 6;
eventState.stress = 90;
const moneyBeforeForcedEvent = eventState.money;
assert.ok(meetsConditions(eventState, [{ stat: "stress", operator: ">=", value: 75 }]));
assert.ok(getEligibleEvents(eventState).some(event => event.id === "work-mistake"));
const forcedEvent = rollEvent(eventState, () => 0, EVENT_DEFINITIONS);
assert.equal(forcedEvent.id, "work-mistake");
assert.equal(eventState.eventHistory.length, 1);
assert.equal(eventState.money, moneyBeforeForcedEvent - 20000);
assert.equal(eventState.economyLedger.at(-1).category, "event");
assert.equal(eventState.economyLedger.at(-1).amount, -20000);
assert.equal(getEligibleEvents(eventState).some(event => event.id === "work-mistake"), false, "cooldown must prevent immediate repeat");
eventState.day += 3;
assert.equal(getEligibleEvents(eventState).some(event => event.id === "work-mistake"), true, "event must return after cooldown");

const suspicionEvent = EVENT_DEFINITIONS.find(event => event.id === "relationship-suspicion");
eventState.partner.personality.jealousy = 50;
eventState.partner.personality.emotionalSensitivity = 50;
eventState.conflict = 0;
const baseSuspicionChance = getEventProbability(eventState, suspicionEvent);
eventState.partner.personality.jealousy = 85;
eventState.partner.personality.emotionalSensitivity = 82;
eventState.conflict = 60;
const modifiedSuspicionChance = getEventProbability(eventState, suspicionEvent);
assert.equal(baseSuspicionChance, 0.42);
assert.equal(modifiedSuspicionChance, 0.87);
assert.ok(meetsConditions(eventState, [{ stat: "partner.personality.jealousy", operator: ">=", value: 70 }]));

const cappedEvent = { probability: 0.9, probabilityModifiers: [{ conditions: [], multiply: 2 }] };
assert.equal(getEventProbability(eventState, cappedEvent), 1, "probability must be capped at one");
eventState.actionHistory = [{ day:eventState.day, tag:"유혹" }];
eventState.partner.personality.jealousy = 50;
eventState.partner.personality.emotionalSensitivity = 50;
eventState.conflict = 0;
assert.ok(meetsConditions(eventState, [{ recentTag:"유혹", withinDays:3, minCount:1 }]));
const suspicionWithTemptation = getEventProbability(eventState, suspicionEvent);
eventState.actionHistory = [{ day:eventState.day - 5, tag:"유혹" }];
const suspicionWithoutRecentTemptation = getEventProbability(eventState, suspicionEvent);
assert.equal(Math.round((suspicionWithTemptation - suspicionWithoutRecentTemptation) * 100), 25);
const crisisState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
crisisState.day = 12;
crisisState.affection = 300;
crisisState.relationshipStress = 60;
crisisState.conflict = 75;
crisisState.partner.personality.loyalty = 25;
const crisisEvent = EVENT_DEFINITIONS.find(event => event.id === "relationship-crisis");
assert.ok(meetsConditions(crisisState, crisisEvent.conditions));
assert.equal(Math.round(getEventProbability(crisisState, crisisEvent) * 100), 86);
const rivalState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
rivalState.day = 10;
rivalState.trust = 400;
rivalState.relationshipStress = 50;
rivalState.partner.personality.opportunism = 80;
const rivalEvent = EVENT_DEFINITIONS.find(event => event.id === "rival-approach");
assert.ok(meetsConditions(rivalState, rivalEvent.conditions));
assert.ok(getEventProbability(rivalState, rivalEvent) > rivalEvent.probability);
eventState.day = eventState.eventHistory[0].day;
const diagnostics = getEventDiagnostics(eventState);
assert.equal(diagnostics.length, EVENT_DEFINITIONS.length);
assert.ok(diagnostics.every(item => typeof item.eligible === "boolean" && item.probability >= 0 && item.probability <= 1));
assert.ok(diagnostics.some(item => item.cooldownRemaining > 0), "diagnostics must expose cooldown state");
assert.equal(MAX_EVENTS_PER_DAY, 1);
const sameDayEventCount = eventState.eventHistory.length;
assert.equal(rollEvent(eventState, () => 0), null, "a second event on the same day must not trigger");
assert.equal(eventState.eventHistory.length, sameDayEventCount);
assert.ok(getEventDiagnostics(eventState).every(item => item.dailyLimitReached), "diagnostics must expose daily event limit");

for (let run = 0; run < 100; run += 1) {
  const randomEventState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
  for (let turn = 0; turn < 120; turn += 1) {
    applyEffects(randomEventState, { stress: turn % 9 === 0 ? 12 : -1, energy: -2, health: turn % 12 === 0 ? -3 : 0 });
    rollEvent(randomEventState, () => ((run * 31 + turn * 17) % 100) / 100);
    advanceTime(randomEventState);
  }
  assert.equal(randomEventState.ended, true);
  const dailyCounts = Object.values(Object.groupBy(randomEventState.eventHistory, event => event.day)).map(events => events.length);
  assert.ok(dailyCounts.every(count => count <= MAX_EVENTS_PER_DAY));
  assert.ok(randomEventState.eventHistory.length <= 120);
}
console.log("✓ 조건·확률·우선순위·쿨다운 이벤트와 100회 회귀 검증 통과");
console.log("✓ 플레이어 상태·연인 성격 기반 동적 이벤트 확률 검증 통과");
console.log("✓ 이별 위기·라이벌 접근 복합 조건과 성격 보정 검증 통과");
assert.equal(validateEventData(), true);
for (const id of ["sudden-overtime", "ex-contact", "date-cancelled"]) assert.ok(EVENT_DEFINITIONS.some(event => event.id === id));
assert.equal(new Set(EVENT_DEFINITIONS.map(event => event.id)).size, EVENT_DEFINITIONS.length);
const invalidProbability = [{ ...EVENT_DEFINITIONS[0], id:"bad-probability", probability:1.5 }];
assert.equal(validateEventData(invalidProbability), false);
const invalidOperator = [{ ...EVENT_DEFINITIONS[0], id:"bad-operator", conditions:[{ stat:"stress", operator:"!=", value:3 }] }];
assert.equal(validateEventData(invalidOperator), false);
const duplicateEvents = [{ ...EVENT_DEFINITIONS[0] }, { ...EVENT_DEFINITIONS[0] }];
assert.equal(validateEventData(duplicateEvents), false);
console.log(`✓ ${EVENT_DEFINITIONS.length}개 이벤트 데이터 스키마와 중복 ID 검증 통과`);
console.log("✓ 디버그용 이벤트 진단 데이터 검증 통과");
assert.equal(validateActionData(), true);
assert.equal(PHASES.length, 4);
assert.equal(Object.values(ACTIONS).flat().length, 16);
assert.equal(new Set(Object.values(ACTIONS).flat().map(action => action.id)).size, 16);
console.log("✓ 4개 시간대·16개 행동 데이터 스키마 검증 통과");
const requirementState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
requirementState.money = 10000;
requirementState.energy = 8;
const lockedDate = getActionAvailability(requirementState, ACTIONS.evening.find(action => action.id === "dinner-date"));
assert.equal(lockedDate.available, false);
assert.match(lockedDate.reason, /자산/);
assert.equal(getActionAvailability(requirementState, ACTIONS.morning.find(action => action.id === "morning-gym")).available, false);
assert.ok(getAvailableActions(requirementState, ACTIONS.evening).length > 0, "at least one evening action must remain available");
console.log("✓ 돈·체력 기반 행동 요구조건과 잠금 사유 검증 통과");
const personalityState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const contactAction = ACTIONS.morning.find(action => action.id === "morning-contact");
personalityState.partner.personality.contactImportance = 90;
const highContactEffects = calculateActionEffects(personalityState, contactAction);
personalityState.partner.personality.contactImportance = 10;
const lowContactEffects = calculateActionEffects(personalityState, contactAction);
assert.ok(highContactEffects.effects.affection > lowContactEffects.effects.affection);

const dateAction = ACTIONS.evening.find(action => action.id === "dinner-date");
personalityState.partner.personality.romanticism = 90;
const romanticEffects = calculateActionEffects(personalityState, dateAction);
personalityState.partner.personality.romanticism = 10;
const practicalEffects = calculateActionEffects(personalityState, dateAction);
assert.ok(romanticEffects.effects.affection > practicalEffects.effects.affection);
assert.ok(romanticEffects.effects.excitement > practicalEffects.effects.excitement);

const temptationAction = ACTIONS.evening.find(action => action.id === "coworker-drinks");
personalityState.partner.personality.jealousy = 90;
const jealousEffects = calculateActionEffects(personalityState, temptationAction);
personalityState.partner.personality.jealousy = 10;
const calmEffects = calculateActionEffects(personalityState, temptationAction);
assert.ok(Math.abs(jealousEffects.effects.trust) > Math.abs(calmEffects.effects.trust));
assert.ok(jealousEffects.effects.conflict > calmEffects.effects.conflict);
console.log("✓ 연락·데이트·쇼핑·성공·유혹의 성격별 복합 결과 검증 통과");
const relationshipState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
relationshipState.affection = 800; relationshipState.trust = 300;
assert.equal(getRelationshipState(relationshipState).id, "love-with-doubt");
relationshipState.affection = 600; relationshipState.trust = 800; relationshipState.excitement = 300;
assert.equal(getRelationshipState(relationshipState).id, "comfortable-rut");
relationshipState.affection = 820; relationshipState.trust = 780; relationshipState.excitement = 700;
assert.equal(getRelationshipState(relationshipState).id, "deep-love");
relationshipState.affection = 250;
assert.equal(getRelationshipState(relationshipState).id, "crisis");
console.log("✓ 호감·신뢰·설렘·갈등 조합 관계 상태 판정 검증 통과");
assert.equal(JOBS.length, 4);
assert.ok(JOBS.every(validateJob));
const jobState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
assert.ok(validateJob(jobState.job));
const workAction = ACTIONS.day.find(action => action.id === "focused-work");
jobState.job = structuredClone(JOBS.find(job => job.id === "developer"));
const modifiedWork = applyJobModifiers(jobState, workAction, workAction.effects);
assert.ok(modifiedWork.money > workAction.effects.money);
assert.ok(modifiedWork.stress > workAction.effects.stress);
jobState.jobProgress = jobState.job.promotionThreshold - 1;
const promotion = addJobProgress(jobState, workAction, modifiedWork);
assert.equal(promotion.level, 2);
assert.ok(jobState.job.incomeMultiplier > JOBS.find(job => job.id === "developer").incomeMultiplier);
const careerSummary = getCareerSummary(jobState);
assert.equal(careerSummary.threshold, jobState.job.promotionThreshold);
assert.equal(careerSummary.remaining, careerSummary.threshold - careerSummary.progress);
assert.ok(careerSummary.percent >= 0 && careerSummary.percent <= 100);
assert.ok(["planner","developer","designer","sales"].includes(generateJob(() => 0.75).id));
console.log("✓ 4개 직업의 수입·스트레스·성장 보정과 승진 검증 통과");
const economyState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const startingMoney = economyState.money;
const actionEntry = appendTransaction(economyState, { category:"action", label:"업무에 집중하기", amount:45000 });
assert.equal(actionEntry.amount, 45000);
assert.equal(economyState.money, startingMoney);
const normalDayEntries = processDayEndEconomy(economyState, 1);
assert.equal(normalDayEntries.length, 1);
assert.equal(economyState.money, startingMoney - DAILY_LIVING_COST);
const beforePayday = economyState.money;
const paydayEntries = processDayEndEconomy(economyState, PAY_DAYS[0]);
assert.equal(paydayEntries.length, 2);
assert.equal(paydayEntries[1].amount, calculatePaycheck(economyState));
assert.equal(economyState.money, beforePayday - DAILY_LIVING_COST + calculatePaycheck(economyState));
recordTransaction(economyState, { day:10, category:"test", label:"테스트 지출", amount:-1000 });
const economySummary = getEconomySummary(economyState);
assert.ok(economySummary.income > 0 && economySummary.expense > 0);
assert.equal(economySummary.transactions, 5);
assert.equal(getNextPayday(1), 10);
assert.equal(getNextPayday(10), 10);
assert.equal(getNextPayday(21), 30);
assert.equal(getNextPayday(31), null);
console.log("✓ 일일 생활비·10일 급여·경제 원장과 요약 검증 통과");
assert.equal(validateItemData(), true);
assert.equal(ITEMS.length, 9);
assert.ok(ITEMS.some(item => item.category === "cosmetics"));
assert.ok(ITEMS.some(item => item.category === "smartphone"));
assert.ok(ITEMS.some(item => item.category === "car"));
const inventoryState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const shirt = acquireActionItem(inventoryState, ACTIONS.night.find(action => action.id === "online-shopping"));
assert.ok(shirt?.equipped);
assert.equal(inventoryState.inventory.length, 1);
assert.equal(inventoryState.equipment.clothes, shirt.instanceId);
const gift = acquireActionItem(inventoryState, ACTIONS.evening.find(action => action.id === "gift-shopping"));
assert.equal(gift.owner, "gift");
assert.equal(gift.equipped, false);
const sneakers = addItem(inventoryState, "urban-sneakers");
equipItem(inventoryState, sneakers.instanceId);
const bonuses = getEquipmentBonuses(inventoryState);
assert.equal(bonuses.fashion, getItem("linen-shirt").fashionBonus + getItem("urban-sneakers").fashionBonus);
const appearance = getEffectiveAppearance(inventoryState);
assert.equal(appearance.charm, Math.min(100, inventoryState.charm + bonuses.attractiveness));
assert.equal(appearance.fashion, Math.min(100, inventoryState.fashion + bonuses.fashion));
const equipmentDateAction = ACTIONS.day.find(action => action.id === "lunch-date");
const equippedDateEffects = calculateActionEffects(inventoryState, equipmentDateAction).effects;
const unequippedDateState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
unequippedDateState.partner = structuredClone(inventoryState.partner);
assert.ok(equippedDateEffects.affection > calculateActionEffects(unequippedDateState, equipmentDateAction).effects.affection);
const replacementShirt = addItem(inventoryState, "linen-shirt");
equipItem(inventoryState, replacementShirt.instanceId);
assert.equal(inventoryState.equipment.clothes, replacementShirt.instanceId);
assert.equal(shirt.equipped, false);
console.log("✓ 8개 아이템·인벤토리·카테고리 장착·능력치 보너스 검증 통과");
const shoppingState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
shoppingState.money = 100000;
const moneyBeforePurchase = shoppingState.money;
const purchase = purchaseItem(shoppingState, "linen-shirt", "player");
assert.ok(purchase.ok && purchase.instance.equipped);
assert.equal(shoppingState.money, moneyBeforePurchase - getItem("linen-shirt").price);
assert.equal(shoppingState.economyLedger.at(-1).category, "shopping");
const failedPurchase = purchaseItem(shoppingState, "classic-watch", "gift");
assert.equal(failedPurchase.ok, false);
assert.equal(shoppingState.inventory.length, 1);
shoppingState.money = getItem("velvet-lip-kit").price;
const cosmeticsPurchase = purchaseItem(shoppingState, "velvet-lip-kit", "player");
assert.ok(cosmeticsPurchase.ok && cosmeticsPurchase.instance.equipped);
assert.equal(shoppingState.equipment.cosmetics, cosmeticsPurchase.instance.instanceId);
const phonePurchase = purchaseItem(shoppingState, "aurora-phone", "gift");
assert.equal(phonePurchase.ok, false);
shoppingState.money = getItem("solstice-ev").price;
const carPurchase = purchaseItem(shoppingState, "solstice-ev", "player");
assert.ok(carPurchase.ok && carPurchase.instance.equipped);
assert.equal(shoppingState.equipment.car, carPurchase.instance.instanceId);
console.log("✓ 상점 구매·경제 원장·자동 장착·잔액 부족 차단 검증 통과");
const giftState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
giftState.partner.personality.materialism = 90;
giftState.partner.personality.giftPreference = 90;
giftState.partner.personality.romanticism = 90;
const perfume = addItem(giftState, "rose-parfum", "gift");
const highGiftReaction = calculateGiftReaction(giftState, getItem("rose-parfum"));
const affectionBeforeGift = giftState.affection;
const givenGift = giveGift(giftState, perfume.instanceId);
assert.ok(givenGift.reaction.willEquip);
assert.equal(givenGift.instance.owner, "girlfriend");
assert.equal(giftState.girlfriendEquipment.perfume, perfume.instanceId);
assert.equal(giftState.affection, affectionBeforeGift + highGiftReaction.affection);
assert.equal(giveGift(giftState, perfume.instanceId), null);
const cosmeticsGift = addItem(giftState, "velvet-lip-kit", "gift");
const givenCosmetics = giveGift(giftState, cosmeticsGift.instanceId);
assert.ok(givenCosmetics.reaction.willEquip);
assert.equal(giftState.girlfriendEquipment.cosmetics, cosmeticsGift.instanceId);
const lowPreferenceState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
lowPreferenceState.partner.personality.materialism = 10;
lowPreferenceState.partner.personality.giftPreference = 10;
lowPreferenceState.partner.personality.romanticism = 10;
const lowGiftReaction = calculateGiftReaction(lowPreferenceState, getItem("rose-parfum"));
assert.ok(highGiftReaction.affection > lowGiftReaction.affection);
assert.equal(lowGiftReaction.willEquip, false);
console.log("✓ 물질·선물·낭만 성향별 선물 반응과 여자친구 장착 검증 통과");
const selfState = createInitialState(generateGirlfriend(() => 0.5), () => 0.5);
const initialConfidence = selfState.confidence;
const gymEffects = ACTIONS.morning.find(action => action.id === "morning-gym").effects;
applyEffects(selfState, gymEffects);
assert.ok(selfState.confidence > initialConfidence && selfState.fatigue > 0);
selfState.fatigue = 90;
applyEffects(selfState, ACTIONS.night.find(action => action.id === "early-sleep").effects);
assert.equal(selfState.fatigue, 72);
selfState.fashion = 98;
applyEffects(selfState, ACTIONS.night.find(action => action.id === "online-shopping").effects);
assert.equal(selfState.fashion, 100);
const restedWorkEffects = applySelfManagementModifiers({ fatigue:20 }, { money:50000, work:10, stress:8 });
const tiredWorkEffects = applySelfManagementModifiers({ fatigue:85 }, { money:50000, work:10, stress:8 });
assert.ok(tiredWorkEffects.money < restedWorkEffects.money);
assert.ok(tiredWorkEffects.work < restedWorkEffects.work);
assert.ok(tiredWorkEffects.stress > restedWorkEffects.stress);
const lowConfidenceEffects = applySelfManagementModifiers({ fatigue:20, confidence:40 }, { social:10, affection:10, stress:8 });
const highConfidenceEffects = applySelfManagementModifiers({ fatigue:20, confidence:80 }, { social:10, affection:10, stress:8 });
assert.ok(highConfidenceEffects.social > lowConfidenceEffects.social);
assert.ok(highConfidenceEffects.affection > lowConfidenceEffects.affection);
assert.ok(highConfidenceEffects.stress < lowConfidenceEffects.stress);
console.log("✓ 피로·패션·자신감 자기관리 행동과 수치 범위 검증 통과");
