import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics } from "../src/event-compatibility.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { DAY18_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=18;state.storyFlags={day18RuntimeComplete:true,day18CurrentHomeSafetyCompleted:true,day19CurrentSharedChorePending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true,shop:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","current-home-safety-route","verified-home-storage","bounded-emergency-access");state.scenario.introducedNpcIds.push("female-coworker","team-lead","office-best-male","best-friend","hospital-nurse");const nurse=state.npcs.find(npc=>npc.id==="hospital-nurse");nurse.active=true;nurse.storyState="introduced";state.storyHistory.push({sceneId:"m30-day18-current-home-safety",arc:"안전하게 사는 집",choiceId:"home18_access_one_time_code",day:18,response:"비상 출입 경계를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day18-current-home-safety",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};
assert.equal(FREE_MODE_EVENT_CATALOG.length,64);assert.equal(DAY18_HOME_ACTIONS.length,5);const state=create();beginStoryFreeAction(state,"day18-home-evening");assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"phone").available,true);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","unexpected-expense","small-windfall","micro-sns-like","context-day18-home-smart-lock-admin"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"lock-bounded-emergency-access",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day18-home-smart-lock-admin");assert.deepEqual(result.event.record.npcIds,["hospital-nurse"]);assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["18"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-home-safety"),null);assert.ok(resolveSituationEventChoice(state,result.event,"reject-permanent-admin"));assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day18FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFlags.day18FreeActionComplete,true);assert.equal(loaded.storyFlags["context-day18-home-smart-lock-admin:REJECTED"],true);
const noNpc=create();noNpc.scenario.introducedNpcIds=noNpc.scenario.introducedNpcIds.filter(id=>id!=="hospital-nurse");beginStoryFreeAction(noNpc,"day18-home-evening");assert.equal(getCompatibleSharedEvents(noNpc,context).some(event=>event.id===result.event.id),false);const noBoundary=create();noBoundary.scenario.unlockedActions=noBoundary.scenario.unlockedActions.filter(id=>id!=="bounded-emergency-access");beginStoryFreeAction(noBoundary,"day18-home-evening");assert.equal(getStoryFreeActions(noBoundary).some(action=>action.id==="lock-bounded-emergency-access"),false);assert.equal(getCompatibleSharedEvents(noBoundary,context).some(event=>event.id===result.event.id),false);const incomplete=create();delete incomplete.storyFlags.day18RuntimeComplete;beginStoryFreeAction(incomplete,"day18-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id===result.event.id),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY18_SCENE_ID[\s\S]*?day18FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("story-free-action-day18.test: all assertions passed");
