import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY15_CAFE_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=15;state.storyFlags={day15RuntimeComplete:true,day15CurrentLeisureDateCompleted:true,day16CurrentSocialCirclePending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true,shop:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","current-leisure-date","date-change-boundary","private-date-record");state.storyHistory.push({sceneId:"m30-day15-current-leisure-date",arc:"오늘의 여가",choiceId:"leisure15_privacy_private_note",day:15,response:"공개 범위를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"cafe",phase:"evening",activeStoryId:"m30-day15-current-leisure-date",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};
assert.equal(FREE_MODE_EVENT_CATALOG.length,64);assert.equal(DAY15_CAFE_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day15-cafe-evening");assert.equal(progress.location,"cafe");assert.equal(progress.phase,"evening");assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"map").available,true);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","unexpected-expense","small-windfall","micro-sns-like","context-day15-cafe-auto-share-prompt"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"lock-private-date-record",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day15-cafe-auto-share-prompt");assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["15"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-leisure-date"),null);assert.ok(resolveSituationEventChoice(state,result.event,"disable-auto-share"));assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day15FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["15"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"disable-auto-share");assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noMap=create();noMap.scenario.unlockedActions=noMap.scenario.unlockedActions.filter(id=>id!=="current-life-map");beginStoryFreeAction(noMap,"day15-cafe-evening");assert.equal(getCompatibleSharedEvents(noMap,{...context,mapUnlocked:false}).some(event=>event.id===result.event.id),false);const noPrivacy=create();noPrivacy.scenario.unlockedActions=noPrivacy.scenario.unlockedActions.filter(id=>id!=="private-date-record");beginStoryFreeAction(noPrivacy,"day15-cafe-evening");assert.equal(getStoryFreeActions(noPrivacy).some(action=>action.id==="lock-private-date-record"),false);assert.equal(getCompatibleSharedEvents(noPrivacy,context).some(event=>event.id===result.event.id),false);const incomplete=create();delete incomplete.storyFlags.day15RuntimeComplete;beginStoryFreeAction(incomplete,"day15-cafe-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id===result.event.id),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY15_SCENE_ID[\s\S]*?day15FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 15 카페·저녁 자유행동·자동 공개 경계 이벤트·위치/기능 필터·저장·중첩·스토리 차단 PASS");
