import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY12_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=12;state.storyFlags={day12RuntimeComplete:true,day12CurrentAccountReviewCompleted:true,day13CurrentHouseholdBudgetPending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","verified-current-account","verified-living-expenses","basic-finance-review","account-ownership-boundary");state.storyHistory.push({sceneId:"m30-day12-current-account-review",arc:"현재 계정의 주인",choiceId:"account12_access_separate_investment",day:12,response:"금융 경계를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day12-current-account-review",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};
const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};

assert.equal(FREE_MODE_EVENT_CATALOG.length,63);assert.equal(DAY12_HOME_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day12-home-evening");assert.equal(progress.location,"home");assert.equal(progress.phase,"evening");assert.equal(state.currentLocation,"home");assert.equal(state.phase,2);
assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","unexpected-expense","small-windfall","micro-sns-like","context-day12-home-investment-prompt-boundary"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"save-account-ownership-boundary",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day12-home-investment-prompt-boundary");assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["12"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-account-review"),null);
const choice=resolveSituationEventChoice(state,result.event,"dismiss-investment-prompt");assert.ok(choice);assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day12FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["12"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"dismiss-investment-prompt");assert.equal(loaded.scenario.featureUnlocks.finance,true);assert.equal(loaded.scenario.featureUnlocks.investment,undefined);assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noFinance=create();noFinance.scenario.featureUnlocks.finance=false;beginStoryFreeAction(noFinance,"day12-home-evening");assert.equal(getCompatibleSharedEvents(noFinance,{...context,financeUnlocked:false}).some(event=>event.id==="context-day12-home-investment-prompt-boundary"),false);
const noBoundary=create();noBoundary.scenario.unlockedActions=noBoundary.scenario.unlockedActions.filter(id=>id!=="account-ownership-boundary");beginStoryFreeAction(noBoundary,"day12-home-evening");assert.equal(getStoryFreeActions(noBoundary).some(action=>action.id==="save-account-ownership-boundary"),false);assert.equal(getCompatibleSharedEvents(noBoundary,context).some(event=>event.id==="context-day12-home-investment-prompt-boundary"),false);
const incomplete=create();delete incomplete.storyFlags.day12RuntimeComplete;beginStoryFreeAction(incomplete,"day12-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id==="context-day12-home-investment-prompt-boundary"),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);
const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY12_SCENE_ID[\s\S]*?day12FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 12 집·저녁 자유행동·투자 추천 경계 이벤트·금융/투자 분리·저장·중첩·스토리 차단 PASS");
