import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY14_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=14;state.storyFlags={day14RuntimeComplete:true,day14CurrentChoiceSpendingCompleted:true,day15CurrentLeisureDatePending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true,shop:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","current-choice-spending","controlled-shopping-checkout","gift-consent-boundary","basic-online-shopping");state.storyHistory.push({sceneId:"m30-day14-current-choice-spending",arc:"현재 선택 소비",choiceId:"spend14_consent_ask_first",day:14,response:"선물 동의 범위를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day14-current-choice-spending",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};
assert.equal(FREE_MODE_EVENT_CATALOG.length,64);assert.equal(DAY14_HOME_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day14-home-evening");assert.equal(progress.location,"home");assert.equal(progress.phase,"evening");assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"shop").available,true);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);
const candidates=getCompatibleSharedEvents(state,context).map(event=>event.id);assert.ok(candidates.includes("context-day14-home-saved-card-prompt"));assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"save-controlled-checkout",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day14-home-saved-card-prompt");assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["14"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-choice-spending"),null);assert.ok(resolveSituationEventChoice(state,result.event,"decline-saved-card"));assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day14FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["14"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"decline-saved-card");assert.equal(loaded.scenario.featureUnlocks.shop,true);assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noShop=create();noShop.scenario.featureUnlocks.shop=false;beginStoryFreeAction(noShop,"day14-home-evening");assert.equal(getCompatibleSharedEvents(noShop,context).some(event=>event.id===result.event.id),false);const noCheckout=create();noCheckout.scenario.unlockedActions=noCheckout.scenario.unlockedActions.filter(id=>id!=="controlled-shopping-checkout");beginStoryFreeAction(noCheckout,"day14-home-evening");assert.equal(getStoryFreeActions(noCheckout).some(action=>action.id==="save-controlled-checkout"),false);assert.equal(getCompatibleSharedEvents(noCheckout,context).some(event=>event.id===result.event.id),false);const incomplete=create();delete incomplete.storyFlags.day14RuntimeComplete;beginStoryFreeAction(incomplete,"day14-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id===result.event.id),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY14_SCENE_ID[\s\S]*?day14FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 14 집·저녁 자유행동·저장 결제 경계 이벤트·쇼핑/금융 필터·저장·중첩·스토리 차단 PASS");
