import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY11_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=11;state.storyFlags={day11RuntimeComplete:true,day11CurrentLifePlanCompleted:true,day12CurrentAccountReviewPending:true,haeun_contact_unlocked:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","current-week-anchor","schedule-conflict-rule","shared-calendar-boundary","protected-buffer-time");state.storyHistory.push({sceneId:"m30-day11-current-life-plan",arc:"현재 생활표",choiceId:"life11_share_changes_only",day:11,response:"공유 범위를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day11-current-life-plan",phoneUnlocked:true,financeUnlocked:false,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};
const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};

assert.equal(FREE_MODE_EVENT_CATALOG.length,63);assert.equal(DAY11_HOME_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day11-home-evening");assert.equal(progress.location,"home");assert.equal(progress.phase,"evening");assert.equal(state.currentLocation,"home");assert.equal(state.phase,2);
assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"map").available,true);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","micro-sns-like","context-day11-home-protected-buffer"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"sync-shared-calendar-boundary",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day11-home-protected-buffer");assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["11"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-life-planning"),null);
const choice=resolveSituationEventChoice(state,result.event,"lock-buffer-time");assert.ok(choice);assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day11FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["11"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"lock-buffer-time");assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noBuffer=create();noBuffer.scenario.unlockedActions=noBuffer.scenario.unlockedActions.filter(id=>id!=="protected-buffer-time");beginStoryFreeAction(noBuffer,"day11-home-evening");assert.equal(getCompatibleSharedEvents(noBuffer,context).some(event=>event.id==="context-day11-home-protected-buffer"),false);
const noCalendar=create();noCalendar.scenario.unlockedActions=noCalendar.scenario.unlockedActions.filter(id=>id!=="shared-calendar-boundary");beginStoryFreeAction(noCalendar,"day11-home-evening");assert.equal(getStoryFreeActions(noCalendar).some(action=>action.id==="sync-shared-calendar-boundary"),false);assert.equal(getCompatibleSharedEvents(noCalendar,context).some(event=>event.id==="context-day11-home-protected-buffer"),false);
const incomplete=create();delete incomplete.storyFlags.day11RuntimeComplete;beginStoryFreeAction(incomplete,"day11-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id==="context-day11-home-protected-buffer"),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);
const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY11_SCENE_ID[\s\S]*?day11FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 11 집·저녁 자유행동·보호된 완충 시간 이벤트·기능/완료 필터·저장·중첩·스토리 차단 PASS");
