import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY17_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=17;state.storyFlags={day17RuntimeComplete:true,day17CurrentHealthRoutineCompleted:true,day18CurrentHomeSafetyPending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true,shop:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","verified-current-prescription","current-health-routine","health-data-boundary");state.scenario.introducedNpcIds.push("female-coworker","team-lead","office-best-male","best-friend","hospital-nurse");const nurse=state.npcs.find(npc=>npc.id==="hospital-nurse");nurse.active=true;nurse.storyState="introduced";state.storyHistory.push({sceneId:"m30-day17-current-health-routine",arc:"지금의 몸",choiceId:"health17_data_private_summary",day:17,response:"건강 데이터 경계를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day17-current-health-routine",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};
assert.equal(FREE_MODE_EVENT_CATALOG.length,63);assert.equal(DAY17_HOME_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day17-home-evening");assert.equal(progress.location,"home");assert.equal(progress.phase,"evening");assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"phone").available,true);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","unexpected-expense","small-windfall","micro-sns-like","context-day17-home-health-share-prompt"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"lock-health-data-boundary",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day17-home-health-share-prompt");assert.deepEqual(result.event.record.npcIds,["hospital-nurse"]);assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["17"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-health-routine"),null);assert.ok(resolveSituationEventChoice(state,result.event,"disable-continuous-health-share"));assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day17FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["17"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"disable-continuous-health-share");assert.ok(loaded.scenario.introducedNpcIds.includes("hospital-nurse"));assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noNpc=create();noNpc.scenario.introducedNpcIds=noNpc.scenario.introducedNpcIds.filter(id=>id!=="hospital-nurse");beginStoryFreeAction(noNpc,"day17-home-evening");assert.equal(getCompatibleSharedEvents(noNpc,context).some(event=>event.id===result.event.id),false);const noBoundary=create();noBoundary.scenario.unlockedActions=noBoundary.scenario.unlockedActions.filter(id=>id!=="health-data-boundary");beginStoryFreeAction(noBoundary,"day17-home-evening");assert.equal(getStoryFreeActions(noBoundary).some(action=>action.id==="lock-health-data-boundary"),false);assert.equal(getCompatibleSharedEvents(noBoundary,context).some(event=>event.id===result.event.id),false);const incomplete=create();delete incomplete.storyFlags.day17RuntimeComplete;beginStoryFreeAction(incomplete,"day17-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id===result.event.id),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY17_SCENE_ID[\s\S]*?day17FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 17 집·저녁 자유행동·건강 상시 공유 이벤트·NPC/건강 필터·저장·중첩·스토리 차단 PASS");
