import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY13_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=13;state.storyFlags={day13RuntimeComplete:true,day13CurrentHouseholdBudgetCompleted:true,day14CurrentChoiceSpendingPending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","current-budget-base","shared-expense-consent","current-household-budget","household-buffer-boundary");state.storyHistory.push({sceneId:"m30-day13-current-household-budget",arc:"합의된 만큼만 공동",choiceId:"budget13_review_totals_only",day:13,response:"공동 장부 범위를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day13-current-household-budget",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};
assert.equal(FREE_MODE_EVENT_CATALOG.length,64);assert.equal(DAY13_HOME_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day13-home-evening");assert.equal(progress.location,"home");assert.equal(progress.phase,"evening");assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","unexpected-expense","small-windfall","micro-sns-like","context-day13-home-full-link-prompt"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"record-shared-expense-consent",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day13-home-full-link-prompt");assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["13"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-budget-agreement"),null);assert.ok(resolveSituationEventChoice(state,result.event,"reject-full-account-link"));assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day13FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["13"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"reject-full-account-link");assert.equal(loaded.scenario.featureUnlocks.finance,true);assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noFinance=create();noFinance.scenario.featureUnlocks.finance=false;beginStoryFreeAction(noFinance,"day13-home-evening");assert.equal(getCompatibleSharedEvents(noFinance,{...context,financeUnlocked:false}).some(event=>event.id==="context-day13-home-full-link-prompt"),false);const noConsent=create();noConsent.scenario.unlockedActions=noConsent.scenario.unlockedActions.filter(id=>id!=="shared-expense-consent");beginStoryFreeAction(noConsent,"day13-home-evening");assert.equal(getStoryFreeActions(noConsent).some(action=>action.id==="record-shared-expense-consent"),false);assert.equal(getCompatibleSharedEvents(noConsent,context).some(event=>event.id==="context-day13-home-full-link-prompt"),false);const incomplete=create();delete incomplete.storyFlags.day13RuntimeComplete;beginStoryFreeAction(incomplete,"day13-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id==="context-day13-home-full-link-prompt"),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY13_SCENE_ID[\s\S]*?day13FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 13 집·저녁 자유행동·전체 계정 연결 경계 이벤트·금융/사생활 필터·저장·중첩·스토리 차단 PASS");
