import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialState } from "../src/game-core.mjs";
import { createGirlfriendFromProfile } from "../src/girlfriend-manager.mjs";
import { SaveManager } from "../src/save-manager.mjs";
import { GAME_MODES } from "../src/scenario-state.mjs";
import { resolveSituationEventChoice } from "../src/situation-event-manager.mjs";
import { DAY16_HOME_ACTIONS, beginStoryFreeAction, completeStoryFreeAction, getStoryFeatureAvailability, getStoryFreeActions, markStoryFreeActionEventComplete, resolveStoryFreeAction } from "../src/story-free-action-manager.mjs";
import { FREE_MODE_EVENT_CATALOG, getCompatibleSharedEvents, getEventCompatibilityDiagnostics, getSharedEventById } from "../src/event-compatibility.mjs";

const create=()=>{const state=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.MARRIAGE_30});state.day=16;state.storyFlags={day16RuntimeComplete:true,day16CurrentSocialCircleCompleted:true,day17CurrentHealthRoutinePending:true,haeun_contact_unlocked:true};state.scenario.featureUnlocks={finance:true,shop:true};state.scenario.unlockedActions.push("smartphone-basic","day5-work-trial","past-contacts-index","current-life-map","current-social-circle","best-friend-current-contact","friend-group-consent");state.scenario.introducedNpcIds.push("female-coworker","team-lead","office-best-male","best-friend");state.scenario.profileUnlocks.push("jihun-current");state.storyHistory.push({sceneId:"m30-day16-current-social-circle",arc:"한 명씩 다시",choiceId:"social16_sharing_current_notes",day:16,response:"공유 범위를 정했다."});return state;};
const context={occurrence:"free-action-result",location:"home",phase:"evening",activeStoryId:"m30-day16-current-social-circle",phoneUnlocked:true,financeUnlocked:true,jobUnlocked:true,mapUnlocked:true,healthRiskAllowed:false};const storage=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};
assert.equal(FREE_MODE_EVENT_CATALOG.length,64);assert.equal(DAY16_HOME_ACTIONS.length,5);const state=create(),progress=beginStoryFreeAction(state,"day16-home-evening");assert.equal(progress.location,"home");assert.equal(progress.phase,"evening");assert.equal(getStoryFreeActions(state).length,5);assert.equal(getStoryFeatureAvailability(state,"contacts").available,true);assert.equal(getStoryFeatureAvailability(state,"investment").available,false);assert.deepEqual(getCompatibleSharedEvents(state,context).map(event=>event.id),["date-cancelled","unexpected-expense","small-windfall","micro-sns-like","context-day16-home-past-group-invite"]);assert.equal(getEventCompatibilityDiagnostics(state,{...context,occurrence:"story-dialogue"}).filter(event=>event.eligible).length,0);
let roll=0;const result=resolveStoryFreeAction(state,"lock-friend-group-consent",{random:()=>roll++===0?.1:0});assert.equal(result.status,"EVENT");assert.equal(result.event.id,"context-day16-home-past-group-invite");assert.deepEqual(result.event.record.npcIds,["best-friend"]);assert.ok(result.event.scenes.length);assert.equal(result.event.choices.length,2);assert.equal(state.eventCompatibility.dailyCounts["16"],1);assert.equal(resolveStoryFreeAction(state,"rest-after-social-check"),null);assert.ok(resolveSituationEventChoice(state,result.event,"cancel-group-invite"));assert.equal(markStoryFreeActionEventComplete(state,result.event.id),true);assert.equal(completeStoryFreeAction(state),true);assert.equal(state.storyFlags.day16FreeActionComplete,true);assert.equal(completeStoryFreeAction(state),false);
const store=storage();SaveManager.save(state,store);const loaded=SaveManager.load(store);assert.equal(loaded.storyFreeAction.status,"COMPLETE");assert.equal(loaded.eventCompatibility.dailyCounts["16"],1);assert.equal(loaded.situationEventStates[result.event.id].choiceId,"cancel-group-invite");assert.ok(loaded.scenario.introducedNpcIds.includes("best-friend"));assert.equal(getSharedEventById(result.event.id).id,result.event.id);
const noNpc=create();noNpc.scenario.introducedNpcIds=noNpc.scenario.introducedNpcIds.filter(id=>id!=="best-friend");beginStoryFreeAction(noNpc,"day16-home-evening");assert.equal(getCompatibleSharedEvents(noNpc,context).some(event=>event.id===result.event.id),false);const noConsent=create();noConsent.scenario.unlockedActions=noConsent.scenario.unlockedActions.filter(id=>id!=="friend-group-consent");beginStoryFreeAction(noConsent,"day16-home-evening");assert.equal(getStoryFreeActions(noConsent).some(action=>action.id==="lock-friend-group-consent"),false);assert.equal(getCompatibleSharedEvents(noConsent,context).some(event=>event.id===result.event.id),false);const incomplete=create();delete incomplete.storyFlags.day16RuntimeComplete;beginStoryFreeAction(incomplete,"day16-home-evening");assert.equal(getCompatibleSharedEvents(incomplete,context).some(event=>event.id===result.event.id),false);
const free=createInitialState(createGirlfriendFromProfile("haeun",()=>.5),()=>.5,{mode:GAME_MODES.FREE_ROMANCE});assert.equal(free.scenario.enabled,false);assert.equal(free.storyFreeAction,undefined);const gameSource=readFileSync(new URL("../game.js",import.meta.url),"utf8");assert.match(gameSource,/completedSession\?\.id===LOCKED_DAY16_SCENE_ID[\s\S]*?day16FreeActionComplete/);assert.match(gameSource,/fromStoryFreeAction/);assert.match(gameSource,/getSharedEventById\(saved\.activeEvent\)/);
console.log("✓ DAY 16 집·저녁 자유행동·단체방 초대 이벤트·NPC/기능 필터·저장·중첩·스토리 차단 PASS");
